### ISSUE TITLE
v1.6.1(58) - 更新后.cpp文件打不开不能查看了

### ISSUE THREAD

**Issue by ikongziming** [PPHubApp/PPHub-Feedback#127]
运行环境: iPhone X - iOS11.4.1 - PPHub v1.6.1(58)

**Comment by jkpang** [comment]
我这边是可以看C++的文件的，可能是你打开的.cpp文件太大了（超过2000行），可能等待的时间比较久一点。
![wechatimg1](https://user-images.githubusercontent.com/17583451/45027579-5f844900-b074-11e8-924f-971f9ef1b8d1.jpeg)
@ikongziming
