### ISSUE TITLE
v1.6.2(59) - 希望有clone功能

### ISSUE THREAD

**Issue by RenzHoly** [PPHubApp/PPHub-Feedback#140]
运行环境: iPhone XS Max - iOS12.0 - PPHub v1.6.2(59)

**Comment by jkpang** [comment]
下个版本（v1.8.4）将会支持导入链接到Working Copy，在Working Copy上可以进行Clong，Push，Pull等操作 @RenzHoly

**Comment by jkpang** [comment]
您好，v1.8.4已更新，支持导入链接到Working Copy，在Working Copy上可以进行Clong，Push，Pull等操作。快去更新吧 @RenzHoly
