### ISSUE TITLE
v1.6.2(59) - A dark mode would be...

### ISSUE THREAD

**Issue by maxwelljordanwhite** [PPHubApp/PPHub-Feedback#144]
A dark mode would be amazing.

Environment: iPhone X - iOS12.1 - PPHub v1.6.2(59)

**Comment by jkpang** [comment]
PPHub v2.0.0 is available
- Added: Dark Mode (Dark Mode);
- Added: Perfect support for iPad multitasking split screen mode;
- Optimization: adjust the layout and style of UI controls.
