### ISSUE TITLE
v1.6.2(59) - 没有 Haptic Feedback

### ISSUE THREAD

**Issue by viduy** [PPHubApp/PPHub-Feedback#146]
Environment: iPhone XS - iOS12.0.1 - PPHub v1.6.2(59)

**Comment by jkpang** [comment]
Hello，请问设置页面中Haptic Feedback（触感反馈）的开关有没有打开？是哪些操作没有触感反馈？目前PPHub只有在下拉刷新、Star / Follow、二次点击同一个底栏按钮这些操作下才有Haptic Feedback @viduy

**Comment by viduy** [comment]
点击底部栏：「搜索」二次点击没有震动反馈 其余的点击底栏按钮两次都会触发刷新（有震动）

**Comment by jkpang** [comment]
嗯嗯，搜索界面目前没有加入二次点击底栏刷新、震动，之后的版本我会考虑是否加上，感谢反馈 @viduy

**Comment by viduy** [comment]
OK
