### ISSUE TITLE
v1.6.3(60) - 除了项目有收藏功能 也可以收藏某文件 譬...

### ISSUE THREAD

**Issue by tanglianggithub** [PPHubApp/PPHub-Feedback#157]
除了项目有收藏功能 也可以收藏某文件 譬如我想看某个项目比较深的目录下面的文件 每次都要点击很多次才能找到 比较麻烦

运行环境: iPhone 8 - iOS12.0 - PPHub v1.6.3(60)

**Comment by jkpang** [comment]
因为GitHub官方没有提供对应的收藏的Api，自己也没有后端服务器，这个功能暂时可能实现不了，不过我会持续关注你的这个建议。感谢反馈 @tanglianggithub

**Comment by tanglianggithub** [comment]
收藏都放到手机本地呢？

**Comment by tanglianggithub** [comment]
希望能有把某个项目缓存到手机的功能。这样在网络不好或者没有网络的时候，仍然可以看一些项目。
是否缓存到本地是可选的。
类似微信把很多内容都缓存到手机里一样。
