### ISSUE TITLE
v1.7.0(61) - 回复没有   艾特功能，要手动输入，我建...

### ISSUE THREAD

**Issue by Mnufs** [PPHubApp/PPHub-Feedback#166]
回复没有   艾特功能，要手动输入，我建议测一下这方面功能，或者是我没发现，谁告诉下我。

运行环境: iPhone X - iOS12.1 - PPHub v1.7.0(61)

**Comment by Mnufs** [comment]
@jkpang  好吧，感谢。

**Comment by jkpang** [comment]
v1.8.0已更新 @Mnufs
