### ISSUE TITLE
v1.7.1(68) - 打开代码时显示 没有请求到数据?

### ISSUE THREAD

**Issue by MaoxianCk** [PPHubApp/PPHub-Feedback#175]
运行环境: iPhone 6 Plus - iOS11.4.1 - PPHub v1.7.1(68)

**Comment by jkpang** [comment]
嗯嗯，某些文件确实存在打不开的情况。我目前认为原因可能是这些文件转换成iOS系统的编码失败造成的。
这个问题我现在还没有找到解决的方案，不过我会持续关注这个问题。临时解决方案：点击右上角的分享-打开网页 查看
