### ISSUE TITLE
v1.7.1(68) - 有一个问题，在分享给微信好友的时候会卡住...

### ISSUE THREAD

**Issue by FlyEgle** [PPHubApp/PPHub-Feedback#186]
有一个问题，在分享给微信好友的时候会卡住不动。微信也同样

运行环境: iPhone 8 Plus - iOS12.1 - PPHub v1.7.1(68)

**Comment by jkpang** [comment]
刚试了一下，在点击微信分享后确实会需要等一会儿才弹出分享到微信的界面。我试了其他的应用，也是同样的现象。我猜测是微信的分享插件在分享时在主线程执行了比较耗时的操作导致的
