### ISSUE TITLE
v1.7.2(69) - 评论列表好像还缺少指定回复的功能，除此之...

### ISSUE THREAD

**Issue by javacodecreeks** [PPHubApp/PPHub-Feedback#190]
评论列表好像还缺少指定回复的功能，除此之外基本功能也基本上有了，还望以后坚持更新。加油！

运行环境: iPhone 6 - iOS12.1 - PPHub v1.7.2(69)

**Comment by jkpang** [comment]
下个版本将会加上这个功能，感谢反馈 @javacodecreeks

**Comment by jkpang** [comment]
v1.8.0已更新 @javacodecreeks
