### ISSUE TITLE
v1.7.3(70) - 总是打不开代码（一直显示转圈的加载动画）...

### ISSUE THREAD

**Issue by yikaiw** [PPHubApp/PPHub-Feedback#194]
总是打不开代码（一直显示转圈的加载动画），相同的网络下另一个手机端github软件CodeHub就可以迅速加载出代码。

运行环境: iPhone X - iOS12.0.1 - PPHub v1.7.3(70)

**Comment by jkpang** [comment]
请问是打开哪个仓库会有这个问题？还是说你这边打开每个仓库都会有这个问题？

**Comment by yikaiw** [comment]
每个仓库都有这个问题。README迅速就加载出来了，但是点仓库里的Python程序就加载很久，有时候加载很久也加载不出来

**Comment by jkpang** [comment]
咦，奇怪，我查看了你的好几个Python仓库代码，基本上都是秒开，我的网络环境是联通4g / 移动50M宽带
