### ISSUE TITLE
v1.7.3(70) - why cannot I see the...

### ISSUE THREAD

**Issue by ZichengQu** [PPHubApp/PPHub-Feedback#195]
why cannot I see the code in private repositories, it shows no request to data.

运行环境: iPad 2017 - iOS12.1 - PPHub v1.7.3(70)

**Comment by ZichengQu** [comment]
我看到了底下的解决方案，能在网页版打开也可以，但希望能尽快修复这个bug。

还有一个bug，假如我的master分支为空，选择issues上面的那个button的时候会闪退。

**Comment by jkpang** [comment]
你好，第一个问题查看某些代码文件请求不到数据，是文本编码解码失败造成的，我尝试了很多解决方案都失败了，不过我还在继续寻找可行的方法
第二个问题可以告诉我是哪个仓库吗？我这边找不到一个master分支为空的仓库

**Comment by jkpang** [comment]
OK，非常感谢你的反馈，我会尽快修复这个问题

**Comment by jkpang** [comment]
v1.8.0我已尝试修复仓库Branch为空崩溃的bug，请问你这边更新版本后还会出现这个问题吗？ @ZichengQu
