### ISSUE TITLE
v1.7.3(70) - 希望加个黑夜🌌主题

### ISSUE THREAD

**Issue by harrychan19** [PPHubApp/PPHub-Feedback#197]
运行环境: iPhone X - iOS12.1 - PPHub v1.7.3(70)

**Comment by jkpang** [comment]
嗯嗯，这个我会考虑的，感谢你的建议😊

**Comment by jkpang** [comment]
你好，v2.0.0版本增加黑暗模式，快去更新吧！ @harrychan19
