### ISSUE TITLE
v1.7.3(70) - maybe you can add a ...

### ISSUE THREAD

**Issue by harrychan19** [PPHubApp/PPHub-Feedback#198]
maybe you can add a dark theme

运行环境: iPhone X - iOS12.1 - PPHub v1.7.3(70)

**Comment by jkpang** [comment]
PPHub v2.0.0 is available
- Added: Dark Mode (Dark Mode);
- Added: Perfect support for iPad multitasking split screen mode;
- Optimization: adjust the layout and style of UI controls.

@harrychan19
