### ISSUE TITLE
v1.7.3(70) - 什么时候能支持把代码clone 到本地呢

### ISSUE THREAD

**Issue by geeyu** [PPHubApp/PPHub-Feedback#199]
运行环境: iPad Pro 10.5 Inch - iOS12.1.1 - PPHub v1.7.3(70)

**Comment by jkpang** [comment]
您好，目前没有这个打算，个人认为git clone到移动设备没有意义。到桌面端才具有生产力 @geeyu

**Comment by geeyu** [comment]
您好~ 感谢回复~ 其实是有些时候会遇到没有网络的情况,如果能把项目缓存到本地的话,就可以随时查看了~  希望如果有可能的话,能够支持一下~ 
无论将来有没有这样的计划,感谢~ app很赞~

**Comment by jkpang** [comment]
嗯嗯，感谢您的反馈，这个Feature我以后会尝试下，不一定会上这个功能，谢谢哈😊

**Comment by jkpang** [comment]
> 您好~ 感谢回复~ 其实是有些时候会遇到没有网络的情况,如果能把项目缓存到本地的话,就可以随时查看了~ 希望如果有可能的话,能够支持一下~
无论将来有没有这样的计划,感谢~ app很赞~

下个版本将会支持导入链接到Working Copy，在Working Copy上可以进行Clong，Push，Pull等操作 @geeyu

**Comment by jkpang** [comment]
您好，v1.8.4已更新，支持导入链接到Working Copy，在Working Copy上可以进行Clong，Push，Pull等操作。快去更新吧 @geeyu
