### ISSUE TITLE
v1.7.3(70) - readme 文件 更新不及时

### ISSUE THREAD

**Issue by ChengLuffy** [PPHubApp/PPHub-Feedback#202]
以 [gitme](https://github.com/flutterchina/gitme) 为例，我之前查看 readme 文件 并 starred，近期查看发现 readme 没有更新到最新的状态，在点击右上角刷新按钮时更新到最新状态。

**Comment by jkpang** [comment]
嗯嗯，加载Readme会有缓存，为了二次加载更加快速。点击Readme一栏的刷新按钮可以获得最新的数据 @ChengLuffy

**Comment by jkpang** [comment]
还可以通过设置-清除缓存来达到目的。因为目前无法通过GitHub的官方接口得知仓库的Readme内容相对于上一次访问是否发生了改变，如果每次都加载最新的Readme，用户二次进入同一仓库的时间与流量成本会变大（国内访问GitHub的速度你懂得），体验不是很好。
这个问题我以后会不断尝试最优的解决方案，感谢你的反馈 @ChengLuffy

**Comment by ChengLuffy** [comment]
也是，墙的存在让用户分成了可以快速访问和慢速访问两种，或许可以把这个暴露给用户选择，但好像又小题大做了，谢谢回复

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jkpang** [comment]
下个版本将优化此问题
