### ISSUE TITLE
v1.8.1(75) - 私有仓库提交代码没有contributi...

### ISSUE THREAD

**Issue by PPythonic** [PPHubApp/PPHub-Feedback#204]
私有仓库提交代码没有contributions记录

运行环境: iPhone XR - iOS12.1.2 - v1.8.1(75)

**Comment by jkpang** [comment]
您好，这种问题可以检查：
- 登录时是否使用了私有访问仓库的授权
- 代码是否是commit到master分支或默认分支
- 网页上commits是否设置了私有仓库提交对外可见 @PPythonic

**Comment by PPythonic** [comment]
ok.网页上commits设置私有仓库提交对外可见,小组件正常显示,问题解决 :-)
