### ISSUE TITLE
v1.8.1(75) - 搜索框在ipad下。有bug。看不见输入...

### ISSUE THREAD

**Issue by hanwenbo** [PPHubApp/PPHub-Feedback#206]
搜索框在ipad下。有bug。看不见输入的字。也看不到输入框

运行环境: iPad Pro 12.9 Inch 3 - iOS12.1.1 - v1.8.1(75)

**Comment by hanwenbo** [comment]
@jkpang 好的  晚上，这个问题是你把ipad关闭上    过个个把小时再进来  还是那个界面 但搜索框及底部的tabbar都是点击不了的  上次搜索的结果内容 被某个元素挡住了 listview的上半部分可以点 下半部分不可以点，重复上面的操作 每次都会遇到   我需要把app上滑销毁掉，再进来才能解决。  这个问题 我怀疑是ipad再次打开，横屏的情况下  它默认是初始化是竖屏点击区域导致 虽然看着是横屏 但貌似点击的区域被挡了 是竖屏的感觉。（我都是在横屏下使用 我是新版的ipad 用了键盘）

**Comment by jkpang** [comment]
我知道了，是你的iPad连接了外接键盘造成的，键盘的虚拟工具栏挡住了底部TabBar导致你点击不了。你可以点击工具栏最右边的“降下”按钮就行了，如下图红色箭头所指的位置：
![image](https://user-images.githubusercontent.com/17583451/51096135-42674000-17f5-11e9-9d57-13ce6959db8b.png)
@hanwenbo

**Comment by hanwenbo** [comment]
不是这个问题 我确定是个bug   晚上我给你拍视频

**Comment by hanwenbo** [comment]
![image](https://user-images.githubusercontent.com/5869741/51423292-dd4a8a80-1bf8-11e9-88c2-0e505b5071aa.png)
搜索框是不是不见了  只要想复现，点击任意一条  左滑回来就这样

**Comment by hanwenbo** [comment]
顶部输入框不见了   只有销毁app再开  我每天每次搜索一次就要关一次再进

**Comment by hanwenbo** [comment]
好的

**Comment by hanwenbo** [comment]
是什么原因导致的？怎么解决的呢？

**Comment by jkpang** [comment]
> 是什么原因导致的？怎么解决的呢？

是iOS11+系统的原因，苹果调整了UINavigationBar的层级与布局方案。给UISearchBar套上一个UIView，采用AutoLayout布局就好了 @hanwenbo

**Comment by hanwenbo** [comment]
好的 谢谢 学习了 或许以后也会遇到

**Comment by jkpang** [comment]
v1.8.2已修复了此问题，快去更新吧 @hanwenbo
