### ISSUE TITLE
v1.8.1(75) - commits 记录只能看到默认分支的记...

### ISSUE THREAD

**Issue by zxh326** [PPHubApp/PPHub-Feedback#207]
commits 记录只能看到默认分支的记录？这是bug还是feature

运行环境: iPhone XS - iOS12.1.1 - v1.8.1(75)

**Comment by jkpang** [comment]
是Bug，下个版本将可以看到其它分支的commits @zxh326

**Comment by jkpang** [comment]
v1.8.2已可以查看其他分支的Commits（在详情页切换分支后再查看Commits），快去更新吧 @zxh326
