### ISSUE TITLE
v1.8.1(75) - news 怎么没东西了

### ISSUE THREAD

**Issue by NevermoreDong** [PPHubApp/PPHub-Feedback#208]
运行环境: iPhone XS - iOS12.1.2 - v1.8.1(75)

**Comment by jkpang** [comment]
News模块没有数据可能是因为您的GitHub账号：
- 没有Follow任何用户或您Follow的用户没有相关动态
- 没有Watch任何代码库或您Watch的代码库没有相关动态
- 其他用户没有对您的公开代码库提出Issues或者Pull request

希望能帮到您 @NevermoreDong
