### ISSUE TITLE
首次登录 Authorize PPHub 灰色点不了

### ISSUE THREAD

**Issue by mokeychan** [PPHubApp/PPHub-Feedback#210]
作者麻烦看下

**Comment by mokeychan** [comment]
[![kAC4Wn.md.png](https://s2.ax1x.com/2019/01/22/kAC4Wn.md.png)](https://imgchr.com/i/kAC4Wn)

**Comment by jkpang** [comment]
可能是网络的原因，导致这个授权网页没有完全加载。换下手机网络或其他WiFi试试~ @mokeychan

**Comment by mokeychan** [comment]
@jkpang 还是没有作用，no idea..

**Comment by jkpang** [comment]
嗯嗯，我邮件发你测试账号看能不能行 @mokeychan

**Comment by mokeychan** [comment]
收到了，一样的没成功。有条件能换个设备或者其他人试试嚒

**Comment by mokeychan** [comment]
或者能否网页版授权？然后ios上直接登录

**Comment by jkpang** [comment]
奇怪，我这边两台设备iPhone 6s与iPhone7，还有我的两个账号重新授权都是可以的。要不你卸载重装试试？如果你这边方便，可以加下PPHub交流群（616587242）解决这个问题 @mokeychan

**Comment by jkpang** [comment]
我大概知道原因了，可能是你低版本的iOS系统导致授权按钮不可点击。我手上的两台都是iOS11+的系统
我邮箱已经发你授权地址了，你试试用电脑浏览器打开，然后在使用PPHub登录
