### ISSUE TITLE
v1.8.2(81) - 为什么在app和github网页中搜索相...

### ISSUE THREAD

**Issue by lushans** [PPHubApp/PPHub-Feedback#214]
为什么在app和github网页中搜索相同的关键词，显示的结果不一样？ app中不相关的结果太多

运行环境: iPhone 6s - iOS12.1 - v1.8.2(81)

**Comment by jkpang** [comment]
网页搜索默认是Best match（最佳）排序，App搜索是默认仓库的Star降序排序 @lushans 

网页：
![网页](https://user-images.githubusercontent.com/17583451/51797402-ff1dc000-223d-11e9-91b3-4f4e71719bf0.png)

App
![App](https://user-images.githubusercontent.com/17583451/51797401-e90fff80-223d-11e9-852a-ea442a6e1c92.png)

**Comment by lushans** [comment]
您好，app 不支持最佳排序，对不对？

**Comment by jkpang** [comment]
> 您好，app 不支持最佳排序，对不对？

嗯嗯，目前的版本不支持。现支持按Star/Forks/Update 与 降序/升序这几种排列组合的方式过滤
以后我会优化搜索模块的机制

**Comment by lushans** [comment]
> > 您好，app 不支持最佳排序，对不对？
> 
> 嗯嗯，目前的版本不支持。现支持按Star/Forks/Update 与 降序/升序这几种排列组合的方式过滤
> 以后我会优化搜索模块的机制
嗯嗯 好的，另外说一句，app挺好用的，很满意，谢谢。

**Comment by jkpang** [comment]
感谢😊
