### ISSUE TITLE
v1.8.3(83) - 显示Repo中issue数量与pr数量不...

### ISSUE THREAD

**Issue by orangedeng** [PPHubApp/PPHub-Feedback#216]
显示Repo中issue数量与pr数量不正确

运行环境: iPhone 8 - iOS12.1.2 - v1.8.3(83)

**Comment by jkpang** [comment]
已找到解决方案，下个版本将修复这个问题，感谢反馈 @orangedeng

**Comment by jkpang** [comment]
您好，v1.8.4已修复此问题，现已可更新 @orangedeng
