### ISSUE TITLE
v1.8.3(83) - 如图，https://i.loli.ne...

### ISSUE THREAD

**Issue by wizyoung** [PPHubApp/PPHub-Feedback#217]
如图，https://i.loli.net/2019/02/02/5c55389490cc8.jpeg  1 hours ago, hour应该单数

运行环境: iPhone X - iOS12.1.3 - v1.8.3(83)

**Comment by jkpang** [comment]
您好，v1.8.4已修复了这个问题，感谢您的反馈 @wizyoung
