### ISSUE TITLE
v1.8.3(83) - 点击qq号码无法调用qq

### ISSUE THREAD

**Issue by qiuzefan** [PPHubApp/PPHub-Feedback#218]
运行环境: iPhone XR - iOS12.0 - v1.8.3(83)

**Comment by jkpang** [comment]
如果你安装的是TIM是无法调起的 @qiuzefan

**Comment by qiuzefan** [comment]
我的是qq

发自我的 iPhone

**Comment by jkpang** [comment]
我这边试了好几次都可以调起，QQ的版本为v7.9.8.464。我是Copy官方提供调起QQ的代码 @qiuzefan

**Comment by qiuzefan** [comment]
就这样然后打不开

发自我的 iPhone

**Comment by jkpang** [comment]
emmm....我试了身边3台iPhone都是可以调起QQ的。对于您现在的这种情况，建议您直接搜索QQ群号添加： **616587242**，感谢反馈！ @qiuzefan
