### ISSUE TITLE
v1.8.3(83) - 小组件显示提交状态时不是最新的提交状态，...

### ISSUE THREAD

**Issue by tracerZzz** [PPHubApp/PPHub-Feedback#220]
小组件显示提交状态时不是最新的提交状态，可否将最新的提交状态显示在小组件里

运行环境: iPhone XS Max - iOS12.1.4 - v1.8.3(83)

**Comment by jkpang** [comment]
您好，这种情况可能由以下几种原因造成：   
- 代码未提交至master分支
- GitHub网页未设置私有仓库提交数量对外可见     

 @tracerZzz

**Comment by jkpang** [comment]
GitHub网页设置私有仓库提交数量对外可见: 

![image](https://user-images.githubusercontent.com/17583451/52764537-961ab280-305b-11e9-887e-44bae178fdc6.png)

**Comment by tracerZzz** [comment]
多谢，已经解决，正如您所讲，是私有仓库的问题

**Comment by jkpang** [comment]
感谢您的使用 @tracerZzz
