### ISSUE TITLE
v1.8.3(83) - 加载  .yml文件失败，提示“没有请求...

### ISSUE THREAD

**Issue by PangXingwang** [PPHubApp/PPHub-Feedback#223]
加载  .yml文件失败，提示“没有请求到数据”。

运行环境: iPhone 6s - iOS12.1.2 - v1.8.3(83)

**Comment by jkpang** [comment]
你好，方便贴下这个.yml的地址吗？（如果是私有库就算啦）
造成此类问题的原因应该是文件转码失败造成的，这个问题有其他用户遇到过 #212 ，我还在寻找解决方案，感谢反馈 @PangXingwang

**Comment by PangXingwang** [comment]
今天测试了一下，
https://github.com/PangXingwang/cloud-eurekas/blob/master/cloud-eureka-8762/src/main/resources/application.yml 这个.yml 文档可以打开
https://github.com/PangXingwang/cloud-eurekas/blob/master/cloud-eureka-8761/src/main/resources/application.yml 这个.yml 文档 提示“没有请求到数据”
这两个文档几乎一样。

**Comment by jkpang** [comment]
嗯嗯，我用App确实打不开第二个文件，我用Chrome打开了第二个文件的原始数据：https://raw.githubusercontent.com/PangXingwang/cloud-eurekas/master/cloud-eureka-8761/src/main/resources/application.yml
里面有一部分乱码，这应该就是原因，但目前还没找到解决方案，我会持续跟进这个问题，感谢反馈！
![image](https://user-images.githubusercontent.com/17583451/53151684-cb407b00-35ee-11e9-88a9-3a15ec822e43.png)
@PangXingwang
