### ISSUE TITLE
v1.8.3(83) - 请问加入ipynb文件的兼容性提上日程了...

### ISSUE THREAD

**Issue by IMath123** [PPHubApp/PPHub-Feedback#225]
请问加入ipynb文件的兼容性提上日程了吗？请问有没有个预估完成的时间

运行环境: iPad Pro 10.5 Inch - iOS12.1.4 - v1.8.3(83)

**Comment by jkpang** [comment]
抱歉哈，目前没有找到iOS端解析ipynb的方案（只能使用网页的方式查看了），这个Feature暂时不会提上日程了，建议在PC端或者使用专业加载ipynb的软件来查看。非常感谢您的使用😊 @IMath123

**Comment by jkpang** [comment]
你好，v1.9.0已审核通过，现在已可以查看.ipynb文件 @IMath123
