### ISSUE TITLE
v1.8.3(83) - Developers每次都请求不到数据

### ISSUE THREAD

**Issue by ckjbug** [PPHubApp/PPHub-Feedback#226]
运行环境: iPhone 7 Plus - iOS12.1 - v1.8.3(83)

**Comment by jkpang** [comment]
您好，这是因为GitHub Trending 官方偶尔间歇性的无数据造成的。我遇到过好几次，通常会持续5s ~ 1min 就恢复了，这个不是App自身的问题 @ckjbug

**Comment by jkpang** [comment]
#222
