### ISSUE TITLE
v1.8.3(83) - 希望能加快markdown的渲染速度

### ISSUE THREAD

**Issue by Arbusz** [PPHubApp/PPHub-Feedback#227]
运行环境: iPhone 8 - iOS12.1.4 - v1.8.3(83)

**Comment by jkpang** [comment]
Readme的加载速度与网络情况有关，国内网络环境下访问GitHub速度较慢。建议使用移动宽带或者开启梯子工具，可以快速加载Readme内容 @Arbusz
