### ISSUE TITLE
v1.8.4(92) - 1排行榜增加点星，快速关注功能。2项目关...

### ISSUE THREAD

**Issue by hdzyxx** [PPHubApp/PPHub-Feedback#229]
1排行榜增加点星，快速关注功能。2项目关注可选release通知模式

运行环境: iPhone 7 Plus - iOS12.1.4 - v1.8.4(92)

**Comment by jkpang** [comment]
> 1排行榜增加点星，快速关注功能。2项目关注可选release通知模式

@hdzyxx 您好：
1. 可点击右下角的“三个点”按钮，弹出的菜单有快速Star/Unstar选项
2. GitHub开放的API中没有给出“可选release通知模式”接口，客户端这边无法实现此功能，希望您能理解
