### ISSUE TITLE
v1.8.4(92) - 为什么看自己仓库的里的代码时，总显示没有...

### ISSUE THREAD

**Issue by mzjlswatt** [PPHubApp/PPHub-Feedback#230]
为什么看自己仓库的里的代码时，总显示没有请求到数据

运行环境: iPhone X - iOS12.1.4 - v1.8.4(92)

**Comment by jkpang** [comment]
您好，是文件编码问题。iOS和macOS的文件编码是UTF-8，如果是其它平台的IDE代码文件，可能造成一部分文件转码失败的情况，目前还没有找到完美的解决方案。
其他用户遇到的同样的问题：  #223 #212 
目前可以点击左上角的“分享”按钮，选择“打开网页”查看，感谢您的反馈！  @mzjlswatt

**Comment by mzjlswatt** [comment]
了解，期待后期改善

发自我的 iPhone

**Comment by jkpang** [comment]
v1.8.5已优化了转码失败文件的查看方式，快去更新吧！
