### ISSUE TITLE
v1.8.4(92) - 请问代码可以设置不换行吗，不然阅读起来有...

### ISSUE THREAD

**Issue by abcanqi** [PPHubApp/PPHub-Feedback#231]
请问代码可以设置不换行吗，不然阅读起来有些乱

运行环境: iPhone 7 Plus - iOS12.1.3 - v1.8.4(92)

**Comment by jkpang** [comment]
您好，这个Feature目前还不好实现。其实在PPHub的早期版本的代码显示是不折行的（因为是使用WebView加载的，没有更换代码主题色功能）。但后来有用户提出需要代码折行的需求： #75 #76 ，所以之后的代码显示修改成现阶段的可折行的版本。
不过您可以点击右上角的 分享-->打开网页，就可以查看网页版本的非折行版本了（详细步骤可查看 #155 ） 或者 横置手机，以获得更宽的代码显示控件
@abcanqi
