### ISSUE TITLE
v1.8.4(92) - 无法查看 private 项目的更新次数...

### ISSUE THREAD

**Issue by iWECon** [PPHubApp/PPHub-Feedback#233]
无法查看 private 项目的更新次数（在 profits 里面不显示）

Environment: iPhone X - iOS12.1.2 - v1.8.4(92)

**Comment by jkpang** [comment]
您好，这种情况可能由以下几种原因造成：
- 代码未提交至master分支
- GitHub网页未设置私有仓库提交数量对外可见

设置方法可以查看这个issue：#220   @iWECon

**Comment by iWECon** [comment]
ok, 三克油~
