### ISSUE TITLE
v1.8.4（92） - iPhone6iOS10登录后无法点击授权

### ISSUE THREAD

**Issue by saizax123** [PPHubApp/PPHub-Feedback#235]
iPhone6iOS10登录后无法点击授权，请问怎么办？

**Comment by saizax123** [comment]
为什么登陆之后点哪里都没有效果，是不是不支持iOS10了？

运行环境: iPhone 6 - iOS10.3.3 - v1.8.4(92)

**Comment by jkpang** [comment]
Hello，目前GitHub官方的授权网页已不支持iOS11以下系统的浏览器进行**第一次**授权登录操作了，会提示Safari版本过低（2018年10月份前都没问题的）。。。
您这边可以使用PC端的浏览器点击以下链接来进行首次的授权，以后在iOS10的设备上就可以登录了
仅公开库：https://github.com/login/oauth/authorize?client_id=5d79469d95f67fe366c9&scope=user,public_repo,notifications
公开库 + 私有库：https://github.com/login/oauth/authorize?client_id=5d79469d95f67fe366c9&scope=user,repo,notifications

@saizax123

**Comment by saizax123** [comment]
谢谢，我用iPad也可以首次授权了的。
