### ISSUE TITLE
v1.8.4(92) - 你好，为啥我在github上的cpp文件...

### ISSUE THREAD

**Issue by CongWh** [PPHubApp/PPHub-Feedback#238]
你好，为啥我在github上的cpp文件都打不开呀？

运行环境: iPhone 6s - iOS12.1.4 - v1.8.4(92)

**Comment by jkpang** [comment]
> 你好，为啥我在github上的cpp文件都打不开呀？

您好，iOS/macOS的文本编码是UTF-8，很有可能是您使用IDE编辑过的文件转码成UTF-8文本时失败造成的。目前我还在继续寻找解决方案。
您可以点击右上角的分享按钮，然后打开网页查看此代码，感谢反馈 @CongWh

**Comment by jkpang** [comment]
您也可以点击仓库详情右下角菜单按钮，选择Working Copy App打开，可以以更专业的方式查看代码

**Comment by jkpang** [comment]
v1.8.5已优化了转码失败文件的查看方式，快去更新吧！
