### ISSUE TITLE
v1.8.4(92) - 希望可以添加一个翻译的功能

### ISSUE THREAD

**Issue by bbbydz** [PPHubApp/PPHub-Feedback#239]
运行环境: iPad 2018 - iOS12.0.1 - v1.8.4(92)

**Comment by jkpang** [comment]
您好，可以使用iOS自带的词典查询单词，选中一个词语，在弹出的菜单中选择“查询”按钮即可 @bbbydz

**Comment by bbbydz** [comment]
那个自带的只能搜索单个单词,我指的类似于谷歌翻译网页的插件,尝试调用谷歌翻译的API添加一下这个小功能呗, 小建议而已

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: jkpang <notifications@github.com>
发送时间: Monday, March 11, 2019 3:23:17 PM
收件人: PPHubApp/PPHub-Feedback
抄送: bbbydz; Mention
主题: Re: [PPHubApp/PPHub-Feedback] v1.8.4(92) - 希望可以添加一个翻译的功能 (#239)


您好，可以使用iOS自带的词典查询单词，选中一个词语，在弹出的菜单中选择“查询”按钮即可 @bbbydz<https://github.com/bbbydz>

―

**Comment by jkpang** [comment]
2.2.0已添加“翻译”功能，选中的文本跳转至谷歌翻译，快去更新吧！ @bbbydz
