### ISSUE TITLE
v1.8.4(92) - 如何可以增加wiki的支持，那就真的太好...

### ISSUE THREAD

**Issue by LYJSPEEDX** [PPHubApp/PPHub-Feedback#240]
如何可以增加wiki的支持，那就真的太好了

运行环境: iPhone 7 - iOS12.1.2 - v1.8.4(92)

**Comment by jkpang** [comment]
> 如何可以增加wiki的支持，那就真的太好了

您好，是支持查看wiki的，仓库详情页点击右下角菜单弹窗，左滑至第二页，即可以看见wiki按钮

**Comment by jkpang** [comment]
v1.8.5已将Wiki入口放在了菜单栏第一个，快去更新吧！
