### ISSUE TITLE
希望可以把仓库 clone 下来编辑

### ISSUE THREAD

**Issue by peterzililuo** [PPHubApp/PPHub-Feedback#241]
外出的时候习惯带 iPad Pro 出去因为 MacBook Pro 真的太重了。缺点是我一直找不到好的工具让我在 iPad Pro 上写代码，所以我希望 PPHub 某一天可以把仓库 Clone 下来编辑。

**Comment by jkpang** [comment]
Hi，PPHub的定位并不是一个专业的GitHub代码编辑器，而是作为GitHub的辅助工具来帮助开发者更加方便的发现仓库与开发者。
推荐您使用专业的编辑器Working Copy来Clone、编辑代码，在PPHub内已经可以一键直达Working Copy进行Clone操作：仓库详情-右下角菜单按钮-Working Copy @peterzililuo
