### ISSUE TITLE
v1.8.4(92) - 强烈希望加入一个按照显示的格式的打印功能...

### ISSUE THREAD

**Issue by MEIXuYan** [PPHubApp/PPHub-Feedback#242]
强烈希望加入一个按照显示的格式的打印功能，方便在notability里面查看标准代码。现在只能通过网页格式转pdf，谢谢🙏

运行环境: iPad 2018 - iOS12.1.4 - v1.8.4(92)

**Comment by jkpang** [comment]
你好，我不是太明白 ”按照显示的格式的打印功能“

**Comment by MEIXuYan** [comment]
就是python在app里面各种颜色pattern，打印都是黑白------------------ 原始邮件 ------------------
发件人: "jkpang"<notifications@github.com>
发送时间: 2019年8月30日(星期五) 下午5:00
收件人: "PPHubApp/PPHub-Feedback"<PPHub-Feedback@noreply.github.com>;
抄送: "USTB_XuYan"<2801500185@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [PPHubApp/PPHub-Feedback] v1.8.4(92) - 强烈希望加入一个按照显示的格式的打印功能... (#242)



你好，我不是太明白 ”按照显示的格式的打印功能“
 
&mdash;
