### ISSUE TITLE
v1.8.4(92) - 大佬有准备弄上暗黑主题me，工具暗黑主题...

### ISSUE THREAD

**Issue by chriman** [PPHubApp/PPHub-Feedback#247]
大佬有准备弄上暗黑主题me，工具暗黑主题用习惯了

Environment: iPhone 7 - iOS12.1.4 - v1.8.4(92)

**Comment by jkpang** [comment]
嗯嗯，我会在以后的版本考虑加入。但是因为我业余的时间有限，可能没有那么快哈 @chriman

**Comment by jkpang** [comment]
你好，v2.0.0版本增加黑暗模式，快去更新吧！  @chriman
