### ISSUE TITLE
UI Bug.

### ISSUE THREAD

**Issue by nlnlnull** [PPHubApp/PPHub-Feedback#248]
机型: iPhone XS Max
系统版本: 12.1.4
PPHub 版本: 1.8.5(95) 

Profile Tab 页，点击右上角进入 hacknical，然后关闭，再随便 push 一个新页面，TabBar 会错位。

**Comment by jkpang** [comment]
您好，我刚刚用iPhone XS Max的模拟器测试了一下，TabBar的高度会短暂变矮，你说的是这种情况吗？
我测试了其他一些机型的模拟器，发现这种情况只会出现在刘海屏的机型上。
目前还不知道原因，因为TabBar都是用的系统自带的控件，初步猜测是iOS12.1.4系统的原因，我会持续关注这个问题，感谢您的反馈 @nlnlnull

**Comment by nlnlnull** [comment]
是这种情况。

jkpang <notifications@github.com>于2019年3月16日 周六13:05写道：

**Comment by jkpang** [comment]
现在升级iOS12.2后应该没有这个问题了吧？

**Comment by nlnlnull** [comment]
很遗憾，还是存在。

**Comment by jkpang** [comment]
这个是系统问题，暂时无解了。但不影响正常使用，那就先关闭这个issues，希望苹果后面能Fix这个问题
