### ISSUE TITLE
v1.8.5(95) - 绿格子显示有问题，当点击倒数第二列的绿格...

### ISSUE THREAD

**Issue by bo233** [PPHubApp/PPHub-Feedback#251]
绿格子显示有问题，当点击倒数第二列的绿格子时，气泡的尖尖处会对准最后一列的格子

运行环境: iPhone X - iOS12.1.3 - v1.8.5(95)

**Comment by jkpang** [comment]
嗯嗯，可能系统弹窗的方式导致计算UI控件边缘Frame有偏差，我会尝试优化这个问题，感谢反馈！ @bo233
