### ISSUE TITLE
v1.8.5(95) - 版本更新后，打开github中的cpp文...

### ISSUE THREAD

**Issue by CongWh** [PPHubApp/PPHub-Feedback#252]
版本更新后，打开github中的cpp文件显示“文件转码UTF-8失败”。本人使用DEV-C++编译器，本地上传github

运行环境: iPhone 6s - iOS12.1.4 - v1.8.5(95)

**Comment by jkpang** [comment]
您好，是因为GitHub上的原始文本转码至iOS系统的UTF-8格式失败造成的。弹窗的目的特意是提示用户遇到这类情况时，选择网页的方式继续查看。 @CongWh
