### ISSUE TITLE
v1.8.5(95) - 图片太小看不清，无法放大。点击之后跳转页...

### ISSUE THREAD

**Issue by hy2013** [PPHubApp/PPHub-Feedback#253]
图片太小看不清，无法放大。点击之后跳转页面提示：
This file is too big to show. Sorry!
也就是无论如何也看不清

运行环境: iPhone 7 - iOS12.2 - v1.8.5(95)

**Comment by jkpang** [comment]
您好，因为查看的图片太大了，导致无法显示。我会在以后的版本尝试优化这个问题 @hy2013

**Comment by jkpang** [comment]
最新版已优化这个问题，快去更新吧！
