### ISSUE TITLE
v1.8.5(95) - 你好，请问github收到issue提问...

### ISSUE THREAD

**Issue by howie6879** [PPHubApp/PPHub-Feedback#254]
你好，请问github收到issue提问回复没有通知吗

运行环境: iPhone 8 - iOS12.1.4 - v1.8.5(95)

**Comment by jkpang** [comment]
> 你好，请问github收到issue提问回复没有通知吗

您好，因为官方没有开放相关事件的推送接口 + 没有自己的服务器，所以就做不了推送了 @howie6879
