### ISSUE TITLE
v1.8.5(95) - .ipynb文件无法打开，而且希望可以d...

### ISSUE THREAD

**Issue by GRP2019** [PPHubApp/PPHub-Feedback#255]
.ipynb文件无法打开，而且希望可以download到本地进行阅读

运行环境: iPad Pro 12.9 Inch 3 - iOS12.1.4 - v1.8.5(95)

**Comment by jkpang** [comment]
如果要clone仓库，可以点击菜单栏的Working Copy按钮，关于查看.ipynb文件的问题可以看issue #225 #183 @GRP2019

**Comment by jkpang** [comment]
你好，v1.9.0已审核通过，现在已可以查看.ipynb文件 @GRP2019
