### ISSUE TITLE
v1.8.5(95) - How to view commits ...

### ISSUE THREAD

**Issue by njzjz** [PPHubApp/PPHub-Feedback#256]
How to view commits of a repository?

运行环境: iPhone X - iOS12.2 - v1.8.5(95)

**Comment by CL-Jeremy** [comment]
![IMG_8710](https://user-images.githubusercontent.com/1714243/54890733-f565b100-4eaa-11e9-9edb-caff2b948977.PNG)
![IMG_8709](https://user-images.githubusercontent.com/1714243/54890735-f860a180-4eaa-11e9-8610-a83371d91064.PNG)

**Comment by njzjz** [comment]
Thank you.
