### ISSUE TITLE
v1.8.5(95) - How to edit the titl...

### ISSUE THREAD

**Issue by njzjz** [PPHubApp/PPHub-Feedback#257]
How to edit the title of an issue?

运行环境: iPhone X - iOS12.2 - v1.8.5(95)

**Comment by jkpang** [comment]
![image](https://user-images.githubusercontent.com/17583451/54892718-983f1f00-4eed-11e9-8010-29f2736e5fb4.png)
@njzjz

**Comment by njzjz** [comment]
这里只能编辑内容，而不是标题…… @jkpang

**Comment by jkpang** [comment]
> 这里只能编辑内容，而不是标题…… @jkpang

你好，那手机端就不能编辑标题了，可以在iPad端或PC网页上编辑。

**Comment by njzjz** [comment]
OK. Thank you.
