### ISSUE TITLE
v1.8.5(95) - 似乎代码树只能树形展开，碰到大量文件/目...

### ISSUE THREAD

**Issue by CL-Jeremy** [PPHubApp/PPHub-Feedback#259]
似乎代码树只能树形展开，碰到大量文件/目录的情况可能不是很方便。现在用着还可以，还算顺手。配色太丰富了，点赞👍

Environment: iPhone SE - iOS10.3.3 - v1.8.5(95)

**Comment by jkpang** [comment]
哈，感谢支持！PPHub的定位并不是专业的浏览Git文件，如果碰到大量文件用着不习惯的情况，可以点击仓库右下角菜单按钮，在菜单栏第二页选择Working Copy打开，即可享受在手机上专业Review代码的体验😁 @CL-Jeremy
