### ISSUE TITLE
v1.8.5(95) - 是否可以支持ipad两侧使用，我可以边看...

### ISSUE THREAD

**Issue by hanwenbo** [PPHubApp/PPHub-Feedback#262]
是否可以支持ipad两侧使用，我可以边看这个app，边用workcopy来看代码，workcopy 克隆下来查看很快，我用pphub主要是当新闻站一样在使用

运行环境: iPad Pro 12.9 Inch 3 - iOS12.1.1 - v1.8.5(95)

**Comment by jkpang** [comment]
你好，现在2.0.0版本支持iPad多任务分屏了，快去更新哟 @hanwenbo
