### ISSUE TITLE
v1.8.5(95) - 为什么一到晚上就访问不了

### ISSUE THREAD

**Issue by qiuzefan** [PPHubApp/PPHub-Feedback#263]
运行环境: iPhone XR - iOS12.0 - v1.8.5(95)

**Comment by jkpang** [comment]
你好，是否您这边白天和晚上的网络运营商不一样？或者两者环境的网络信号不一样？PPHub请求的都是GitHub官方Api，没有做过特殊处理(因为GitHub在国内受到了DNS污染，这是造成访问慢的主要原因。如果有条件，建议使用小火箭开启vpn代理访问，速度会快很多) @qiuzefan

**Comment by qiuzefan** [comment]
那ios没有ssr 啊 可不可以推荐一个

发自我的 iPhone

**Comment by jkpang** [comment]
> 那ios没有ssr 啊 可不可以推荐一个

我目前用的shadowrocket，但是国区已下架，其他的工具我就不清楚了，对这类型的工具了解的比较少 @qiuzefan
