### ISSUE TITLE
v1.8.5(95) - 搞不懂 在右上角弄个一直loading的...

### ISSUE THREAD

**Issue by hanwenbo** [PPHubApp/PPHub-Feedback#264]
搞不懂 在右上角弄个一直loading的按钮干嘛。进去就是个条形码 一直等着？

运行环境: iPhone X - iOS12.1.4 - v1.8.5(95)

**Comment by jkpang** [comment]
你好，请问是哪个界面右上角的Loading按钮？还有条形码是什么东西？ @hanwenbo

**Comment by hanwenbo** [comment]
您好 ，个人中心的右上角，有个花的圈状按钮，点进去很卡，然后一直等待也没见出来什么，就是一个条形码，一直等待生成什么 ![img](https://ws3.sinaimg.cn/large/006tKfTcly1g1mbg2cx6nj30u01szwng.jpg)

**Comment by hanwenbo** [comment]
个人中心右上角 ，一直就这样等着 没任何出现

**Comment by jkpang** [comment]
哦哦，这个是一个开源前端项目，作者是用来帮助用户利用的GitHub数据生成简历，方便找工作，我觉得对开发者挺实用，就加了个入口。那个条形码只是一个Loading动画，表示那边的服务器正在给你分析数据
这是该项目的链接：https://github.com/ecmadao/hacknical

**Comment by hanwenbo** [comment]
哦  不过这个很卡 你得想办法处理下，不然大家都会以为是坏了，它至少等待大于1-2分钟

**Comment by jkpang** [comment]
> 哦 不过这个很卡 你得想办法处理下，不然大家都会以为是坏了，它至少等待大于1-2分钟

这个我就处理不了了，因为我不是作者，我这边只是加载了一个网页😂😂😂 @hanwenbo

**Comment by hanwenbo** [comment]
@jkpang 也可以优化  比如微信的文章 他可以浮动在最上层 ，用户可以挂起来 干点其他的去，当然这个有点小题大做，作为用户这个loading确实会影响你的app体验哦~ 它忒慢了 至今未打开过

**Comment by jkpang** [comment]
> @jkpang 也可以优化 比如微信的文章 他可以浮动在最上层 ，用户可以挂起来 干点其他的去，当然这个有点小题大做，作为用户这个loading确实会影响你的app体验哦~ 它忒慢了 至今未打开过

这个数据分析处理是在服务端进行的，用户不用一直开着网页等待加载完成，如果那边的服务器处理好了，下次再进去就行。
