### ISSUE TITLE
v1.8.6(100) - 可以增加markdown数学公式late...

### ISSUE THREAD

**Issue by leechor** [PPHubApp/PPHub-Feedback#267]
可以增加markdown数学公式latex显示功能吗？

运行环境: iPad Pro 10.5 Inch - iOS12.1.4 - v1.8.6(100)

**Comment by jkpang** [comment]
你好，目前Markdown使用的是GitHub官方的标准，如果官方不支持，可能暂时就没办法了 @leechor
