### ISSUE TITLE
v1.8.6(100) - 经常提示没有请求到数据是什么原因

### ISSUE THREAD

**Issue by 1Shaun** [PPHubApp/PPHub-Feedback#270]
运行环境: iPhone 7 - iOS12.2 - v1.8.6(100)

**Comment by jkpang** [comment]
您好，
- 如果是Trending列表，说明此时的官方数据为空；
- 如果是News列表，说明您的账号没有Follow用户或Watch仓库或它们根本没有活动；
- 如果是其它列表，说明是您访问这个列表没有数据
- 如果是访问文件，说明此文件内容为空或者解码成UTF-8失败
