### ISSUE TITLE
v1.8.6(100) - 首页小组件统计的小绿格有时候是错的

### ISSUE THREAD

**Issue by winstonwxj** [PPHubApp/PPHub-Feedback#272]
运行环境: iPhone 7 - iOS12.2 - v1.8.6(100)

**Comment by jkpang** [comment]
您好，在GitHub官网的用户界面，打开私有仓库Commit数量对外可见就可以了（同issues #171），如下图 ![](https://user-images.githubusercontent.com/23581749/49558618-a66d2d80-f946-11e8-8c36-ebbbc81fa2e0.png)
 @winstonwxj

**Comment by winstonwxj** [comment]
嗯，解决了
