### ISSUE TITLE
v1.8.7(101) - 能不能支持下推送，比如某些库的relea...

### ISSUE THREAD

**Issue by bashen1** [PPHubApp/PPHub-Feedback#276]
能不能支持下推送，比如某些库的release版本或者issues动态

运行环境: iPhone 7 - iOS12.2 - v1.8.7(101)

**Comment by jkpang** [comment]
您好，因为官方没有开放相关事件的推送接口 + 没有自己的服务器，所以目前不支持推送哈 @bashen1
