### ISSUE TITLE
v1.8.7(101) - 没有 README.md 时应该不显示 ...

### ISSUE THREAD

**Issue by Linger2** [PPHubApp/PPHub-Feedback#277]
没有 README.md 时应该不显示 readme，而不是显示404

運行環境: iPhone 8 - iOS12.2 - v1.8.7(101)

**Comment by jkpang** [comment]
你好，下个版本将改进这个问题，感谢反馈！ @Linger2

**Comment by jkpang** [comment]
您好，1.8.9版本已优化了此问题，快去更新吧！ @Linger2

**Comment by Linger2** [comment]
好的谢谢！
