### ISSUE TITLE
v1.8.8(103) - 更新后，GitHub私有仓库和共享仓库打...

### ISSUE THREAD

**Issue by MenJacks** [PPHubApp/PPHub-Feedback#279]
更新后，GitHub私有仓库和共享仓库打开readme时，提示404 not found。更新前是可以的。

运行环境: iPad 2017 - iOS12.2 - v1.8.8(103)

**Comment by jkpang** [comment]
好的，已知悉，我会尽快解决这个问题，感谢反馈 @MenJacks

**Comment by jkpang** [comment]
您好，1.8.9版本已修复此问题，快去更新吧！
