### ISSUE TITLE
v1.8.8(103) - news 无法浏览 有梯子

### ISSUE THREAD

**Issue by MRNath** [PPHubApp/PPHub-Feedback#281]
运行环境: iPhone 8 - iOS12.2 - v1.8.8(103)

**Comment by jkpang** [comment]
如果提示“没有请求到数据”，可能是因为您的GitHub账号：

- 没有Follow任何用户或您Follow的用户没有相关动态
- 没有Watch任何代码库或您Watch的代码库没有相关动态
- 其他用户没有对您的公开代码库提出Issues或者Pull request


@MRNath
