### ISSUE TITLE
v1.8.8(103) - 点击 Issues 页面右上角的“+”应...

### ISSUE THREAD

**Issue by Teemwu** [PPHubApp/PPHub-Feedback#282]
点击 Issues 页面右上角的“+”应用自动退出

运行环境: iPad Pro 11 Inch - iOS12.2 - v1.8.8(103)

**Comment by jkpang** [comment]
已知悉，我会尽快修复这个问题，感谢反馈 @Teemwu

**Comment by jkpang** [comment]
1.8.9已修复此问题，快去更新吧！ @Teemwu
