### ISSUE TITLE
v1.8.8(103) - issue页面点击“+”按钮导致崩溃

### ISSUE THREAD

**Issue by hujianhang2996** [PPHubApp/PPHub-Feedback#283]
运行环境: iPhone X - iOS12.2 - v1.8.8(103)

**Comment by jkpang** [comment]
目前问题已解决，我会尽快发布新版本，感谢反馈！ˆ😊ˆ @hujianhang2996

**Comment by jkpang** [comment]
1.8.9已修复此问题，快去更新吧！ @hujianhang2996
