### ISSUE TITLE
v1.8.9(105) - News怎么没显示内容

### ISSUE THREAD

**Issue by Godisbilly** [PPHubApp/PPHub-Feedback#285]
运行环境: iPhone XS - iOS12.3 - v1.8.9(105)

**Comment by jkpang** [comment]
您好，如果提示“没有请求到数据”，可能是因为您的GitHub账号：

- 没有Follow任何用户或您Follow的用户没有相关动态
- 没有Watch任何代码库或您Watch的代码库没有相关动态
- 其他用户没有对您的公开代码库提出Issues或者Pull request

 @Godisbilly
