### ISSUE TITLE
v1.8.9(105) - 取消关注一个用户后，这个用户的动态还会出...

### ISSUE THREAD

**Issue by cat-walk** [PPHubApp/PPHub-Feedback#287]
取消关注一个用户后，这个用户的动态还会出现在最近动态里，刷新、清除缓存也没有帮助。

运行环境: iPhone 6s Plus - iOS12.2 - v1.8.9(105)

**Comment by jkpang** [comment]
你好，你这边有没有对该用户下面的仓库进行Watch操作呢？ @cat-walk

**Comment by cat-walk** [comment]
你好，没有的

jkpang <notifications@github.com> 于2019年4月26日周五 下午4:10写道：

**Comment by cat-walk** [comment]
好的，了解了。蟹蟹~


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: jkpang <notifications@github.com>
发送时间: 2019年5月8日 20:47
收件人: PPHubApp/PPHub-Feedback <PPHub-Feedback@noreply.github.com>
抄送: 杨培阳 <yangpy@foxmail.com>, Mention <mention@noreply.github.com>
主题: 回复：[PPHubApp/PPHub-Feedback] v1.8.9(105) - 取消关注一个用户后，这个用户的动态还会出... (#287)




我明白了，你的意思是：“取关用户后，此用户的历史动态还在列表中”
 目前是这样子的，取关用户后，GitHub的Api还是会给我返回之前的历史动态，但此用户未来的动态是不会出现了的 @cat-walk
