### ISSUE TITLE
v1.8.9(105) - 联系可以保留上次选择的分支，另外代码主题...

### ISSUE THREAD

**Issue by qiubinbin** [PPHubApp/PPHub-Feedback#288]
联系可以保留上次选择的分支，另外代码主题选择有点卡顿，

运行环境: iPhone 6s Plus - iOS12.2 - v1.8.9(105)

**Comment by jkpang** [comment]
你好，GitHub仓库众多，在本地维护上次选的仓库分支不是很理想。
