### ISSUE TITLE
v1.8.9(105) - 为啥我的新闻是空的？

### ISSUE THREAD

**Issue by qiubinbin** [PPHubApp/PPHub-Feedback#289]
运行环境: iPhone 6s Plus - iOS12.2 - v1.8.9(105)

**Comment by jkpang** [comment]
您好，如果提示“没有请求到数据”，可能是因为您的GitHub账号：

- 没有Follow任何用户或您Follow的用户没有相关动态
- 没有Watch任何代码库或您Watch的代码库没有相关动态
- 其他用户没有对您的公开代码库提出Issues或者Pull request

**Comment by qiubinbin** [comment]
收到。谢谢------------------ 原始邮件 ------------------发件人: jkpang  <notifications@github.com>发送时间: 2019年4月28日 08:19收件人: PPHubApp/PPHub-Feedback <PPHub-Feedback@noreply.github.com>抄送: qiubinbin <qiubin780061109@163.com>, Author <author@noreply.github.com>主题: 回复：[PPHubApp/PPHub-Feedback] v1.8.9(105) - 为啥我的新闻是空的？ (#289)您好，如果提示“没有请求到数据”，可能是因为您的GitHub账号：

没有Follow任何用户或您Follow的用户没有相关动态
没有Watch任何代码库或您Watch的代码库没有相关动态
其他用户没有对您的公开代码库提出Issues或者Pull request


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/PPHubApp/PPHub-Feedback","title":"PPHubApp/PPHub-Feedback","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/PPHubApp/PPHub-Feedback"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jkpang in #289: 您好，如果提示“没有请求到数据”，可能是因为您的GitHub账号：\r\n\r\n- 没有Follow任何用户或您Follow的用户没有相关动态\r\n- 没有Watch任何代码库或您Watch的代码库没有相关动态\r\n- 其他用户没有对您的公开代码库提出Issues或者Pull request"}],"action":{"name":"View Issue","url":"https://github.com/PPHubApp/PPHub-Feedback/issues/289#issuecomment-487329539"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/PPHubApp/PPHub-Feedback/issues/289#issuecomment-487329539",
"url": "https://github.com/PPHubApp/PPHub-Feedback/issues/289#issuecomment-487329539",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
