### ISSUE TITLE
v1.8.9(105) - trending无法请求到数据

### ISSUE THREAD

**Issue by Pearson-Zhang** [PPHubApp/PPHub-Feedback#292]
运行环境: iPad11,1 - iOS12.2 - v1.8.9(105)

**Comment by jkpang** [comment]
您好，这是因为GitHub Trending 官方偶尔间歇性的无数据造成的。我遇到过好几次，通常会持续5s ~ 1min 就恢复了 @Pearson-Zhang 
相同问题 #226

**Comment by Pearson-Zhang** [comment]
了解了，感谢回复。软件不错，加油！

**Comment by jkpang** [comment]
> 了解了，感谢回复。软件不错，加油！

感谢感谢😊
