### ISSUE TITLE
v1.8.9(105) - 无法识别GitHub apps链接
例如...

### ISSUE THREAD

**Issue by njzjz** [PPHubApp/PPHub-Feedback#294]
无法识别GitHub apps链接
例如https://github.com/apps/renovate ，会以为这是一个repo

运行环境: iPhone X - iOS12.3 - v1.8.9(105)

**Comment by jkpang** [comment]
您好，是这样子的，PPHub会把此类链接识别成**apps/renovate**仓库。在识别的过程中无法知晓**apps**、**renovate**是否为GitHub中的一个有效的User/Org、Repo @njzjz

**Comment by njzjz** [comment]
能否给apps、marketplace这类特殊链接添加例外规则？
