### ISSUE TITLE
v1.8.9(105) - 查看.cpp 文件时会显示文本转为utf...

### ISSUE THREAD

**Issue by a74731248** [PPHubApp/PPHub-Feedback#295]
查看.cpp 文件时会显示文本转为utf -8编码失败，只能点打开网页才能查看

运行环境: iPhone 7 - iOS12.1.3 - v1.8.9(105)

**Comment by jkpang** [comment]
是的，此.cpp文件转换成UTF-8编码文本失败 @a74731248
