### ISSUE TITLE
v1.8.9(105) - 从 safari 用 openner 打...

### ISSUE THREAD

**Issue by kid1412621** [PPHubApp/PPHub-Feedback#296]
从 safari 用 openner 打开又不能跳转具体页面了

Environment: iPhone 6s - iOS12.2 - v1.8.9(105)

**Comment by kid1412621** [comment]
查看文档的时候能不能（在往下滑动时）把状态栏或导航栏隐藏掉？这样浏览区域大些，上滑再显示，像底部工具栏那样

**Comment by jkpang** [comment]
> 从 safari 用 openner 打开又不能跳转具体页面了

v1.9.0已发布，已修复此问题

**Comment by jkpang** [comment]
> 查看文档的时候能不能（在往下滑动时）把状态栏或导航栏隐藏掉？这样浏览区域大些，上滑再显示，像底部工具栏那样

这个Feature我会考虑，但不一定会上哈，感谢反馈！
