### ISSUE TITLE
v1.8.9(105) - 那个，就是如果README里面有那个可以...

### ISSUE THREAD

**Issue by iPixelOldC** [PPHubApp/PPHub-Feedback#297]
那个，就是如果README里面有那个可以折叠的内容，当你把折叠打开时，下面的内容就会消失（就是上划不动），但是关闭折叠，就又出现了.....所以是不是限制了高度啊

运行环境: iPhone 6 - iOS12.2 - v1.8.9(105)

**Comment by jkpang** [comment]
目前是有这样的问题，还在寻找解决方案 @iPixelOldC

**Comment by iPixelOldC** [comment]
啊，好的，谢谢


------------------ 原始邮件 ------------------
发件人: jkpang <notifications@github.com>
发送时间: 2019年5月9日 11:50
收件人: PPHubApp/PPHub-Feedback <PPHub-Feedback@noreply.github.com>
抄送: iPixelOldC <ipixeloldc@qq.com>, Mention <mention@noreply.github.com>
主题: 回复：[PPHubApp/PPHub-Feedback] v1.8.9(105) - 那个，就是如果README里面有那个可以... (#297)




目前是有这样的问题，还在寻找解决方案 @iPixelOldC
