### ISSUE TITLE
v1.8.9(105) - 首页提示没有数据

### ISSUE THREAD

**Issue by prayraincyh** [PPHubApp/PPHub-Feedback#298]
运行环境: iPhone 8 - iOS12.2 - v1.8.9(105)

**Comment by jkpang** [comment]
你好，这是因为GitHub Trending官网正在计算整合数据，所以导致空白，此状态会持续1~5min @prayraincyh

**Comment by prayraincyh** [comment]
原来如此 怪不得软件突然就好了，还以为软件不稳定
