### ISSUE TITLE
v1.8.9(105) - 能不能像知乎一样，退出之后再进入还是退出...

### ISSUE THREAD

**Issue by tanglianggithub** [PPHubApp/PPHub-Feedback#301]
能不能像知乎一样，退出之后再进入还是退出之前的页面呢？
切换应用后回来发现不是原来的页面，再进入很麻烦

运行环境: iPhone 8 - iOS12.0 - v1.8.9(105)

**Comment by jkpang** [comment]
这可能是你的设备开启了太多应用，切换应用后将PPHub进程kill掉了，我这边测试了反复多次切换应用，还是会在之前的页面的
