### ISSUE TITLE
v1.9.0.108 - 您好，请问考虑做一个 LeetCode ...

### ISSUE THREAD

**Issue by hologerry** [PPHubApp/PPHub-Feedback#303]
您好，请问考虑做一个 LeetCode 客户端吗？
目前有的客户端界面都好丑，感觉您做的这个 PPHub 界面好看，功能好用。希望能扩展到 LeetCode！
谢谢

Environment: iPhone X - iOS12.2 - v1.9.0.108

**Comment by jkpang** [comment]
如果LeetCode有开放的Api，我会考虑这个的哈！非常感谢你的建议！ @hologerry

**Comment by hologerry** [comment]
有 [leetcode-cl](https://github.com/skygragon/leetcode-cli) 可以参考一下😊

**Comment by jkpang** [comment]
Hi，最近发现已经有新的LeetCode客户端出现了，所以这个就暂时不考虑啦！
