### ISSUE TITLE
v1.9.0.108 - 请问一下，我这边已经不在关注项目动态，为...

### ISSUE THREAD

**Issue by yanxi252515237** [PPHubApp/PPHub-Feedback#304]
请问一下，我这边已经不在关注项目动态，为什么news里面还有之前的动态？

运行环境: iPhone 6s - iOS12.2 - v1.9.0.108

**Comment by jkpang** [comment]
你好，取关用户后，GitHub的Api还是会给我返回之前的历史动态，但此用户未来的动态是不会出现了的 @yanxi252515237
