### ISSUE TITLE
v1.9.0.108 - 打开README好慢，能否加上缓存之类的...

### ISSUE THREAD

**Issue by lsl233** [PPHubApp/PPHub-Feedback#307]
打开README好慢，能否加上缓存之类的东西

Environment: iPhone 8 - iOS12.2 - v1.9.0.108

**Comment by jkpang** [comment]
你好，README加载是有缓存的，加载慢的原因是因为解析GitHub的DNS在国内被污染了，所以会比较慢，亲测在网络质量良好的条件下，移动运营商的网络访问GitHub是最快的（有秒开的效果） @lsl233
