### ISSUE TITLE
v1.9.0.108 - 标题为url编码后的内容！全英文没问题。...

### ISSUE THREAD

**Issue by summerHearts** [PPHubApp/PPHub-Feedback#308]
标题为url编码后的内容！全英文没问题。有中文的不行！

运行环境: iPhone XS Max - iOS12.1 - v1.9.0.108

**Comment by jkpang** [comment]
你好，是查看仓库文件遇到的吗？能否贴出此仓库的链接？ @summerHearts

**Comment by summerHearts** [comment]
https://github.com/summerHearts/JavaArchitecture/blob/master/Concurrent/浅谈AtomicInteger实现原理.md

**Comment by jkpang** [comment]
OK，明白了，下个版本将优化这个小问题，感谢反馈！ @summerHearts

**Comment by jkpang** [comment]
嗨，最新v1.9.1已经优化了这个问题，快去更新吧 @summerHearts
