### ISSUE TITLE
v1.9.0.108 - 希望能够提供上传图片，帮助解决问题的功能...

### ISSUE THREAD

**Issue by summerHearts** [PPHubApp/PPHub-Feedback#309]
希望能够提供上传图片，帮助解决问题的功能！不然只有文字描述很难定位问题

运行环境: iPhone XS Max - iOS12.1 - v1.9.0.108

**Comment by jkpang** [comment]
你好，因为GitHub没有开放issues接口上传图片的字段, 所以上传不了。不过你这边可以使用Markdown语法，贴上图片链接也能达到同样的效果 @summerHearts
