### ISSUE TITLE
v1.9.0.108 - Stargazers 列表应该把最新 s...

### ISSUE THREAD

**Issue by vincentlauvlwj** [PPHubApp/PPHub-Feedback#310]
Stargazers 列表应该把最新 star 的用户排在前面，这样才与网页版一致

运行环境: iPhone SE - iOS12.2 - v1.9.0.108

**Comment by jkpang** [comment]
你好，我也非常想这样做，但是GitHub开放出来的Api没有给排序的选项，目前只能这样 @vincentlauvlwj
