### ISSUE TITLE
v1.9.0.108 - 请问新版本是不支持查看私有仓库的提交数了...

### ISSUE THREAD

**Issue by Muyun99** [PPHubApp/PPHub-Feedback#315]
请问新版本是不支持查看私有仓库的提交数了吗

运行环境: iPhone 6s - iOS12.2 - v1.9.0.108

**Comment by jkpang** [comment]
你好，你说的是commits方格图吗？

**Comment by Muyun99** [comment]
嗯嗯是的，我在之前的某个版本可以看，最近看不了了(笑~

**Comment by jkpang** [comment]
> 嗯嗯是的，我在之前的某个版本可以看，最近看不了了(笑~

看看这个issues：https://github.com/PPHubApp/PPHub-Feedback/issues/220

**Comment by Muyun99** [comment]
> > 嗯嗯是的，我在之前的某个版本可以看，最近看不了了(笑~
> 
> 看看这个issues：#220

十分感谢您的回复，确实不知道还有这个解决方案哈哈

**Comment by jkpang** [comment]
> > > 嗯嗯是的，我在之前的某个版本可以看，最近看不了了(笑~
> > 
> > 
> > 看看这个issues：#220
> 
> 十分感谢您的回复，确实不知道还有这个解决方案哈哈

哈哈，客气啦
