### ISSUE TITLE
v1.9.1.109 - Github 现在可以查看一个项目use...

### ISSUE THREAD

**Issue by superbiger** [PPHubApp/PPHub-Feedback#317]
Github 现在可以查看一个项目useby 数量，希望支持

运行环境: iPad Pro 11 Inch - iOS12.3.1 - v1.9.1.109

**Comment by jkpang** [comment]
好的，我会考虑这个Feature，感谢反馈！

**Comment by jkpang** [comment]
你好，我查看了GitHub开放的Api，还没有关于use by的接口，这个Feature暂时无法实现了 @superbiger
