### ISSUE TITLE
不支持删除fork的项目吗？

### ISSUE THREAD

**Issue by yanghuanrong** [PPHubApp/PPHub-Feedback#318]
是否也是因为github没有开放对应的api呢？

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by jkpang** [comment]
嗯嗯，没有取消Fork的Api。但是有删除仓库的接口，但是考虑在移动端删除仓库太危险了，就没有添加这个功能。

**Comment by yanghuanrong** [comment]
好滴。谢谢
