### ISSUE TITLE
v1.9.1.109 - 那个jupyter 打不开ipynb后缀...

### ISSUE THREAD

**Issue by CodePlayercc** [PPHubApp/PPHub-Feedback#319]
那个jupyter 打不开ipynb后缀的代码啊 是个空白界面

运行环境: iPad 2018 - iOS12.2 - v1.9.1.109

**Comment by jkpang** [comment]
请问是哪个仓库？我刚刚试了好几个ipynb的文件都是可以打开的

**Comment by CodePlayercc** [comment]
打开后就是这个样子...用的本地仓库上传后 网页中能打开 软件中打开是空白页 从jupyter notebook中进去的
 
---原始邮件---
发件人: "jkpang"<notifications@github.com>
发送时间: 2019年6月1日(星期六) 晚上9:02
收件人: "PPHubApp/PPHub-Feedback"<PPHub-Feedback@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"CodePlayercc"<2569274643@qq.com>;
主题: Re: [PPHubApp/PPHub-Feedback] v1.9.1.109 - 那个jupyter 打不开ipynb后缀... (#319)



请问是哪个仓库？我刚刚试了好几个ipynb的文件都是可以打开的

**Comment by jkpang** [comment]
请问是私有仓库吗？如果是的话就没有访问权限，查看不了了

**Comment by CodePlayercc** [comment]
不好意思..应该是私有仓库


 
---原始邮件---
发件人: "jkpang"<notifications@github.com>
发送时间: 2019年6月1日(星期六) 晚上9:12
收件人: "PPHubApp/PPHub-Feedback"<PPHub-Feedback@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"CodePlayercc"<2569274643@qq.com>;
主题: Re: [PPHubApp/PPHub-Feedback] v1.9.1.109 - 那个jupyter 打不开ipynb后缀... (#319)



请问是私有仓库吗？如果是的话就没有访问权限，查看不了了

**Comment by jkpang** [comment]
嗯嗯，那就是私有库的问题了
