### ISSUE TITLE
v1.9.1.109 - 没有显示我的新organiation中的...

### ISSUE THREAD

**Issue by Ssiswent** [PPHubApp/PPHub-Feedback#324]
没有显示我的新organiation中的仓库…

运行环境: iPhone 8 - iOS12.0.1 - v1.9.1.109

**Comment by jkpang** [comment]
你好，组织里面的仓库是否显示在个人仓库列表中好像是要到网页中设置的。

**Comment by Ssiswent** [comment]
好的，谢谢~

jkpang <notifications@github.com>于2019年6月20日 周四下午12:37写道：
