### ISSUE TITLE
v1.9.1.109 - 今天排名刷不出来了

### ISSUE THREAD

**Issue by neversay4ever** [PPHubApp/PPHub-Feedback#325]
运行环境: iPhone XR - iOS12.3.1 - v1.9.1.109

**Comment by jkpang** [comment]
是的，因为昨天GitHub修改了Trending官网的数据，导致PPHub解析数据出错。我会在今天修复这个问题、提审，明天应该就可以更新啦 @neversay4ever

**Comment by jkpang** [comment]
1.9.2已修复此问题，快去更新吧
