### ISSUE TITLE
v1.9.1.109 - 电信4G 显示 没有请求到数据

### ISSUE THREAD

**Issue by Jasmine-Super** [PPHubApp/PPHub-Feedback#326]
运行环境: iPhone 6s - iOS10.3.2 - v1.9.1.109

**Comment by jkpang** [comment]
是的，因为昨天GitHub修改了Trending官网的数据，导致PPHub解析数据出错。我会在今天修复这个问题、提审，明天应该就可以更新啦

**Comment by Jasmine-Super** [comment]
谢谢，祝更好~

**Comment by jkpang** [comment]
1.9.2已修复此问题，快去更新吧
