### ISSUE TITLE
v1.9.1.109 - Developers 和news空白

### ISSUE THREAD

**Issue by mcdulldd** [PPHubApp/PPHub-Feedback#327]
运行环境: iPad11,1 - iOS12.3.1 - v1.9.1.109

**Comment by jkpang** [comment]
Hi：
Developers空白请看Issue：#325
news空白请看Issue：#305
@mcdulldd

**Comment by jkpang** [comment]
Trending空白问题已在1.9.2版本中修复。快去更新吧
