### ISSUE TITLE
v1.9.1.109 - "No request to data"...

### ISSUE THREAD

**Issue by wende** [PPHubApp/PPHub-Feedback#329]
"No request to data" for all queries :/

Environment: iPhone XS - iOS12.3.1 - v1.9.1.109

**Comment by jkpang** [comment]
Hi，Because GitHub Trending adjusted the data, the parsing failed. 1.9.2 has fixed this problem, go and update it. @wende

**Comment by jkpang** [comment]
v1.9.3 has been updated
