### ISSUE TITLE
v1.9.1.109 - 访问自己的repo没有问题，但是访问tr...

### ISSUE THREAD

**Issue by jdxyw** [PPHubApp/PPHub-Feedback#333]
访问自己的repo没有问题，但是访问trending一直显示 没有请求到数据 显示空白

运行环境: iPhone 8 - iOS12.0 - v1.9.1.109

**Comment by jkpang** [comment]
您好，这是因为GitHub Trending 调整数据，导致解析出错造成的，更新1.9.2版本就可以了，同issues #325  @jdxyw

**Comment by jkpang** [comment]
你好，v1.9.3已可更新，再次修复因Trending官网调整请求参数造成的问题。
