### ISSUE TITLE
v1.9.2.112 - 私人仓库访问失败 readme 还有 i...

### ISSUE THREAD

**Issue by ronething** [PPHubApp/PPHub-Feedback#334]
私人仓库访问失败 readme 还有 issue 都打不开

運行環境: iPhone 6 - iOS12.2 - v1.9.2.112

**Comment by jkpang** [comment]
你好，我刚刚测试了私有库时没有问题的。请问访问私有库失败是提示加载失败还是？是所有的issues都打不开吗？在确定网络良好的情况下可以重新登录试试

**Comment by ronething** [comment]
退出之后 再重新登陆就行了。
在没有退出重新登陆之前是这样，所有 issues 都打不开，然后代码部分文件可以打开，很神奇。

![image](https://user-images.githubusercontent.com/28869910/59489901-fc9ec880-8eb5-11e9-9582-17dd1d43e10c.png)

**Comment by jkpang** [comment]
可能是加载README与issues的WebView丢失了Cookie导致的，重新登录会重新生成Cookie。 @ronething
