### ISSUE TITLE
v1.9.2.112 - 不好意思我第一次用，为什么首页都什么都没...

### ISSUE THREAD

**Issue by nlpzy** [PPHubApp/PPHub-Feedback#335]
不好意思我第一次用，为什么首页都什么都没有显示没有请求到数据呐

运行环境: iPhone 7 - iOS12.3.1 - v1.9.2.112

**Comment by jkpang** [comment]
你好，是因为昨天GitHub调整了Trending总榜请求参数导致的，我会尽快修复这个问题，目前可以选择特定的编程语言查看榜单，感谢反馈！ @nlpzy

**Comment by jkpang** [comment]
你好，v1.9.3已可更新，修复了此问题。 @nlpzy
