### ISSUE TITLE
v1.9.2.112 - 无法获取trending reposit...

### ISSUE THREAD

**Issue by voilalz** [PPHubApp/PPHub-Feedback#336]
无法获取trending repository

运行环境: iPhone 7 - iOS12.3.1 - v1.9.2.112

**Comment by jkpang** [comment]
你好，是因为昨天GitHub调整了Trending总榜请求参数导致的，我已提交了新版本，明天应该就可以更新了，目前可以选择特定的编程语言查看榜单，感谢反馈！ @voilalz

**Comment by jkpang** [comment]
你好，v1.9.3已可更新，修复了此问题。
