### ISSUE TITLE
v1.9.3.113 - 1   希望增加黑暗模式
2   希望增...

### ISSUE THREAD

**Issue by liuyangzuo** [PPHubApp/PPHub-Feedback#338]
1   希望增加黑暗模式
2   希望增加查看release

运行环境: iPad Air 2 - iOS13.0 - v1.9.3.113

**Comment by jkpang** [comment]
你好，Dark mode在计划中；目前的版本是可以查看Release的，点击仓库详情右下角菜单按钮，左滑至第二页，即可点击Release按钮查看。
![image](https://user-images.githubusercontent.com/17583451/59973491-20a78b80-95d3-11e9-8692-d96c7ec23ab1.png)

**Comment by jkpang** [comment]
PPHub v2.0.0已可用
- 新增：Dark Mode（黑暗模式）；
- 新增：完美支持iPad多任务分屏模式；
- 优化：调整界面UI控件的排版、样式。

@liuyangzuo
