### ISSUE TITLE
Consider using GitHub v4 API - GraphQL version ?

### ISSUE THREAD

**Issue by Sorosliu1029** [PPHubApp/PPHub-Feedback#34]
GraphQL is next generation, and you could give a try, especially there are mature GraphQL client libraries for swift on GitHub, like [Apollo iOS](https://github.com/apollographql/apollo-ios) under MIT license.

**Comment by jkpang** [comment]
Thank you for your advice, and I'll consider using GraphQL API in a later version

**Comment by Desgard** [comment]
What are the advantages of `GraphQL` about a mini github client? I think the **PPHub** is fitter to the `RESTful` then `GraphQL`. 
You can refer to the article - [*GraphQL vs REST: Things to Consider*](https://www.infoq.com/news/2017/07/graphql-vs-rest)
