### ISSUE TITLE
v1.9.3.113 - Can’t load repo rank...

### ISSUE THREAD

**Issue by ixongju** [PPHubApp/PPHub-Feedback#340]
Can’t load repo ranking 

运行环境: iPhone 8 - iOS13.0 - v1.9.3.113

**Comment by jkpang** [comment]
Hello, did you choose the Objective-C classification? Currently GitHub Trending official website does not have Objective-C classified data.
@ixongju

**Comment by ixongju** [comment]
yeah, when I switch to Swift, I could get datas. thank~
