### ISSUE TITLE
v1.9.4.119 - 为什么开了VPN就网络错误？

### ISSUE THREAD

**Issue by DeppWang** [PPHubApp/PPHub-Feedback#341]
运行环境: iPhone XR - iOS12.2 - v1.9.4.119

**Comment by jkpang** [comment]
你好，可能是你使用的V*N软件的规则屏蔽了GitHub，或者你使用的节点已被封 @DeppWang

**Comment by DeppWang** [comment]
刚才可能节点被封，现在访问正常了



deppwang@163.com
 
发件人： jkpang
发送时间： 2019-07-04 09:42
收件人： PPHubApp/PPHub-Feedback
抄送： deppwang; Mention
主题： Re: [PPHubApp/PPHub-Feedback] v1.9.4.119 - 为什么开了VPN就网络错误？ (#341)
你好，可能是你使用的V*N软件的规则屏蔽了GitHub，或者你使用的节点已被封 @DeppWang

**Comment by jkpang** [comment]
OK
