### ISSUE TITLE
v1.9.4.119 - 无法看到我的贡献记录，就是一堆绿色小方格...

### ISSUE THREAD

**Issue by JansonC** [PPHubApp/PPHub-Feedback#342]
无法看到我的贡献记录，就是一堆绿色小方格那一栏

运行环境: iPhone 7 Plus - iOS12.3.1 - v1.9.4.119

**Comment by jkpang** [comment]
你好，解决方案可以这个issues：#220
 @JansonC

**Comment by JansonC** [comment]
谢谢，原来是私有仓库的问题 @jkpang

**Comment by jkpang** [comment]
还有如果分支的commits没有合并到默认分支也不会显示
