### ISSUE TITLE
希望能够优化iOS13 iPad上面低栏显示不全的问题

### ISSUE THREAD

**Issue by DrMerxer** [PPHubApp/PPHub-Feedback#343]
如题

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by jkpang** [comment]
你好，这个问题需要等iOS 13正式版出来才能解决了 @DrMerxer

**Comment by jkpang** [comment]
试试最新版本的PPHub，将我的iPad升级iOS13 Beta后再安装没有出现底栏显示不全的情况 @DrMerxer
