### ISSUE TITLE
v1.9.4.119 - Hi thanks for this m...

### ISSUE THREAD

**Issue by JustinLimYuSiang** [PPHubApp/PPHub-Feedback#347]
Hi thanks for this marvelous app, can I suggest a few improvements for you to consider, 1) the ability to save certain repos for offline viewing, 2) the ability to zoom in when viewing codes. Thank you!

Environment: iPad Mini 4 - iOS11.4.1 - v1.9.4.119

**Comment by jkpang** [comment]
Hello, thank you very much for your support of PPHub. I think the offline view code should be handed over to professional tools, but PPHub provides an entry point to "Working Copy." “Working Copy” is a professional code view and editor on iOS that provides offline download function, as shown below:    
![IMG_20F13DBF089E-1](https://user-images.githubusercontent.com/17583451/63840358-7faec580-c9b3-11e9-93d1-5373c80d7658.jpeg)
