### ISSUE TITLE
Repositories is Trending? Why are so different?

### ISSUE THREAD

**Issue by DeppWang** [PPHubApp/PPHub-Feedback#351]
![image](https://user-images.githubusercontent.com/21981221/61372333-6cdfa600-a8c9-11e9-8e64-9a76bdaed317.png)

![image](https://user-images.githubusercontent.com/21981221/61372427-aca68d80-a8c9-11e9-9a05-bd3388812d7e.png)

**Comment by jkpang** [comment]
Hello, this may be the reason GitHub official server has a cache, the data on the mobile browser is the same as the App.
![IMG_BA81E3ADD937-1](https://user-images.githubusercontent.com/17583451/61380287-aae5c580-a8db-11e9-9b40-c4742ce2c116.jpeg)
 @DeppWang

**Comment by DeppWang** [comment]
OK，I get it.
