### ISSUE TITLE
取消关注后 news里还有相关信息

### ISSUE THREAD

**Issue by Leemts** [PPHubApp/PPHub-Feedback#353]
取消关注某人后。news里还有他相关建库的动态

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by Leemts** [comment]
重装也不行

**Comment by jkpang** [comment]
> 取消关注某人后。news里还有他相关建库的动态

你好，是这样的。取消关注后，GitHub的Api还是会返回历史数据，但是以后的相关动态是不会返回的 @Leemts

**Comment by Leemts** [comment]
好的 @jkpang
