### ISSUE TITLE
v1.9.4.119 - 为zip格式 显示view raw 点击...

### ISSUE THREAD

**Issue by luozhb37** [PPHubApp/PPHub-Feedback#355]
为zip格式 显示view raw 点击后会白屏 有什么方法可以下载吗 

运行环境: iPhone XS - iOS12.3.1 - v1.9.4.119

**Comment by jkpang** [comment]
你好，PPHub不支持下载的。可以复制这个zip文件的原始地址到专业的下载软件下载 @luozhb37
