### ISSUE TITLE
v1.9.4.119 - 怎么不支持3D Touch 了？ 官方还...

### ISSUE THREAD

**Issue by lzr52o** [PPHubApp/PPHub-Feedback#356]
怎么不支持3D Touch 了？ 官方还没砍呢

运行环境: iPhone XS Max - iOS12.3.1 - v1.9.4.119

**Comment by jkpang** [comment]
你好，按App图标是支持3DTouch的，App内部Reademe、issues内容中的图片与链接也是支持3D touch的 @lzr52o
