### ISSUE TITLE
v1.9.4.119 - Star项目报错，不能正常显示Readm...

### ISSUE THREAD

**Issue by huoji555** [PPHubApp/PPHub-Feedback#357]
Star项目报错，不能正常显示Readme

运行环境: iPad 2018 - iOS12.3.1 - v1.9.4.119

**Comment by jkpang** [comment]
你好，刚刚试了下Star正常，仓库README和Trending 请求失败，应该是GitHub服务器部分接口挂了，这个要等待GitHub官方修复了 @huoji555
