### ISSUE TITLE
v1.9.4.119 - 可以增加issue啊

### ISSUE THREAD

**Issue by archine** [PPHubApp/PPHub-Feedback#359]
运行环境: iPhone 8 - iOS12.3.1 - v1.9.4.119

**Comment by jkpang** [comment]
你好，请问是给仓库创建issues的功能吗？ @archine

**Comment by archine** [comment]
可以增加有人提Issue的时候来个通知啥的


------------------ 原始邮件 ------------------
发件人: "jkpang"<notifications@github.com>;
发送时间: 2019年7月25日(星期四) 上午8:48
收件人: "PPHubApp/PPHub-Feedback"<PPHub-Feedback@noreply.github.com>;
抄送: "阿靖哦"<me@gjing.cn>;"Mention"<mention@noreply.github.com>;
主题: Re: [PPHubApp/PPHub-Feedback] v1.9.4.119 - 可以增加issue啊 (#359)




你好，请问是给仓库创建issues的功能吗？ @archine

**Comment by jkpang** [comment]
GitHub没有开放推送通知Api，自建推送服务器成本对我来说有点高了，所以暂时不会有这个计划 @archine

**Comment by archine** [comment]
好的吧




------------------ 原始邮件 ------------------
发件人: "jkpang"<notifications@github.com>;
发送时间: 2019年7月25日(星期四) 上午9:51
收件人: "PPHubApp/PPHub-Feedback"<PPHub-Feedback@noreply.github.com>;
抄送: "阿靖哦"<me@gjing.cn>;"Mention"<mention@noreply.github.com>;
主题: Re: [PPHubApp/PPHub-Feedback] v1.9.4.119 - 可以增加issue啊 (#359)




GitHub没有开放推送通知Api，自建推送服务器成本对我来说有点高了，所以暂时不会有这个计划 @archine
