### ISSUE TITLE
v1.9.4.119 - 希望加上代码编辑功能。
不然这12块钱真...

### ISSUE THREAD

**Issue by pch18** [PPHubApp/PPHub-Feedback#362]
希望加上代码编辑功能。
不然这12块钱真白瞎了。

运行环境: iPhone X - iOS12.3.1 - v1.9.4.119

**Comment by jkpang** [comment]
呃，只能说非常抱歉啦，PPHub暂时没有开发代码编辑功能的打算，建议使用桌面端专业工具进行编码操作哈。
我非常能理解你的对于没有编辑功能的心情，但我也对这款工具有自己的想法，只能说抱歉啦。如果你是在三个月内购买的PPHub，使用不满意是可以退款的哈，再次感谢对PPHub的支持。🍻🍻🍻 @pch18
