### ISSUE TITLE
v1.9.4.119 - Can you add the func...

### ISSUE THREAD

**Issue by DeppWang** [PPHubApp/PPHub-Feedback#364]
Can you add the function that user can edit own repositories files directly?

Environment: iPhone XR - iOS12.4 - v1.9.4.119

**Comment by jkpang** [comment]
I think editing files on an app is very inefficient and dangerous, so I won't do it for the time being. You can use the "Working Copy" associated with PPHub to Clone and edit files. @DeppWang
