### ISSUE TITLE
v1.9.5.121 - 在其他应用网络一切正常的情况下，无法查看...

### ISSUE THREAD

**Issue by AsuraLG** [PPHubApp/PPHub-Feedback#366]
在使用流量的情况下，其他应用网络一切正常，但是PPHub无法查看代码库里的任何文件，始终提示网络错误

运行环境: iPhone X - iOS12.3.1 - v1.9.5.121

**Comment by jkpang** [comment]
你好，系统设置里面是否关闭了PPHub在移动网络的权限？使用WiFi可以访问吗？ @AsuraLG

**Comment by AsuraLG** [comment]
> 你好，系统设置里面是否关闭了PPHub在移动网络的权限？使用WiFi可以访问吗？ @AsuraLG

并没有关闭权限，除了无法打开代码库的文件之外其他的网络访问均正常，刚刚测试在流量下打不开时直接切换至wifi一样会提示网络错误，无法请求到数据，但是退回到profile界面切换成wifi再进入代码库则可以浏览代码

**Comment by jkpang** [comment]
> 并没有关闭权限，除了无法打开代码库的文件之外其他的网络访问均正常，刚刚测试在流量下打不开时直接切换至wifi一样会提示网络错误，无法请求到数据，但是退回到profile界面切换成wifi再进入代码库则可以浏览代码

咦，奇怪，如果是使用内置网页打开私有代码库报错，那可能是cookie失效了，可以重新登录试试。 @AsuraLG

**Comment by AsuraLG** [comment]
> > 并没有关闭权限，除了无法打开代码库的文件之外其他的网络访问均正常，刚刚测试在流量下打不开时直接切换至wifi一样会提示网络错误，无法请求到数据，但是退回到profile界面切换成wifi再进入代码库则可以浏览代码
> 
> 咦，奇怪，如果是使用内置网页打开私有代码库报错，那可能是cookie失效了，可以重新登录试试。 @AsuraLG

这几天试了试，又没有什么问题了，可能是前几天的网络问题吧，抱歉了~

**Comment by jkpang** [comment]
没事没事，没问题就好👌🏻 @AsuraLG
