### ISSUE TITLE
v1.9.5.121 - First off awesome ap...

### ISSUE THREAD

**Issue by ryolambert** [PPHubApp/PPHub-Feedback#370]
First off awesome app! Your integrations with the Github api is fantastic! Really my only complaint is the app doesn’t have a Global dark mode, and the code syntax theme support is still lacking support for a couple of file types like Vue, JSX, etc. files. It’d be super nice, to get some better contrast/more colorful syntax themes like Monokai Pro or a global theming option like Theme-UI’s implementation. Otherwise, keep up the amazing work, the UI components are all super polished!!!

Environment: iPhone XS Max - iOS12.4 - v1.9.5.121

**Comment by Phoqe** [comment]
I agree, a dark mode is needed, especially now since the release of iOS 13 is just around the corner. iOS 13 introduces a system-wide dark mode and I would want PPHub to use that functionality.

**Comment by jkpang** [comment]
Thank you very much for your support of PPHub. Dark Mode is currently in progress, and some details are being improved. I hope I can get them done soon! @ryolambert @Phoqe 
![IMG_4594](https://user-images.githubusercontent.com/17583451/63145805-58f3a500-c02b-11e9-892f-2ca5b34b1bd0.PNG)
![IMG_4595](https://user-images.githubusercontent.com/17583451/63145809-5db85900-c02b-11e9-8c0d-e6403fcfdf57.PNG)

**Comment by jkpang** [comment]
#365 #338 #198 #144 #89

**Comment by Phoqe** [comment]
Nice, looks good!

**Comment by jkpang** [comment]
PPHub v2.0.0 is available
- Added: Dark Mode (Dark Mode);
- Added: Perfect support for iPad multitasking split screen mode;
- Optimization: adjust the layout and style of UI controls.
@ryolambert @Phoqe
