### ISSUE TITLE
is there a way to only follow Releases and not every change to a repo?

### ISSUE THREAD

**Issue by maxwelljordanwhite** [PPHubApp/PPHub-Feedback#375]
<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by jkpang** [comment]
Hello, because GitHub officially does not provide related APIs, this feature is temporarily unavailable. @maxwelljordanwhite

**Comment by maxwelljordanwhite** [comment]
@jkpang Hi, thanks for the response! Closing this, then. Love the app, by the way. :)

**Comment by jkpang** [comment]
Thank you for supporting PPHub!!! 🍻 @maxwelljordanwhite
