### ISSUE TITLE
Dark Mode Rules! But text is unreadable, now, when typing

### ISSUE THREAD

**Issue by gitatmax** [PPHubApp/PPHub-Feedback#378]
<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by jkpang** [comment]
Hello，Which interface text is unreadable? @maxwelljordanwhite

**Comment by jkpang** [comment]
Is the iOS13 Beta system? May be caused by the failure to set the UISearchBar font color. My performance on iOS 12.4 is normal. This problem needs to be resolved after the official release of iOS 13 @maxwelljordanwhite
