### ISSUE TITLE
v2.0.0.129 - 黑暗模式中，设置->自定义底部栏中的文字...

### ISSUE THREAD

**Issue by nlnlnull** [PPHubApp/PPHub-Feedback#379]
黑暗模式中，设置->自定义底部栏中的文字配色没有修改好。

运行环境: iPhone XS Max - iOS13.0 - v2.0.0(129)

**Comment by jkpang** [comment]
好的，感谢反馈，下个版本将优化这个问题。 @nlnlnull

**Comment by jkpang** [comment]
v2.0.1版本已优化
