### ISSUE TITLE
v1.9.5.121 - README.md display er...

### ISSUE THREAD

**Issue by DeppWang** [PPHubApp/PPHub-Feedback#382]
README.md display error. Feedback should can upload pic.

Environment: iPhone XR - iOS12.4 - v1.9.5.121

**Comment by jkpang** [comment]
Hello:
1. If the README of the private warehouse is loaded incorrectly, it is because the Cookie is invalid, so you need to log in again. 
2. The feedback is that the image cannot be uploaded because GitHub does not provide the corresponding Api
 @DeppWang

**Comment by DeppWang** [comment]
get it.



    
    
        font{
            line-height: 1.6;
        }
    
公众号：DeppWang个人博客：https://depp.wang个人主页：https://github.com/deppwang

     



            On 08/28/2019 20:22, jkpang wrote: Hello:

If the README of the private warehouse is loaded incorrectly, it is because the Cookie is invalid, so you need to log in again.
The feedback is that the image cannot be uploaded because GitHub does not provide the corresponding Api
@DeppWang


—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/PPHubApp/PPHub-Feedback/issues/382?email_source=notifications\u0026email_token=AFHWQJOGE7O5DX44S5L2AVTQGZUXVA5CNFSM4IRBZ2MKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5K5YTQ#issuecomment-525720654",
"url": "https://github.com/PPHubApp/PPHub-Feedback/issues/382?email_source=notifications\u0026email_token=AFHWQJOGE7O5DX44S5L2AVTQGZUXVA5CNFSM4IRBZ2MKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5K5YTQ#issuecomment-525720654",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jkpang** [comment]
PPHub v2.0.0 is available
- Added: Dark Mode (Dark Mode);
- Added: Perfect support for iPad multitasking split screen mode;
- Optimization: adjust the layout and style of UI controls.    
 @DeppWang
