### ISSUE TITLE
v2.0.0.129 - I love the new Dark ...

### ISSUE THREAD

**Issue by kyledwagner** [PPHubApp/PPHub-Feedback#383]
I love the new Dark Mode, but I feel that the blue color for the names of repositories isn’t visible enough against the background. Maybe it could be white like the description below?

Environment: iPhone 8 Plus - iOS12.4.1 - v2.0.0(129)

**Comment by Xiao79** [comment]
v2.4.2 is available @kyledwagner

**Comment by jkpang** [comment]
v2.4.2 is available @kyledwagner
