### ISSUE TITLE
从黑暗模式切换回的时候，搜索界面顶部样式出错

### ISSUE THREAD

**Issue by qgaye** [PPHubApp/PPHub-Feedback#384]
运行环境: iPhone 8 - iOS13.1.0 - v2.0.0

![IMG_0104](https://user-images.githubusercontent.com/33546916/63903989-090cd900-ca42-11e9-98d0-b8053256a09b.PNG)

**Comment by jkpang** [comment]
目前在iOS 13Beta系统上切换会有点问题，可能要到iOS 13正式版出来才能解决了。暂时解决的方案是杀掉进程重新进入 @qgaye

**Comment by qgaye** [comment]
ok 期待解决啦

**Comment by jkpang** [comment]
最新版已经解决，过了这么久才回复，抱歉~ 😂
@qgaye
