### ISSUE TITLE
v2.0.0.129 - 解除系统的 竖排锁定，打开 app ，横...

### ISSUE THREAD

**Issue by ChengLuffy** [PPHubApp/PPHub-Feedback#385]
解除系统的 竖排锁定，打开 app ，横屏， 软件崩溃

运行环境: iPhone XS - iOS13.0 - v2.0.0(129)

**Comment by ChengLuffy** [comment]
附带系统崩溃日志

[PPHub-2019-08-29-141502.ips.zip](https://github.com/PPHubApp/PPHub-Feedback/files/3554126/PPHub-2019-08-29-141502.ips.zip)

**Comment by jkpang** [comment]
好的，感谢反馈，我会尽快修复 @ChengLuffy

**Comment by jkpang** [comment]
请问按这个步骤操作，崩溃是必现的吗？ 我这边iOS 12.4各个模拟器、真机；iOS 13Beta的iPad没有出现 @ChengLuffy

**Comment by ChengLuffy** [comment]
13.0 beta8 先解除竖排锁定，再打开 app 必定复线

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ChengLuffy** [comment]
news 调到第一个，杀死应用再打开，就可以复现，Trending 是第一个是不会崩溃

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jkpang** [comment]
嗯嗯，复现了，感谢反馈！我会尽快修复！ @ChengLuffy

**Comment by jkpang** [comment]
v2.0.1 is available
