### ISSUE TITLE
v2.0.0.129 - 点击链接之后闪退

### ISSUE THREAD

**Issue by meetgudu** [PPHubApp/PPHub-Feedback#388]
运行环境: iPhone 7 Plus - iOS12.1.2 - v2.0.0(129)

**Comment by jkpang** [comment]
你好，请问是点击哪个地方的链接闪退？方便贴个地址吗？感谢 @meetgudu

**Comment by jkpang** [comment]
由于我不知道具体闪退的地方，我尝试修复了可能会发生Crash的方位，已发了新版本，明天应该可以更新，如果新版没有问题，希望看到能回复下下哈，感谢 @meetgudu

**Comment by jkpang** [comment]
v2.0.1已更新

**Comment by meetgudu** [comment]
已更新至最新版，目前使用没有出现闪退情况



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jkpang <notifications@github.com&gt;
发送时间: 2019年9月1日 16:47
收件人: PPHubApp/PPHub-Feedback <PPHub-Feedback@noreply.github.com&gt;
抄送: Yi_Py <1369705910@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[PPHubApp/PPHub-Feedback] v2.0.0.129 - 点击链接之后闪退 (#388)




由于我不知道具体闪退的地方，我尝试修复了可能会发生Crash的方位，已发了新版本，明天应该可以更新，如果新版没有问题，希望看到能回复下下哈，感谢 @meetgudu

**Comment by jkpang** [comment]
收到！ @meetgudu
