### ISSUE TITLE
v2.0.0.129 - 把star fork watch 三个按...

### ISSUE THREAD

**Issue by YangXiaoHei** [PPHubApp/PPHub-Feedback#389]
把star fork watch 三个按钮按照屏幕三等份是真的丑，希望改回原来的样子

运行环境: iPhone 6s - iOS12.0 - v2.0.0(129)

**Comment by jkpang** [comment]
你好，有其他用户正好意见相反，说之前版本不均等排列真丑，So。。。我只能说一千个人心中有一千个哈姆雷特了 🤣🤣🤣 @YangXiaoHei

**Comment by YangXiaoHei** [comment]
求一个上版本的 ipa 好吗！！😂




在2019年09月01日 16:43，jkpang 写道：

你好，有其他用户正好意见相反，说之前版本不均等排列真丑，So。。。我只能说一千个人心中有一千个哈姆雷特了 🤣🤣🤣@YangXiaoHei
