### ISSUE TITLE
v2.0.0.129 - https://raw.githubus...

### ISSUE THREAD

**Issue by qinjingchao123** [PPHubApp/PPHub-Feedback#391]
https://raw.githubusercontent.com/qinjingchao123/Mybatis1/master/%E7%94%B5%E5%AD%90%E4%B9%A6/6-%E6%B7%B1%E5%85%A5%E6%B5%85%E5%87%BAMyBatis%E6%8A%80%E6%9C%AF%E5%8E%9F%E7%90%86%E4%B8%8E%E5%AE%9E%E6%88%98%40ww.java1234.com.pdf    前边的是pdf的地址，不知道为什么打不开在我手机上

运行环境: iPhone XR - iOS12.4 - v2.0.0(129)

**Comment by jkpang** [comment]
你好，原因可能是这个文件体积太大了（81.1MB），导致在移动设备无法打开，这个问题暂时无法结局，在移动设备上还得用专业的PDF App打开，希望理解 @qinjingchao123 
![image](https://user-images.githubusercontent.com/17583451/64117838-c98b1780-cdc8-11e9-9615-e857b2bab87d.png)
