### ISSUE TITLE
进入某 Repo 后，界面右下角圈点呼出的菜单显示有些许瑕疵

### ISSUE THREAD

**Issue by wao1201** [PPHubApp/PPHub-Feedback#392]
Device: iPhone Xs Max
iOS: v12.4.1
App: The latest version

症状如图所示：
![photo_2019-09-02_11-44-36.jpg](https://i.loli.net/2019/09/02/9UB2h1zpXJxPYVw.jpg)

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by jkpang** [comment]
嗯嗯，v2.0.1已经在审核的路上了，已优化这个问题 @wao1201

**Comment by jkpang** [comment]
v2.0.1已更新 @wao1201
