### ISSUE TITLE
v2.0.1.131 - stars today 显示有问题，显示...

### ISSUE THREAD

**Issue by leslieeilsel** [PPHubApp/PPHub-Feedback#394]
stars today 显示有问题，显示的是该项目的总star数

运行环境: iPhone 7 Plus - iOS12.4.1 - v2.0.1(131)

**Comment by jkpang** [comment]
嗯嗯，应该是GitHub调整了数据格式，我会尽快调整解析方式，修复这个问题 @leslieeilsel

**Comment by jkpang** [comment]
你好，刚刚看了GitHub Trending：https://github.com/trending 的官网数据也是错的，看来是官方的锅，如下图：
![image](https://user-images.githubusercontent.com/17583451/64266500-4227da80-cf67-11e9-97bb-718ecdd4c7cc.png)
@leslieeilsel

**Comment by jkpang** [comment]
目前数据已恢复正常
