### ISSUE TITLE
v2.0.1.131 - 不能获得私人仓库么？

### ISSUE THREAD

**Issue by FengGuanxi** [PPHubApp/PPHub-Feedback#395]
运行环境: iPhone XR - iOS12.4 - v2.0.1(131)

**Comment by jkpang** [comment]
可以访问的，在登陆的时候是否选择了“私有库+公开库”选项登录？ @FengGuanxi

**Comment by cactusnix** [comment]
对的 可以退出重新登录一下 选择私有库+公开库选项重新登录一下 我本来也无法访问重新授权后可以了
