### ISSUE TITLE
v2.0.1.131 - 代码的字体大小可以调整吗，如果没有建议增...

### ISSUE THREAD

**Issue by Silverdiscs** [PPHubApp/PPHub-Feedback#397]
代码的字体大小可以调整吗，如果没有建议增加一下

运行环境: iPhone 7 Plus - iOS12.4 - v2.0.1(131)

**Comment by jkpang** [comment]
你好，目前还不可以调整代码字体大小，这个Feature我会考虑的 @Silverdiscs

**Comment by jkpang** [comment]
v2.4.0已支持调整代码字体大小，快去更新吧！@Silverdiscs
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-05-27 at 00 29 00](https://user-images.githubusercontent.com/17583451/83014737-d2580380-a051-11ea-93ec-0df8d4cf416e.PNG)
