### ISSUE TITLE
v2.0.1.131 - 我在使用的过程中体验交互性很好，相信开发...

### ISSUE THREAD

**Issue by ghost** [PPHubApp/PPHub-Feedback#398]
我在使用的过程中体验交互性很好，相信开发者可以在以后的开发中继续努力，可以将浏览文件的阅读和浏览变得更加流畅！加油干

运行环境: iPhone 7 - iOS12.3.1 - v2.0.1(131)

**Comment by jkpang** [comment]
哈哈，非常感谢支持！我会继续努力的💪💪💪
