### ISSUE TITLE
v2.0.1.131 - 暗黑主题时，搜索关键词看不见，搜索框和文...

### ISSUE THREAD

**Issue by cszdlq** [PPHubApp/PPHub-Feedback#399]
暗黑主题时，搜索关键词看不见，搜索框和文字都是黑的

运行环境: iPad11,3 - iOS13.1 - v2.0.1(131)

**Comment by jkpang** [comment]
你好，这是iOS 13的问题，我会在iOS   @@13正式版出来立即解决这个问题 @cszdlq

**Comment by jkpang** [comment]
v2.1.0已可用，已适配iOS 13 @cszdlq
