### ISSUE TITLE
v2.0.2.135 - Can you add support ...

### ISSUE THREAD

**Issue by hacknug** [PPHubApp/PPHub-Feedback#404]
Can you add support for Dynamic Type please?

Environment: iPhone XS - iOS13.1 - v2.0.2(135)

**Comment by jkpang** [comment]
Is the "Dynamic Type" support for that interface or function? @hacknug

**Comment by hacknug** [comment]
It's a feature. You can find it on the Settings.app, under _Display & Brightness -> Text Size_.

**Comment by jkpang** [comment]
v2.4.0 now supports resizing code fonts.
