### ISSUE TITLE
v2.0.2.135 - 深色模式下，搜索框字体是黑色的，导致看不...

### ISSUE THREAD

**Issue by fyved24** [PPHubApp/PPHub-Feedback#405]
深色模式下，搜索框字体是黑色的，导致看不清楚输入的内容。

运行环境: iPhone 8 - iOS13.1 - v2.0.2(135)

**Comment by jkpang** [comment]
你好，这是iOS 13的问题，等正式版出来会立马解决 @fyved24

**Comment by jkpang** [comment]
v2.1.0已可用，已适配iOS 13 @fyved24
