### ISSUE TITLE
v2.0.2.135 - 切换白天黑夜模式的时候，上下和中间部分有...

### ISSUE THREAD

**Issue by weichenlxp** [PPHubApp/PPHub-Feedback#406]
切换白天黑夜模式的时候，上下和中间部分有割裂感，看起来上下是同时切换的，中间不是

运行环境: iPad 2018 - iOS13.1 - v2.0.2(135)

**Comment by jkpang** [comment]
iOS 13的问题，等正式版出了会立马解决 @weichenlxp

**Comment by jkpang** [comment]
v2.1.0已可用，已适配iOS 13。割裂问题因为在切换时，中间内容有过渡动画，而上下栏系统没有提供相关的动画方式，所以会有此问题。 @weichenlxp
