### ISSUE TITLE
v2.0.2.135 - Feature request: add...

### ISSUE THREAD

**Issue by Lancern** [PPHubApp/PPHub-Feedback#407]
Feature request: add settings to customize the appearance of code viewer, e.g. font face, font size, color scheme, etc.

运行环境: iPad 2017 - iOS12.3.1 - v2.0.2(135)

**Comment by jkpang** [comment]
v2.4.0 is available.  @Lancern 
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-05-27 at 00 29 00](https://user-images.githubusercontent.com/17583451/83015098-7d68bd00-a052-11ea-8b72-26c3c06d78bb.PNG)
