### ISSUE TITLE
v2.0.2.135 - 查看某些项目的代码，好慢啊。一样能出下载...

### ISSUE THREAD

**Issue by luozhe73** [PPHubApp/PPHub-Feedback#408]
查看某些项目的代码，好慢啊。一样能出下载repository代码的功能，把代码离线到本地，这样打开项目查看代码会快很多

运行环境: iPhone XR - iOS12.3.1 - v2.0.2(135)

**Comment by jkpang** [comment]
你好，速度慢是因为GitHub在国内的DNS解析被污染（原因你懂的）。若需要离线下载看代码，可以点击仓库详情页右下角的菜单按钮，滑动至第二页，点击Working Copy即可 @luozhe73
