### ISSUE TITLE
v2.0.2.135 - 搜索栏的字体颜色可以调整下，暗黑模式下无...

### ISSUE THREAD

**Issue by chaoedu** [PPHubApp/PPHub-Feedback#409]
搜索栏的字体颜色可以调整下，暗黑模式下无法看清

运行环境: iPhone XS - iOS13.1 - v2.0.2(135)

**Comment by jkpang** [comment]
你好，这是iOS 13的原因，等正式版出来我会尽快解决这个问题 @chaoedu

**Comment by jkpang** [comment]
v2.1.0已可用，已适配iOS 13
