### ISSUE TITLE
v2.0.2.135 - 莫名其妙，每次搜都会冒出一个叫zhaoh...

### ISSUE THREAD

**Issue by caijynb** [PPHubApp/PPHub-Feedback#412]
莫名其妙，每次搜都会冒出一个叫zhaohmng的用户在最前

运行环境: iPhone X - iOS12.4.1 - v2.0.2(135)

**Comment by jkpang** [comment]
你好，是搜索任何关键字都会这样吗？搜索用户的默认排序是降序。我这边没有出现这种情况 @caijynb

**Comment by caijynb** [comment]
抱歉，应该是个人搜索问题。

**Comment by jkpang** [comment]
嗯嗯，应该是在你搜的关键字zhaohmng这个用户的Follower最多，所以就排在了前面
