### ISSUE TITLE
v2.0.2.135 - 请问有没有方式把工程压成一个压缩包下载下...

### ISSUE THREAD

**Issue by hy2013** [PPHubApp/PPHub-Feedback#413]
请问有没有方式把工程压成一个压缩包下载下来？

运行环境: iPhone 7 - iOS12.4.1 - v2.0.2(135)

**Comment by jkpang** [comment]
可以配合Working Copy 离线下载，仓库详情-右下角菜单按钮-左滑第二页，点击即可 @hy2013
