### ISSUE TITLE
v2.0.3.136 - 这暗色模式并不能随系统的全局设置啊

### ISSUE THREAD

**Issue by gzy645272019** [PPHubApp/PPHub-Feedback#415]
运行环境: iPhone X - iOS13.0 - v2.0.3(136)

**Comment by jkpang** [comment]
你好，苹果今天才更新Xcode，目前正在做iOS 13的适配 @gzy645272019

**Comment by jkpang** [comment]
v2.1.0已可用，已适配iOS 13
