### ISSUE TITLE
v2.0.2.135 - 希望深色模式颜色能随时间调整，现在太暗了

### ISSUE THREAD

**Issue by DeppWang** [PPHubApp/PPHub-Feedback#416]
运行环境: iPhone XR - iOS13.0 - v2.0.2(135)

**Comment by jkpang** [comment]
昨天苹果才更新Xcode11正式版，现在正在适配iOS13的系统黑暗模式 @DeppWang

**Comment by jkpang** [comment]
v2.1.0已可用，已适配iOS 13。 @DeppWang
