### ISSUE TITLE
v2.0.3.136 - 可否将夜间模式和白天模式的切换改为跟随系...

### ISSUE THREAD

**Issue by sunyongsheng** [PPHubApp/PPHub-Feedback#417]
可否将夜间模式和白天模式的切换改为跟随系统

运行环境: iPad11,3 - iOS13.1 - v2.0.3(136)

**Comment by jkpang** [comment]
昨天苹果才更新Xcode11正式版，现在正在适配 @sunyongsheng

**Comment by jkpang** [comment]
v2.1.0已可用，已适配iOS 13 @sunyongsheng
