### ISSUE TITLE
v2.0.3.136 - I noticed the item t...

### ISSUE THREAD

**Issue by marionebl** [PPHubApp/PPHub-Feedback#420]
I noticed the item to switch branches is misspelled “Branchs”

Environment: iPhone XS - iOS13.0 - v2.0.3(136)

**Comment by jkpang** [comment]
Thanks for the feedback, my fault, this problem will be fixed in the next version. @marionebl

**Comment by jkpang** [comment]
v2.1.0 is available, this problem has been fixed @marionebl
