### ISSUE TITLE
v2.0.3.136 - 深色模式下，搜索框字体还是黑色的然后看不...

### ISSUE THREAD

**Issue by Fndroid** [PPHubApp/PPHub-Feedback#421]
深色模式下，搜索框字体还是黑色的然后看不清了

希望支持跟随系统变化深色和亮色

Environment: iPhone XR - iOS13.0 - v2.0.3(136)

**Comment by jkpang** [comment]
正在适配iOS 13，可能会在这两天发布 @Fndroid

**Comment by jkpang** [comment]
v2.1.0已可用，已适配iOS 13。 @Fndroid
