### ISSUE TITLE
v2.0.3.136 - 因为iPados把通知的界面变窄了，现在...

### ISSUE THREAD

**Issue by beardnick** [PPHubApp/PPHub-Feedback#427]
因为iPados把通知的界面变窄了，现在通知的组件显示得不完全，希望改进一下

运行环境: iPad 2018 - iOS13.1 - v2.0.3(136)

**Comment by jkpang** [comment]
你好，是顶部的这个Banner提醒控件吗 @beardnick 
![image](https://user-images.githubusercontent.com/17583451/65658986-69506400-e05c-11e9-9c4c-e9651d543beb.png)

**Comment by beardnick** [comment]
不好意思，我没有表述清楚，是指这个挂件






------------------ 原始邮件 ------------------
发件人: jkpang <notifications@github.com&gt;
发送时间: 2019年9月26日 12:52
收件人: PPHubApp/PPHub-Feedback <PPHub-Feedback@noreply.github.com&gt;
抄送: qianz <1685437606@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[PPHubApp/PPHub-Feedback] v2.0.3.136 - 因为iPados把通知的界面变窄了，现在... (#427)




你好，是顶部的这个Banner提醒控件吗 @beardnick

**Comment by jkpang** [comment]
> 不好意思，我没有表述清楚，是指这个挂件

明白了，你说的是负一屏的Today挂件。emmm.....这个就改不了了，目前只能截断显示。
