### ISSUE TITLE
v2.1.0.141 - 阅读代码，把重力感应打开，横屏会崩溃闪退...

### ISSUE THREAD

**Issue by yihong0618** [PPHubApp/PPHub-Feedback#430]
阅读代码，把重力感应打开，横屏会崩溃闪退。

运行环境: iPhone XR - iOS13.1 - v2.1.0(141)

**Comment by jkpang** [comment]
你好，我这边没有复现。你这边查看喷一仓库代码都是必现的吗？ @yihong0618

**Comment by jkpang** [comment]
用模拟器复现了，在刘海屏的机型上会出现，感谢反馈

**Comment by yihong0618** [comment]
是的。。。我这台机器100%复现。横屏的起因是之前用pythonista横屏看代码很爽

**Comment by jkpang** [comment]
嗯嗯，问题我昨晚已修复，我会尽快提审修复版本

**Comment by yihong0618** [comment]
感谢作者

**Comment by jkpang** [comment]
哈哈，客气啦，这是我应该的！

**Comment by jkpang** [comment]
v2.1.1已可更新，已修复这个问题 @jkpang
