### ISSUE TITLE
v2.1.1.145 - 希望加入翻译功能

### ISSUE THREAD

**Issue by dayhi** [PPHubApp/PPHub-Feedback#435]
运行环境: iPhone 6s - iOS13.1 - v2.1.1(145)

**Comment by dayhi** [comment]
就是README.md的翻译功能

**Comment by jkpang** [comment]
2.2.0已添加“翻译”功能，快去更新吧！ @dayhi

**Comment by dayhi** [comment]
已经更新，但是没有找到翻译按钮，如何操作呢？

发自我的iPhone
