### ISSUE TITLE
v2.1.1.145 - 能否增加消息提醒，Watch项目更新和I...

### ISSUE THREAD

**Issue by darkr4y** [PPHubApp/PPHub-Feedback#436]
能否增加消息提醒，Watch项目更新和Issue更新都有提醒呢？

运行环境: iPhone 8 Plus - iOS13.1.2 - v2.1.1(145)

**Comment by jkpang** [comment]
你好，由于GitHub 没有开放相关推送Api，自建推送服务器成本较大，所以暂时没有这个计划了。 @darkr4y
