### ISSUE TITLE
v2.1.1.145 - 请问怎么取消选择的语言，恢复默认

### ISSUE THREAD

**Issue by Zhiwei1996** [PPHubApp/PPHub-Feedback#438]
Environment: iPhone XR - iOS13.1 - v2.1.1(145)

**Comment by jkpang** [comment]
你好，请问是App语言，还是编程语言分类？ @Zhiwei1996

**Comment by Zhiwei1996** [comment]
编程语言分类

**Comment by jkpang** [comment]
没有恢复默认选择的按钮选项。默认选择在中文环境下是：所有语言，在英文环境下是：Any，选择这个选项即可。 @Zhiwei1996

**Comment by Zhiwei1996** [comment]
明白鸟，我没注意看，没看到这个选项，现在好了

**Comment by jkpang** [comment]
OK！
