### ISSUE TITLE
v2.1.1.145 - .yaml 文件，打开时，显示 请求错误...

### ISSUE THREAD

**Issue by imnicy** [PPHubApp/PPHub-Feedback#439]
.yaml 文件，打开时，显示 请求错误。

运行环境: iPhone 6s Plus - iOS13.1.1 - v2.1.1(145)

**Comment by jkpang** [comment]
你好，是顶部弹横幅提示，还是弹窗提示编码错误？ @imnicy

**Comment by imnicy** [comment]
是顶部横幅提示，红色的信息。

**Comment by jkpang** [comment]
明白了，你点击的应该是最右边的🌀符号按钮，这是查看文件的原始文本数据，点击🌀符号以外的区域就可以了。这个问题等国庆过完我再看看。感谢反馈 @imnicy

**Comment by imnicy** [comment]
.yaml文件后面没有那个 🌀 符号， 之前我手机中的版本打开是这样子的，我没有重装，现在是最新版本。不知道其他机器是不是这样子。我尝试打开了好几个别人项目中的.yaml文件，都是同样的情况。 你可以很容易复现我的情况，在octobercms/october 项目中的plugins/octoner/demo/updates/version.yaml尝试打开看看。

> 在 2019年10月4日，09:16，jkpang <notifications@github.com> 写道：
> 
> 🌀

**Comment by jkpang** [comment]
你好，经过排查，这类文件在iOS13以下的系统是可以正常打开的。是在iOS13中，可能是苹果改变了WKWebView的内部实现，导致打不开，目前还没有解决的方案，不过我会持续关注这个问题。
此类文件在浏览器中被识别成了一个文件，并没有加载其中的内容。
![Simulator Screen Shot - iPhone 8 - 2019-10-12 at 20 43 48](https://user-images.githubusercontent.com/17583451/66701647-0257ce00-ed31-11e9-8612-18efa8075b95.png)
@imnicy

**Comment by jkpang** [comment]
v2.1.2已更新，已修复了这个问题 @imnicy
