### ISSUE TITLE
v2.1.1.145 - 这是一个非常好的软件，就是每次查看代码都...

### ISSUE THREAD

**Issue by daiweinice** [PPHubApp/PPHub-Feedback#440]
这是一个非常好的软件，就是每次查看代码都要加载很久，希望能够有一个将仓库代码保存到本地的功能！

运行环境: iPhone 7 - iOS13.1.2 - v2.1.1(145)

**Comment by jkpang** [comment]
你好，可以通过内置Working Copy入口来clone代码，仓库详情-右下角菜单按钮-左滑至第二页-Working Copy，同issue：#241     
@daiweinice
