### ISSUE TITLE
v2.1.1.145 - Repositories如果可以实现每次...

### ISSUE THREAD

**Issue by LengMingxuan** [PPHubApp/PPHub-Feedback#447]
Repositories如果可以实现每次刷新都会换一批的功能就比较好了，不知道开发者可不可以实现

运行环境: iPhone XR - iOS13.1.2 - v2.1.1(145)

**Comment by jkpang** [comment]
你好，首页Repositories数据根据GitHub Trending网站数据改变的哦！是查看GitHub仓库排行榜的 @LengMingxuan

**Comment by LengMingxuan** [comment]
了解了，谢谢开发者解答问天，，App非常棒，支持！

**Comment by LengMingxuan** [comment]
了解了，谢谢开发者解答问题，App非常棒，支持！

**Comment by jkpang** [comment]
哈哈，感谢感谢😘 @LengMingxuan
