### ISSUE TITLE
v2.1.1.145 - 您好，首先表示我对您做出如此优秀的app...

### ISSUE THREAD

**Issue by fangxue93** [PPHubApp/PPHub-Feedback#448]
您好，首先表示我对您做出如此优秀的app的感谢。然而分享到微信的时候有卡顿，屏幕顿住没用反馈，只能后台退出再重新进入app。希望PPHub会更好。

运行环境: iPhone SE - iOS11.4 - v2.1.1(145)

**Comment by jkpang** [comment]
非常感谢您的反馈！我也遇到过这样的情况。微信分享插件在分享时会请求网络来解析分享链接，我猜测在网络差的情况下，这个解析链接的过程阻塞了UI操作，导致屏幕无响应。
这个问题需要微信官方优化了  @fangxue93
