### ISSUE TITLE
v2.1.1.145 - Issue 页面现在还是打开了一个网页 ...

### ISSUE THREAD

**Issue by jwenjian** [PPHubApp/PPHub-Feedback#449]
Issue 页面现在还是打开了一个网页 有没有计划做成原生的页面？

Environment: iPhone 8 - iOS13.1.2 - v2.1.1(145)

**Comment by jkpang** [comment]
嗯嗯，我认为目前GitHub issues网页在内容展示上的观感体验是最好的，相比于原生界面，只是文本输入体验差了一点点。但是不排除以后用原生界面的可能  @jwenjian
