### ISSUE TITLE
v2.1.1.145 - 为什么我的news标签界面刷新不出来？

### ISSUE THREAD

**Issue by WangChenhuan** [PPHubApp/PPHub-Feedback#450]
运行环境: iPhone 7 - iOS13.1.2 - v2.1.1(145)

**Comment by jkpang** [comment]
多Follow 、Watch 几个活跃的开发者和仓库就有了 @WangChenhuan

**Comment by WangChenhuan** [comment]
这个开发者是真的厉害👍！能不能给小白的我推荐几个机器学习的大牛？不甚感激！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jkpang <notifications@github.com&gt;
发送时间: 2019年10月17日 11:14
收件人: PPHubApp/PPHub-Feedback <PPHub-Feedback@noreply.github.com&gt;
抄送: Wang <1041324602@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[PPHubApp/PPHub-Feedback] v2.1.1.145 - 为什么我的news标签界面刷新不出来？ (#450)




多Follow 、Watch 几个活跃的开发者和仓库就有了 @WangChenhuan

**Comment by jkpang** [comment]
我对机器学习不了解哦，大牛就更不认识啦😂 @WangChenhuan
