### ISSUE TITLE
v2.1.1.145 - 仓库里代码可以一次性全部下载到本地缓存吗...

### ISSUE THREAD

**Issue by laiwenqiang** [PPHubApp/PPHub-Feedback#452]
仓库里代码可以一次性全部下载到本地缓存吗？

运行环境: iPhone SE - iOS13.1.2 - v2.1.1(145)

**Comment by jkpang** [comment]
你好，可以通过内置Working Copy入口来clone代码，仓库详情-右下角菜单按钮-左滑至第二页-Working Copy，同issue：#241    @laiwenqiang
