### ISSUE TITLE
v2.1.2.147 - 您好，请问看别人代码时的主题能设置成自动...

### ISSUE THREAD

**Issue by YvanYifeiLi** [PPHubApp/PPHub-Feedback#453]
您好，请问看别人代码时的主题能设置成自动跟随系统主题（白天/黑暗）吗？现在整个软件都跟随系统，但是代码主题却没有.... 或许可以让软件分别设置白天模式和黑暗模式的代码主题。谢谢！

Environment: iPhone XS - iOS13.2 - v2.1.2(147)

**Comment by jkpang** [comment]
你好，当初我也想到了这个问题。因为代码主题有很多个，而且选择一次后，再次进去会记住上一次的选择。如果随着白天、黑夜模式改变主题，两者操作就冲突了。所以，我还是把代码选择主题的主动权交给用户会好些。 @YvanYifeiLi

**Comment by YvanYifeiLi** [comment]
您好，其实类似情况在其他的软件上是有的，比如Unread（如下图）的处理方法就是让用户分别选一款白天与黑夜的主题，之后会跟随系统分别对应不同的所选两款主题。

不过我不知道您软件的底层架构是什么，这里只是提个建议。谢谢！

[cid:FCF36AB5A6154A4893D6C0C7EF4E5A10][cid:E1AC359B03D74EA8AEA4F57F5000A053]
On Oct 25, 2019, 1:21 AM -0500, jkpang <notifications@github.com>, wrote:

你好，当初我也想到了这个问题。因为代码主题有很多个，而且选择一次后，再次进去会记住上一次的选择。如果随着白天、黑夜模式改变主题，两者操作就冲突了。所以，我还是把代码选择主题的主动权交给用户会好些。 @YvanYifeiLi<https://github.com/YvanYifeiLi>

**Comment by jkpang** [comment]
嗯嗯，非常感谢你的反馈，我在后续的版本中会好好考虑这个Feature的

**Comment by jkpang** [comment]
2.2.0已优化此问题，快去更新吧！ @YvanYifeiLi
