### ISSUE TITLE
v2.1.2.147 - I can’t find a way t...

### ISSUE THREAD

**Issue by Tyounoyume** [PPHubApp/PPHub-Feedback#460]
I can’t find a way to change the size of the fonts. My eyes are not good, and I just want the code a little bit bigger.

Environment: iPad Pro 10.5 Inch - iOS13.1.3 - v2.1.2(147)

**Comment by jkpang** [comment]
Hello, sorry, there is currently no feature to change the font size of the code. But you can pass the code to the professional code editor via the built-in entry of PPHub: "Working Copy". I will try to optimize this issue in a future release. @Tyounoyume

**Comment by jkpang** [comment]
v2.4.0 is available. @Tyounoyume 
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-05-27 at 00 29 00](https://user-images.githubusercontent.com/17583451/83014737-d2580380-a051-11ea-93ec-0df8d4cf416e.PNG)
