### ISSUE TITLE
v2.1.2.147 - 为什么有些正常的.cpp文件无法打开，而...

### ISSUE THREAD

**Issue by weiyaoxing** [PPHubApp/PPHub-Feedback#462]
为什么有些正常的.cpp文件无法打开，而点击显示用网页打开的时候是正常的

运行环境: iPhone 6s Plus - iOS12.1.4 - v2.1.2(147)

**Comment by jkpang** [comment]
你好，因为有些cpp文件的编码不是utf8，在iOS平台将文本转码到utf8失败了，所以才显示不出。这个问题一直在寻找可行的解决方案，暂时只能通过网页查看编码失败的文件了。 @weiyaoxing
