### ISSUE TITLE
v2.1.2.147 - 看不了代码了，提示网络错误

### ISSUE THREAD

**Issue by ysppp** [PPHubApp/PPHub-Feedback#465]
运行环境: iPad Pro 11 Inch - iOS13.1.3 - v2.1.2(147)

**Comment by jkpang** [comment]
你好，是因为GitHub查看文件Raw数据的链接挂掉了，导致请求数据出错，只能等GitHub修复了。 @ysppp

**Comment by jkpang** [comment]
现在https://raw.githubusercontent.com/  已基本回复正常，可以访问了。
