### ISSUE TITLE
v2.1.2.147 - 老是网络错误 我晕了

### ISSUE THREAD

**Issue by TiankaiHang** [PPHubApp/PPHub-Feedback#466]
运行环境: iPad 6 - iOS13.1.3 - v2.1.2(147)

**Comment by jkpang** [comment]
你好，请问是在查看代码文件时弹出的提示吗？前天晚上开始，GitHub查看文件raw网站挂了，访问不了，只能等GitHub修复了  @TiankaiHang

**Comment by jkpang** [comment]
https://raw.githubusercontent.com/ 现在在国内被墙了

**Comment by jkpang** [comment]
现在https://raw.githubusercontent.com/  已基本回复正常，可以访问了。
