### ISSUE TITLE
v2.1.2.147 - 查看远码一直提示请求错误啊

### ISSUE THREAD

**Issue by xcc2** [PPHubApp/PPHub-Feedback#468]
运行环境: iPhone XS Max - iOS13.2 - v2.1.2(147)

**Comment by jkpang** [comment]
https://raw.githubusercontent.com/ 现在被墙了 @xcc2

**Comment by jkpang** [comment]
现在https://raw.githubusercontent.com/  已基本回复正常，可以访问了。
