### ISSUE TITLE
v2.1.2.147 - 打开java文件的时候，一直转圈。打不开...

### ISSUE THREAD

**Issue by zhyaqi** [PPHubApp/PPHub-Feedback#469]
打开java文件的时候，一直转圈。打不开文件

运行环境: iPhone X - iOS12.1 - v2.1.2(147)

**Comment by jkpang** [comment]
https://raw.githubusercontent.com/ 现在被墙了, 开V*PN可以看 @zhyaqi

**Comment by jkpang** [comment]
现在https://raw.githubusercontent.com/  已基本回复正常，可以访问了。
