### ISSUE TITLE
v2.1.2.147 - 查看代码会提示“请求错误”

### ISSUE THREAD

**Issue by andyMemory** [PPHubApp/PPHub-Feedback#470]
运行环境: iPad Air 3 - iOS13.1.3 - v2.1.2(147)

**Comment by andyMemory** [comment]
还有系统静音之后，点击PPHub客户端仍会有提示音

**Comment by jkpang** [comment]
你好：
1、https://raw.githubusercontent.com/ 现在被墙了，时好时坏, 开V*PN可以看 
2、是点击哪里的按钮有声音？
@andyMemory
