### ISSUE TITLE
v2.1.2.147 - 打不开源码！！！！！

### ISSUE THREAD

**Issue by ChinaWim** [PPHubApp/PPHub-Feedback#471]
运行环境: iPhone11 - iOS13.1.3 - v2.1.2(147)

**Comment by jkpang** [comment]
你好：因为https://raw.githubusercontent.com/ 现在被墙了，时好时坏, 开VPN可以看。（WiFi网络打不开，可以试试手机移动网络） @ChinaWim

**Comment by jkpang** [comment]
现在https://raw.githubusercontent.com/  已基本回复正常，可以访问了。
