### ISSUE TITLE
v2.1.2.147 - 文件内容加载不出来打开几个py文件都是的

### ISSUE THREAD

**Issue by pamphiluss** [PPHubApp/PPHub-Feedback#472]
运行环境: iPad 6 - iOS13.1.3 - v2.1.2(147)

**Comment by jkpang** [comment]
你好：因为https://raw.githubusercontent.com/ 现在被墙了，时好时坏, 开VPN可以看。（WiFi网络打不开，可以试试手机移动网络) @pamphiluss

**Comment by pamphiluss** [comment]
好的谢谢



---原始邮件---
发件人: "jkpang"<notifications@github.com&gt;
发送时间: 2019年11月6日(星期三) 晚上11:23
收件人: "PPHubApp/PPHub-Feedback"<PPHub-Feedback@noreply.github.com&gt;;
抄送: "syd"<1349619363@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题: Re: [PPHubApp/PPHub-Feedback] v2.1.2.147 - 文件内容加载不出来打开几个py文件都是的 (#472)



你好：因为https://raw.githubusercontent.com/ 现在被墙了，时好时坏, 开VPN可以看。（WiFi网络打不开，可以试试手机移动网络) @pamphiluss

**Comment by jkpang** [comment]
现在https://raw.githubusercontent.com/  已基本回复正常，可以访问了。
