### ISSUE TITLE
v2.1.3.148 - 希望取消音效或者使其可选。
设置关闭音效...

### ISSUE THREAD

**Issue by liushichuan** [PPHubApp/PPHub-Feedback#479]
希望取消音效或者使其可选。
设置关闭音效后，star时会有音效，我比较安静，我自己知道我在干什么，所以这个音效不需要。

运行环境: iPhone XR - iOS13.2.2 - v2.1.3(148)

**Comment by jkpang** [comment]
好的，感谢反馈！ @liushichuan

**Comment by jkpang** [comment]
2.2.0已优化此问题，已可更新 @liushichuan
