### ISSUE TITLE
v2.1.3.148 - 有些repo搜不到，是有权限的

### ISSUE THREAD

**Issue by l3031875** [PPHubApp/PPHub-Feedback#480]
运行环境: iPhone11 Pro - iOS13.1.3 - v2.1.3(148)

**Comment by jkpang** [comment]
如果已授权私有权限，搜索私有库，当前用户的的私有库是可以搜到的，但是你参加的组织私有库不一定能搜索到，这一点我也很伤，不知道为啥GitHub Api和网页版的不一样  @l3031875
