### ISSUE TITLE
v2.1.3.148 - Would you consider h...

### ISSUE THREAD

**Issue by TobiasRuano** [PPHubApp/PPHub-Feedback#487]
Would you consider having the app automatically switch between dark and light mode based on the device settings?

Environment: iPhone XS - iOS13.2.3 - v2.1.3(148)

**Comment by jkpang** [comment]
Hello, PPHub now automatically switches to the dark mode of the device system. @TobiasRuano

**Comment by TobiasRuano** [comment]
Hi, yes it does! but for some weird reason I had to re download the app again. Now it works as intended! Thanks.
