### ISSUE TITLE
v2.1.3.148 - 中文设置不管用？

### ISSUE THREAD

**Issue by bageshangqian** [PPHubApp/PPHub-Feedback#490]
运行环境: iPad Mini 5 - iOS13.1.3 - v2.1.3(148)

**Comment by jkpang** [comment]
你好，PPHub目前只做了与GitHub内容不相关的汉化。我觉得觉得这样比较符合GitHub的传统，如果汉化 Star -> 星标、Fork -> 分叉..... 这样总感觉怪怪的，GitHub官方就只有英语一种语言，我认为有关于它的内容还是原生态的好一些。 @bageshangqian
