### ISSUE TITLE
v2.1.3.148 - 所有用户的头像都不显示了，不知是网络问题...

### ISSUE THREAD

**Issue by coda1997** [PPHubApp/PPHub-Feedback#495]
所有用户的头像都不显示了，不知是网络问题加载超时，还是因为bug的问题。

运行环境: iPhone X - iOS13.2.3 - v2.1.3(148)

**Comment by coda1997** [comment]
sorry，自己的网络问题，挂ss就好了，辣鸡联通。

**Comment by jkpang** [comment]
我的也是联通，但是感觉还好诶，没挂ss，大部分都能秒开 😂
