### ISSUE TITLE
v2.1.3.148 - 问什么私有项目能看到文件目录，点进去却是...

### ISSUE THREAD

**Issue by wuxiaohua123** [PPHubApp/PPHub-Feedback#496]
问什么私有项目能看到文件目录，点进去却是404。

运行环境: iPhone 6 Plus - iOS11.2.5 - v2.1.3(148)

**Comment by jkpang** [comment]
你好，有些文件是用WebView展示的，有时候可能Cookie失效。退出账号重新使用网页授权登录就好了，在未来的版本我会尝试优化这个问题  @wuxiaohua123
