### ISSUE TITLE
v2.1.3.148 - fork之后，能不能提示哪些已经被for...

### ISSUE THREAD

**Issue by chensaics** [PPHubApp/PPHub-Feedback#497]
fork之后，能不能提示哪些已经被fork了？有的重复fork也不知道。

运行环境: iPhone 6s - iOS13.1.2 - v2.1.3(148)

**Comment by jkpang** [comment]
你好，这个GitHub没有提供相关Api，检查不了哦。目前如果是Fork同一仓库多次，最终只会有一份Fork的仓库。
