### ISSUE TITLE
v2.1.3.148 - 代码都打不开了呀

### ISSUE THREAD

**Issue by advancc** [PPHubApp/PPHub-Feedback#498]
运行环境: iPhone11 - iOS13.2.3 - v2.1.3(148)

**Comment by jkpang** [comment]
你好，如果是私有库代码，可使用App内网页重新授权登录(偶尔存在cookie失效的问题)；如果是公有库代码，可更换网络环境后查看，GitHub在国内DNS被污染了，有时请求会超时......  @advancc
