### ISSUE TITLE
v2.2.0.151 - 绿色的 activity 记录总是刷不出...

### ISSUE THREAD

**Issue by leoyejl** [PPHubApp/PPHub-Feedback#499]
绿色的 activity 记录总是刷不出来。

Environment: iPhone 6s Plus - iOS13.2.3 - v2.2.0(151)

**Comment by jkpang** [comment]
你好，解决方案可以看看这个issue：https://github.com/PPHubApp/PPHub-Feedback/issues/220     
@leoyejl

**Comment by leoyejl** [comment]
确实是这个原因，一开始没看到反馈是提到 issue 里面来的，不然搜一下就行了。
