### ISSUE TITLE
watch设定必须用网页打开

### ISSUE THREAD

**Issue by nzcool** [PPHubApp/PPHub-Feedback#505]
个人选项中没有watchs需要点开后才能找到watchs

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by jkpang** [comment]
你好，Watch仓库点击仓库详情页，右下角菜单按钮，弹窗中的第一个按钮就可以操作了。
![IMG_BE0305FD7F57-1](https://user-images.githubusercontent.com/17583451/70897788-4ebfd280-202e-11ea-813e-358e96d4c9b4.jpeg)
@nzcool
