### ISSUE TITLE
v2.2.0.151 - 点击打开某些文件会提示“请求数据错误”，...

### ISSUE THREAD

**Issue by Alex1990** [PPHubApp/PPHub-Feedback#507]
点击打开某些文件会提示“请求数据错误”，几户每个仓库都发生

运行环境: iPhone11 Pro - iOS13.2.3 - v2.2.0(151)

**Comment by jkpang** [comment]
代码文件的数据是从 https://raw.githubusercontent.com 获取的，最近几个月在国内的网络环境访问此域名不稳定，有条件可以用梯子。 @Alex1990

**Comment by Alex1990** [comment]
好的
