### ISSUE TITLE
v2.2.0.151 - news界面无法显示内容，刷新无效。

### ISSUE THREAD

**Issue by ParkerGong** [PPHubApp/PPHub-Feedback#508]
运行环境: iPhone 8 Plus - iOS13.3 - v2.2.0(151)

**Comment by jkpang** [comment]
您好，如果提示“没有请求到数据”，可能是因为您的GitHub账号：

- 没有Follow任何用户或您Follow的用户没有相关动态
- 没有Watch任何代码库或您Watch的代码库没有相关动态
- 其他用户没有对您的公开代码库提出Issues或者Pull request     
      
@ParkerGong
