### ISSUE TITLE
不可以下载代码吗？

### ISSUE THREAD

**Issue by asdf2014** [PPHubApp/PPHub-Feedback#509]

**Comment by jkpang** [comment]
你好，PPHub不支持下载代码。不过可以配合Working Copy使用。 @asdf2014 
![DBEE442E-A706-4134-9443-2745CD3C4731](https://user-images.githubusercontent.com/17583451/71305484-f1ea6080-240f-11ea-97b1-28e7eb211156.jpeg)

**Comment by asdf2014** [comment]
Working Copy 不好用… Two-factor authentication 开启后没法 push 代码

**Comment by asdf2014** [comment]
看来是我不会用，可以了，谢谢
