### ISSUE TITLE
点击文件看不到代码，说请求数据错误，但是错误原因是啥看不到

### ISSUE THREAD

**Issue by asdf2014** [PPHubApp/PPHub-Feedback#510]
![7CC0239C-1F36-40CE-8556-8981FB4436EC](https://user-images.githubusercontent.com/8108788/71305017-e6476b80-2408-11ea-8d85-f8052403874b.png)

![EB48A7CB-3764-402D-A332-370D7C7992E5](https://user-images.githubusercontent.com/8108788/71305050-53f39780-2409-11ea-8d83-38655e9daf40.png)

**Comment by jkpang** [comment]
你好，代码文件的数据是从 https://raw.githubusercontent.com 获取的，最近几个月在国内的网络环境访问此域名不稳定，有条件可以用梯子  @asdf2014

**Comment by asdf2014** [comment]
虽然不知道梯子是什么，但还是谢谢你
