### ISSUE TITLE
v2.2.0.151 - 貌似现在 Trending 功能不能选择...

### ISSUE THREAD

**Issue by asdf2014** [PPHubApp/PPHub-Feedback#513]
貌似现在 Trending 功能不能选择多种语言，不知道能否支持一下，看到 github 上搜索是可以多选的

运行环境: iPhone11 Pro - iOS13.3 - v2.2.0(151)

**Comment by jkpang** [comment]
你好，支持多种语言的，在Trending界面点击右上角筛选按钮，即可选择不通种类的编程语言分类 @asdf2014

**Comment by asdf2014** [comment]
难道是我用得不对… 貌似不能同时选择多个语言吧，比如 java 和 python 一起选，貌似不行

**Comment by jkpang** [comment]
> 难道是我用得不对… 貌似不能同时选择多个语言吧，比如 java 和 python 一起选，貌似不行

明白你的意思了。Tending 目前只能单选一种编程语言的来查看其数据，目前官网也只能选一种吧。

**Comment by asdf2014** [comment]
哦哦 好吧 谢谢
