### ISSUE TITLE
v2.2.0.151 - news  stars什么都不显示，刷新...

### ISSUE THREAD

**Issue by Penguin-SAMA** [PPHubApp/PPHub-Feedback#515]
news  stars什么都不显示，刷新也刷不出来

运行环境: iPhone11 Pro Max - iOS13.3.1 - v2.2.0(151)

**Comment by jkpang** [comment]
你好，如果提示“没有请求到数据”，可能是因为您的GitHub账号：

- 没有Follow任何用户或您Follow的用户没有相关动态
- 没有Watch任何代码库或您Watch的代码库没有相关动态
- 其他用户没有对您的公开代码库提出Issues或者Pull request         

Star列表需要对仓库star操作后才会有显示  @Penguin-SAMA
