### ISSUE TITLE
v2.2.0.151 - 代码报错，请求数据出错

### ISSUE THREAD

**Issue by AdvancingStone** [PPHubApp/PPHub-Feedback#517]
运行环境: iPhone 8 Plus - iOS11.3.1 - v2.2.0(151)

**Comment by jkpang** [comment]
代码文件的数据是从 https://raw.githubusercontent.com 获取的，最近几个月在国内的网络环境访问此域名不稳定，用梯子可以根治此问题（唉，国内的网络环境是硬伤） @AdvancingStone
