### ISSUE TITLE
v2.2.0.151 - 目前GitHub trending增加了...

### ISSUE THREAD

**Issue by yihong0618** [PPHubApp/PPHub-Feedback#518]
目前GitHub trending增加了，语言筛选，作者会考虑增加么？非常感谢带来这么好用的客户端。

运行环境: iPhone XR - iOS13.3 - v2.2.0(151)

**Comment by jkpang** [comment]
最新版已支持“交流语言”筛选，抱歉鸽了这么久 @yihong0618
