### ISSUE TITLE
v2.2.0.151 - 我在github上更新头像，本地还没刷新

### ISSUE THREAD

**Issue by FaithZL** [PPHubApp/PPHub-Feedback#522]
运行环境: iPhone SE - iOS12.4.1 - v2.2.0(151)

**Comment by jkpang** [comment]
你好，前后端都有缓存（GitHub在国内网络环境下访问的表现，会有一定的延时，你懂的），可退出App或清理缓存再试。 @FaithZL

**Comment by FaithZL** [comment]
清理缓存可以了
