### ISSUE TITLE
v2.2.0.151 - 打不开代码，request data e...

### ISSUE THREAD

**Issue by Heath1210** [PPHubApp/PPHub-Feedback#526]
打不开代码，request data error

Environment: iPad Pro 10.5 Inch - iOS13.3 - v2.2.0(151)

**Comment by jkpang** [comment]
你好，是国内的网络问题，具体原因：#517 @Heath1210

**Comment by jkpang** [comment]
v2.2.2已更新，已修复此问题 @Heath1210
