### ISSUE TITLE
v2.2.0.151 - 怎么不能fork github仓库阿
还...

### ISSUE THREAD

**Issue by c0pyninj4** [PPHubApp/PPHub-Feedback#530]
怎么不能fork github仓库阿
还有就是
我创建的组织怎么也看不到啊

运行环境: iPhone SE - iOS13.3 - v2.2.0(151)

**Comment by jkpang** [comment]
你好: 
Fork仓库：仓库详情页-右下角菜单按钮-点击Fork按钮即可
组织：目前只能查看用户写在“ Company”那一栏的组织
 @n07hin9
