### ISSUE TITLE
v2.2.0.151 - 请求数据错误！
越来越多的情况下发现请求...

### ISSUE THREAD

**Issue by Bian-Sh** [PPHubApp/PPHub-Feedback#531]
请求数据错误！
越来越多的情况下发现请求数据错误，下面的链接就存在这个问题

https://github.com/Kink3d/kPooling/blob/master/Tests/Editor/ProcessorTests.cs

运行环境: iPhone X - iOS13.3 - v2.2.0(151)

**Comment by jkpang** [comment]
你好，是国内的网络问题，具体原因：#517 @Bian-Sh

**Comment by jkpang** [comment]
v2.2.2已更新，已优化此问题 @Bian-Sh
