### ISSUE TITLE
v2.2.1.153 - 查看代码源文件会出现  '请求数据错误'

### ISSUE THREAD

**Issue by AlanAlbert** [PPHubApp/PPHub-Feedback#533]
运行环境: iPhone XS Max - iOS13.3 - v2.2.1(153)

**Comment by jkpang** [comment]
你好，是国内的网络问题，具体原因：#517 @AlanAlbert

**Comment by jkpang** [comment]
v2.2.2已更新，已优化此问题 @AlanAlbert
