### ISSUE TITLE
v2.2.1.153 - 之前一直是 Android 用户，换了 ...

### ISSUE THREAD

**Issue by rsyhan** [PPHubApp/PPHub-Feedback#534]
之前一直是 Android 用户，换了 iOS之后发现Github 客户端如此之少。找到 PPHub 后很喜欢，界面比较好看。下面反馈一下我个人的一些意见
因为之前是 Android 用户，使用的是 Fasthub，所以换回来时不太适应。具体体现在：
Fasthub 可以看单独的commit，包括复制提交的 Git SHA1（因为我们在 cherry-pick 、revert的时候经常用到），而PPHub则需要进入commit页面，看着GitHub的电脑界面，费劲的复制一下 SHA1，再换下一条提交
希望看repo commits提交的时候，更换一下布局，如果每一条commit都显示所有commit comment的话，您可以看看 Linux 的commit，有些提交都有很多信息，包括崩溃的一些日志，这样如果想找一个commit，难度大大加大
所以我建议有一些方案，可以参考一下 Android 端的 Fasthub，这个软件对 Github 客户端做的很到位了。当然您的产品动画、界面非常值得肯定👍感谢开发者

运行环境: iPhone11 Pro Max - iOS13.3 - v2.2.1(153)

**Comment by jkpang** [comment]
v2.3.0已可更新 @rsyhan
