### ISSUE TITLE
v2.2.1.153 - 系统切换粗体字时共享弹出菜单时’PPHu...

### ISSUE THREAD

**Issue by OOXXXX** [PPHubApp/PPHub-Feedback#535]
系统切换粗体字时共享弹出菜单时’PPHub’五个字仍是细体 强迫症患者看着很不舒服 另外 希望添加explore版块 并跟搜索功能合并 毕竟搜索如果什么都不输显得比较唐突（ 一点建议 望参考 谢谢）

Environment: iPhone XS - iOS13.3 - v2.2.1(153)

**Comment by jkpang** [comment]
> 系统切换粗体字时共享弹出菜单时’PPHub’五个字仍是细体 强迫症患者看着很不舒服 另外 希望添加explore版块 并跟搜索功能合并 毕竟搜索如果什么都不输显得比较唐突（ 一点建议 望参考 谢谢）
> 
> Environment: iPhone XS - iOS13.3 - v2.2.1(153)

苹果没有开放出修改 ”系统共享菜单的字体“的Api，应该是有系统接管的。
