### ISSUE TITLE
v2.2.1.153 - 访问代码  经常请求出错

### ISSUE THREAD

**Issue by lizhi-shenghuo** [PPHubApp/PPHub-Feedback#537]
运行环境: iPad 6 - iOS13.2 - v2.2.1(153)

**Comment by jkpang** [comment]
你好，是国内的网络问题，具体原因：#517  @lizhi-shenghuo

**Comment by jkpang** [comment]
v2.2.2已更新，已优化此问题 @lizhi-shenghuo
