### ISSUE TITLE
v2.2.1.153 - 服务器是放到国外吗？每次加载太慢了，开V...

### ISSUE THREAD

**Issue by ckjbug** [PPHubApp/PPHub-Feedback#538]
服务器是放到国外吗？每次加载太慢了，开VPN才用得下去！

运行环境: iPhone 7 Plus - iOS13.3 - v2.2.1(153)

**Comment by jkpang** [comment]
你好，PPHub全是使用的GitHub官方开放的API。加载速度慢是因为GitHub在国内DNS被污染的原因，特别是在电信的网络环境下最为严重。在不开VPN的情况下，我使用联通4g 或 移动宽带的网络，最好的情况可以达到秒开的效果。 @ckjbug

**Comment by jkpang** [comment]
v2.2.2已更新，已优化此问题 @ckjbug
