### ISSUE TITLE
v2.2.1.153 - 请求数据出错，真是坑人

### ISSUE THREAD

**Issue by mxz1994** [PPHubApp/PPHub-Feedback#541]
运行环境: iPad Air 2 - iOS12.1.4 - v2.2.1(153)

**Comment by jkpang** [comment]
你好，是国内的网络问题，GitHub请求原始文件的Api域名DNS污染严重，在电信的网络环境下尤其突出，建议有条件可以开启VPN，或者使用除电信以外的网络，我会持续跟进这个问题，寻找更完美的解决方案 @mxz1994

**Comment by dawnlh** [comment]
> 你好，是国内的网络问题，GitHub请求原始文件的Api域名DNS污染严重，在电信的网络环境下尤其突出，建议有条件可以开启VPN，或者使用除电信以外的网络，我会持续跟进这个问题，寻找更完美的解决方案 @mxz1994

这个问题希望老板能好好解决下，不然看不到文件这就没法用了啊 ，感谢

**Comment by jkpang** [comment]
v2.2.2已更新，已优化此问题 @mxz1994 @dawnlh
