### ISSUE TITLE
v2.2.1.153 - 查看yml文件时，一直提示“请求错误数据...

### ISSUE THREAD

**Issue by dy20082250** [PPHubApp/PPHub-Feedback#542]
查看yml文件时，一直提示“请求错误数据”，这个现象很频繁。但是也有正常的时候

运行环境: iPad Pro 11 Inch - iOS13.3 - v2.2.1(153)

**Comment by dawnlh** [comment]
同 看其他文件也会遇到 比如 Python或者MATLAB

**Comment by jkpang** [comment]
v2.2.2已更新，已优化此问题，原因是：#541   @dy20082250 @dawnlh
