### ISSUE TITLE
v2.2.2.156 - 经常请求错误

### ISSUE THREAD

**Issue by qrzeng** [PPHubApp/PPHub-Feedback#549]
运行环境: iPad Mini 4 - iOS13.3.1 - v2.2.2(156)

**Comment by jkpang** [comment]
你好，因为PPHub全部使用的是GitHub官方开放Api，GitHub在国内的网络环境下一直存在DNS被污染的问题。可能目前“污染”的更严重了吧。通过测试，在联通、移动网络环境下，会有比较好的表现，在电信环境下，影响最为严重。如果有条件，使用V*P**N工具会获得完美体验。。。

**Comment by qrzeng** [comment]
是的，后来科学上网就好多了，我觉得应该换个提示好一点，网络问题还是提示网络问题，不然还以为软件不好



---原始邮件---
发件人: "jkpang"<notifications@github.com&gt;
发送时间: 2020年2月24日(周一) 晚上8:58
收件人: "PPHubApp/PPHub-Feedback"<PPHub-Feedback@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"zqr"<892880500@qq.com&gt;;
主题: Re: [PPHubApp/PPHub-Feedback] v2.2.2.156 - 经常请求错误 (#549)



你好，因为PPHub全部使用的是GitHub官方开放Api，GitHub在国内的网络环境下一直存在DNS被污染的问题。可能目前“污染”的更严重了吧。通过测试，在联通、移动网络环境下，会有比较好的表现，在电信环境下，影响最为严重。如果有条件，使用V*P**N工具会获得完美体验。。。

**Comment by jkpang** [comment]
> 是的，后来科学上网就好多了，我觉得应该换个提示好一点，网络问题还是提示网络问题，不然还以为软件不好


这个条件无法准确判断哦！如果在这种情况下提示网络问题，但是其他App能正常联网使用，那用户还是觉得PPHub不行😂
