### ISSUE TITLE
v2.2.2.156 - 经常请求数据错误

### ISSUE THREAD

**Issue by Buzhisuocuopanda** [PPHubApp/PPHub-Feedback#551]
运行环境: iPad 6 - iOS13.3.1 - v2.2.2(156)

**Comment by jkpang** [comment]
你好，因为PPHub全部使用的是GitHub官方开放Api，GitHub在国内的网络环境下一直存在DNS被污染的问题。可能目前“污染”的更严重了吧。通过测试，在联通、移动网络环境下，会有比较好的表现，在电信环境下，影响最为严重。如果有条件，使用V*P**N工具会获得完美体验。。。
