### ISSUE TITLE
v2.2.2.156 - 请问怎么查询所有Java语言的仓库 我发...

### ISSUE THREAD

**Issue by qiuzefan** [PPHubApp/PPHub-Feedback#556]
请问怎么查询所有Java语言的仓库 我发现只要在搜索框输入关键字才能查询 然而我就想看看这个语言star最多的项目

运行环境: iPhone XR - iOS13.3 - v2.2.2(156)

**Comment by jkpang** [comment]
你好，目前只能通过关键字进行检索相关仓库； @qiuzefan
