### ISSUE TITLE
v2.2.2.156 - 代码阅读时能否加入横屏查看功能 并且可以...

### ISSUE THREAD

**Issue by qiuzefan** [PPHubApp/PPHub-Feedback#557]
代码阅读时能否加入横屏查看功能 并且可以左右拖动

运行环境: iPhone XR - iOS13.3 - v2.2.2(156)

**Comment by jkpang** [comment]
你好，解锁手机横竖屏锁定，旋转手机就可以横屏了 @qiuzefan
