### ISSUE TITLE
v2.3.0 - 发生SSL错误，无法连接服务器

### ISSUE THREAD

**Issue by airacoon** [PPHubApp/PPHub-Feedback#563]
运行环境: iPhone 7 - iOS13.3.1 - v2.3.0(161)

**Comment by jkpang** [comment]
你好，最近一个月，有用户反馈经常出现“请求数据错误”、“无法连接服务器”的问题。PPHub使用的是100% GitHub官方开放Api。众所周知，GitHub在国内受到一直受到DNS污染，导致访问速度很慢。不知道为啥，这段时间“好像”被污染得更严重了，所以才会出现这样的问题。。。
以下为解决方案：
1、使用联通、移动手机网络，不要使用宽带或电信网络（不完美解决）；
2、有条件的童鞋可以使用科学上网（完美解决）。       
@airacoon
