### ISSUE TITLE
v2.3.0 - 无法显示非utf-8的中文文件

### ISSUE THREAD

**Issue by wangfanstar** [PPHubApp/PPHub-Feedback#564]
运行环境: iPad Pro 12.9 Inch 2 - iOS13.3.1 - v2.3.0(161)

**Comment by jkpang** [comment]
因为有些代码文件的文本编码不是utf8，在iOS平台将文本转码到utf8失败了，所以才显示不出。这个问题一直在寻找可行的解决方案，暂时只能通过网页查看编码失败的文件了
