### ISSUE TITLE
v2.3.0 - 体验很好 ，可以开发登录，Gitlab么...

### ISSUE THREAD

**Issue by LANCEREN** [PPHubApp/PPHub-Feedback#567]
体验很好 ，可以开发登录，Gitlab么？很期待

运行环境: iPhone11 Pro Max - iOS13.3.1 - v2.3.0(161)

**Comment by jkpang** [comment]
感谢您对PPHub的评价，GitLab暂时不会考虑了，以后再找机会😂 @LANCEREN

**Comment by LANCEREN** [comment]
好的感谢




在2020年03月12日 10:29，jkpang 写道：

感谢您对PPHub的评价，GitLab暂时不会考虑了，以后再找机会😂@LANCEREN
