### ISSUE TITLE
v2.3.0 - markown里面链接不能跳转

### ISSUE THREAD

**Issue by wangsiji** [PPHubApp/PPHub-Feedback#569]
运行环境: iPad Air 3 - iOS13.3.1 - v2.3.0(161)

**Comment by jkpang** [comment]
你好，方便贴一下这个MarkDown的链接吗 @wangsiji

**Comment by wangsiji** [comment]
仓库如果是Private，markdown不能跳转。转为公开，可以跳转

**Comment by jkpang** [comment]
应该是Cookie失效了，退出重新授权登录就行（如果直接使用Token登录不行） @wangsiji
