### ISSUE TITLE
v2.3.0 - 仓库分享（微信)时导致软件卡死 关闭重启...

### ISSUE THREAD

**Issue by jhonconal** [PPHubApp/PPHub-Feedback#573]
仓库分享（微信)时导致软件卡死 关闭重启正常再次分享依然卡死

运行环境: iPhone XS Max - iOS13.3.1 - v2.3.0(161)

**Comment by jkpang** [comment]
你好，PPHub使用的是iOS系统分享，卡死的问题应该是微信share extention造成的  @jhonconal
