### ISSUE TITLE
v2.3.0 - 项目不更新了，无法与电脑同步

### ISSUE THREAD

**Issue by liuminchao123** [PPHubApp/PPHub-Feedback#578]
运行环境: iPad 6 - iOS13.3.1 - v2.3.0(161)

**Comment by jkpang** [comment]
是说的handoff-接力吗？ 是在哪个界面不同步的？手机和Mac打开了蓝牙吗 @liuminchao123

**Comment by liuminchao123** [comment]
在电脑上的项目，git到GitHub后，在电脑端可以看到，PPhub上显示SSH错误，无法显示git的项目

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: jkpang <notifications@github.com>
发送时间: Saturday, March 28, 2020 1:18:33 PM
收件人: PPHubApp/PPHub-Feedback <PPHub-Feedback@noreply.github.com>
抄送: liuminchao123 <Mr.liuminchao@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [PPHubApp/PPHub-Feedback] v2.3.0 - 项目不更新了，无法与电脑同步 (#578)


是说的handoff-接力吗？ 是在哪个界面不同步的？手机和Mac打开了蓝牙吗 @liuminchao123<https://github.com/liuminchao123>
