### ISSUE TITLE
v2.3.1 - star 按钮偶现不正常，见下图

### ISSUE THREAD

**Issue by qiuncheng** [PPHubApp/PPHub-Feedback#582]
运行环境: iPhone X - iOS13.4 - v2.3.1(163)

**Comment by qiuncheng** [comment]
![image](https://user-images.githubusercontent.com/9990834/78366782-9a08eb80-75f3-11ea-95b5-1df017b52d2e.png)

**Comment by jkpang** [comment]
你好，有没有稳定的复现路径 @qiuncheng

**Comment by qiuncheng** [comment]
只出现一次，后来没有复现了

发自我的iPhone

**Comment by jkpang** [comment]
嗯嗯，我这边也没有复现，我再找找原因

**Comment by jkpang** [comment]
v2.3.2已上线，已尝试修复此问题 @qiuncheng

**Comment by qiuncheng** [comment]
👍

发自我的iPhone
