### ISSUE TITLE
v2.3.1 - 文本转换为uft-8失败？

### ISSUE THREAD

**Issue by PufeiLi** [PPHubApp/PPHub-Feedback#586]
运行环境: iPad Air 3 - iOS13.4 - v2.3.1(163)

**Comment by PufeiLi** [comment]
打开自己仓库的.m文件，显示文本转换为uft-8失败是什么意思？

**Comment by jkpang** [comment]
因为有些代码文件的文本编码不是utf8，在iOS平台将文本转码到utf8失败了，所以才显示不出。这个问题一直在寻找可行的解决方案，暂时只能通过网页查看编码失败的文件了。 @PufeiLi
