### ISSUE TITLE
v2.3.2 - 小组件中的contributions显示...

### ISSUE THREAD

**Issue by SomnambulistL** [PPHubApp/PPHub-Feedback#595]
小组件中的contributions显示有问题
只能看到右上角一个小绿点...

运行环境: iPhone11 - iOS13.3.1 - v2.3.2(166)

**Comment by jkpang** [comment]
![image](https://user-images.githubusercontent.com/17583451/81528142-999c0700-938e-11ea-8f71-0d3710cbed94.png)
可以cha查看网页中的Private contributions是否已勾选  @SomnambulistL

**Comment by SomnambulistL** [comment]
OK, 勾选后可以正常显示，之前误以为有问题是因为组件会闪一下全部的然后再消失掉~
