### ISSUE TITLE
v2.3.2 - 在开启VPN翻墙的情况下依然无法读取Re...

### ISSUE THREAD

**Issue by ylqylq001** [PPHubApp/PPHub-Feedback#598]
在开启VPN翻墙的情况下依然无法读取Repo中的Readme，有时无法读取Commit修改的内容。

运行环境: iPhone X - iOS13.4.1 - v2.3.2(166)

**Comment by jkpang** [comment]
是查看私有库的Readme和Commit吗？那应该是Cookie失效，重新登录下就好了 @ylqylq001

**Comment by ylqylq001** [comment]
> 是查看私有库的Readme和Commit吗？那应该是Cookie失效，重新登录下就好了 @ylqylq001

谢谢，已经解决！
