### ISSUE TITLE
v2.4.0 - 要是能保持到本地看就好了，虽然这种情况很...

### ISSUE THREAD

**Issue by Keronaya** [PPHubApp/PPHub-Feedback#607]
要是能保持到本地看就好了，虽然这种情况很少

运行环境: iPad Pro 10.5 Inch - iOS13.5 - v2.4.0(167)

**Comment by jkpang** [comment]
仓库详情页-右下角菜单按钮-菜单滑动至第二页-使用Working Copy 下载代码仓库保存 @Keronaya
