### ISSUE TITLE
v2.4.2 - 有的readme会浏览器跳转？为什么？是...

### ISSUE THREAD

**Issue by F7ionsy** [PPHubApp/PPHub-Feedback#618]
有的readme会浏览器跳转？为什么？是api不支持吗？

运行环境: iPhone XR - iOS13.5.1 - v2.4.2(172)

**Comment by jkpang** [comment]
更新下 v2.6.0 试试，现在点击 readme 里的超链标题，可以在本界面滚动至指定位置了 @F7ionsy
