### ISSUE TITLE
v2.4.2 - 我有用github issues私密仓库...

### ISSUE THREAD

**Issue by yihong0618** [PPHubApp/PPHub-Feedback#620]
我有用github issues私密仓库写日记的习惯。
并且我会把issues整理在readme中，方便直接打开
但是用pphub直接点击readme中issue的链接报404
猜测是没带token请求，麻烦作者帮看一下
![image](https://user-images.githubusercontent.com/15976103/86200324-e7630d80-bb8e-11ea-99d9-e851872336bb.png)
![image](https://user-images.githubusercontent.com/15976103/86200331-eaf69480-bb8e-11ea-8384-e0511fe74222.png)

运行环境: iPhone XR - iOS13.5.1 - v2.4.2(172)

**Comment by jkpang** [comment]
是的，这是没有带Token导致的。
**解决方案：** 在Safari浏览器中登录GitHub账号，在PPHub中就可以查看Readme的外链了。
**原因：** 加载Readme中的外链使用了系统SFSafariViewController，SFSafariViewController没有提供添加Cookie的Api，但是可以和Safari共享Cookie。

@yihong0618

**Comment by yihong0618** [comment]
@jkpang 收到，感谢。
