### ISSUE TITLE
v2.4.3 - 为什么我的提交数日历图和github的不...

### ISSUE THREAD

**Issue by skykiseki** [PPHubApp/PPHub-Feedback#625]
为什么我的提交数日历图和github的不一致呢？是因为我的仓库都是私有的导致的吗

运行环境: iPhone 8 Plus - iOS12.4.1 - v2.4.3(175)

**Comment by jkpang** [comment]
需要到官网勾选私有库提交对外可见；
![image](https://user-images.githubusercontent.com/17583451/87849327-51630d00-c91a-11ea-8be6-8914eb9919a4.png)
