### ISSUE TITLE
v2.4.3 - 每个仓库readme怎么都会显示网页的t...

### ISSUE THREAD

**Issue by lowking** [PPHubApp/PPHub-Feedback#626]
每个仓库readme怎么都会显示网页的tab栏（code，issue，pull request，action那栏）？

运行环境: iPhone XS - iOS14.0 - v2.4.3(175)

**Comment by jkpang** [comment]
此问题已修复，如果有条件，可以打开VPN后重启App即可解决。
如果没有，PPHub新版本已提交审核，不出意外明天即可获取更新。 @lowking
