### ISSUE TITLE
v2.4.6 - 切换分支无效

### ISSUE THREAD

**Issue by Edger** [PPHubApp/PPHub-Feedback#630]
运行环境: iPhone11 - iOS13.6 - v2.4.6(178)

**Comment by Edger** [comment]
可以确认代理是没有问题的。

我用了其他两款 GitHub 客户端都是可以正常切换分支的，但是 PPhub 不行。

**Comment by Teemwu** [comment]
+1

**Comment by Edger** [comment]
提 bug 都没动静的？不能切换分支很影响使用啊，能不能学学隔壁的 Coderx 。。。。。。。

**Comment by jkpang** [comment]
> 提 bug 都没动静的？不能切换分支很影响使用啊，能不能学学隔壁的 Coderx 。。。。。。。

抱歉抱歉，因为工作忙，这个issue被堆积在下面没有注意到。我刚刚使用App Store最新版本v2.4.7切换分支后，查看README和仓库文件都是没问题的，请问你切换分支后，是查看什么内容不生效？
@Edger

**Comment by Edger** [comment]
> > 提 bug 都没动静的？不能切换分支很影响使用啊，能不能学学隔壁的 Coderx 。。。。。。。
> 
> 抱歉抱歉，因为工作忙，这个issue被堆积在下面没有注意到。我刚刚使用App Store最新版本v2.4.7切换分支后，查看README和仓库文件都是没问题的，请问你切换分支后，是查看什么内容不生效？
> @Edger

仓库文件正常，README 显示不正常，例如这个仓库 [nzw9314](https://github.com/nzw9314/QuantumultX)，打开后默认是 Ov 分支，接着第一次切换到 master 分支，README 刷不出来。然后在 Ov 和 master 之间多切换几次，README 就反着显示了，Ov 分支显示 master 分支的 README，master 分支显示 Ov 分支的 README。

**Comment by jkpang** [comment]
好的，我已复现了这个问题，这周末我会尽快修复这个问题并上线，感谢反馈 @Edger @Teemwu

**Comment by jkpang** [comment]
v2.4.8已可更新 @Teemwu @Edger

**Comment by Edger** [comment]
> v2.4.8已可更新 @Teemwu @Edger

已下载，使用正常了。辛苦了，谢谢 👍
