### ISSUE TITLE
v2.4.6 - 经常出现网络连接失败。不知道是啥情况。体...

### ISSUE THREAD

**Issue by hellomrbai** [PPHubApp/PPHub-Feedback#631]
经常出现网络连接失败。不知道是啥情况。体验不太友好。

运行环境: iPhone X - iOS13.3.1 - v2.4.6(178)

**Comment by jkpang** [comment]
是Github Api的问题，详细原因：https://github.com/PPHubApp/PPHub-Feedback/issues/611

@hellomrbai
