### ISSUE TITLE
v2.4.6 - 无法查看commit
视频文件地址

h...

### ISSUE THREAD

**Issue by fandongtongxue** [PPHubApp/PPHub-Feedback#637]
无法查看commit
视频文件地址

https://cloud.189.cn/t/mqAJzuqeuyUr

运行环境: iPhone 7 Plus - iOS14.0 - v2.4.6(178)

**Comment by jkpang** [comment]
是私有库吗？如果是，可以退出登录，再使用账号重新登录一下就可以了（Cookie失效） @fandongtongxue

**Comment by fandongtongxue** [comment]
ok
