### ISSUE TITLE
v2.4.6 - News 一直网络错误，打不开，翻墙也没...

### ISSUE THREAD

**Issue by lester-learner** [PPHubApp/PPHub-Feedback#638]
News 一直网络错误，打不开，翻墙也没东西，空白

运行环境: iPhone X - iOS13.6 - v2.4.6(178)

**Comment by jkpang** [comment]
空白的原因是你的账号没有Follow其它用户、Watch其它仓库，或者你Follow、Watch的用户和仓库没有动态 @lester-learner
