### ISSUE TITLE
v2.4.7 - 在浏览GitHub上带目录的内容时，点击...

### ISSUE THREAD

**Issue by fremakvi** [PPHubApp/PPHub-Feedback#640]
在浏览GitHub上带目录的内容时，点击超链接会新开一个网页而非自动跳转。
同理，项目中的所有超链接都以网页形式打开而非pphub的跳转。
然而，使用网页访问GitHub中的内容是相当缓慢的。因此，希望开发者能在用户点击超链接后先看看是不是GitHub本站内容，如果是则用pphub直接跳转而非打开网页。
谢谢。

运行环境: iPad Air 3 - iOS13.6 - v2.4.7(180)

**Comment by jkpang** [comment]
如果超链是“仓库”和“用户”，会跳转至原生的详情页，否则会打开网页。 @fremakvi

**Comment by jkpang** [comment]
更新下 v2.6.0 试试， 经过攻坚，在 readme 点击标题超链会在本界面滚动指定位置了 @fremakvi
