### ISSUE TITLE
v2.4.7 - contribute 日历显示不正常。没...

### ISSUE THREAD

**Issue by nateInChina** [PPHubApp/PPHub-Feedback#642]
contribute 日历显示不正常。没法更新。 打开app后再关屏看一下。会短暂更新一下，然后又恢复几天前的状态（就是闪一下最新状态而已）

运行环境: iPhone X - iOS13.6.1 - v2.4.7(180)

**Comment by jkpang** [comment]
你好，卸载重装试试？可能犹豫版本更新缓存不一致导致的。 @nateInChina

**Comment by jkpang** [comment]
有没有勾选网页版的`私有库提交对外可见`的选项？
![image](https://user-images.githubusercontent.com/17583451/91113269-bb0fcd00-e6b7-11ea-9554-bc3a0a0e50db.png)

**Comment by nateInChina** [comment]
@jkpang 确实是这个问题，多谢
