### ISSUE TITLE
v2.4.7 - 你好，在项目主页的右下角有的小圆圈，点了...

### ISSUE THREAD

**Issue by iccy-code** [PPHubApp/PPHub-Feedback#643]
你好，在项目主页的右下角有的小圆圈，点了后会有其他几个选项可以点，但是每次点了这个小圆圈都会有一段动画，可以让这个动画出现一次吗，之后就不出现这段动画了

运行环境: iPhone 7 - iOS12.0 - v2.4.7(180)

**Comment by jkpang** [comment]
这个动画是告诉用户左滑有更多菜单，一共会出现3次，因为之前有许多用户不知道还可以左滑查看更多
