### ISSUE TITLE
v2.4.7 - 希望可以缓存整个项目代码

### ISSUE THREAD

**Issue by royluo1984** [PPHubApp/PPHub-Feedback#649]
运行环境: iPad Pro 11 Inch - iOS12.1.1 - v2.4.7(180)

**Comment by jkpang** [comment]
可以使用Working Copy缓存，打开路径：仓库详情页 -->右下角菜单 -->左滑至第二页 --> 点击Working Copy    @royluo1984

**Comment by royluo1984** [comment]
苹果版的app好像没有这些选项
