### ISSUE TITLE
v2.4.7 - 关于 ticket 	649
我没有找到...

### ISSUE THREAD

**Issue by royluo1984** [PPHubApp/PPHub-Feedback#650]
关于 ticket 	649
我没有找到 仓库详情页 这个界面

运行环境: iPad Pro 11 Inch - iOS12.1.1 - v2.4.7(180)

**Comment by jkpang** [comment]
这个是仓库详情页： @royluo1984 
![IMG_38E1827B77B9-1](https://user-images.githubusercontent.com/17583451/92370803-5cbe0200-f12d-11ea-9a1f-9a0adca77f1f.jpeg)
