### ISSUE TITLE
v2.4.7 - 可以缓存代码么

### ISSUE THREAD

**Issue by qisikai** [PPHubApp/PPHub-Feedback#651]
运行环境: iPad Mini 5 - iOS13.6.1 - v2.4.7(180)

**Comment by PK-Patomsiri** [comment]
> 运行环境: iPad Mini 5 - iOS13.6.1 - v2.4.7(180)

**Comment by jkpang** [comment]
可以使用Working Copy缓存，使用路径：仓库详情页 -- 右下角菜单 -- 左滑至第二页 -- 点击Working Copy @qisikai
