### ISSUE TITLE
v2.4.7 - “文本转换为UTF8编码时失败”
当代码...

### ISSUE THREAD

**Issue by YunLambert** [PPHubApp/PPHub-Feedback#653]
“文本转换为UTF8编码时失败”
当代码中含有中文的时候，无法查看线上代码；虽然提供了前往网页查看的功能，但是如果是自己私有仓库的话需要登录才能查看；会略显不方便。
能否支持UTF8编码的解析功能？

运行环境: iPhone11 - iOS13.5.1 - v2.4.7(180)

**Comment by jkpang** [comment]
> “文本转换为UTF8编码时失败”
> 当代码中含有中文的时候，无法查看线上代码；虽然提供了前往网页查看的功能，但是如果是自己私有仓库的话需要登录才能查看；会略显不方便。
> 能否支持UTF8编码的解析功能？
> 
> 运行环境: iPhone11 - iOS13.5.1 - v2.4.7(180)

其它编码的文本转化为iOS平台所需UTF-8失败的问题，直到目前还没有找到解决方案，如果日后找到，会第一时间更新！

**Comment by jkpang** [comment]
最新版优化了这个问题，现在应该不会报这个错误了
