### ISSUE TITLE
项目内跳转问题

### ISSUE THREAD

**Issue by Lauv-who** [PPHubApp/PPHub-Feedback#654]
希望可以直接在app内向下方跳转，不要另开个网页转到跳转的地方，可能我说的不清楚，你看下这个项目：
https://github.com/kon9chunkit/GitHub-Chinese-Top-Charts 

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by jkpang** [comment]
> 希望可以直接在app内向下方跳转，不要另开个网页转到跳转的地方，可能我说的不清楚，你看下这个项目：
> https://github.com/kon9chunkit/GitHub-Chinese-Top-Charts
> 
> Sent from [PPHub](https://apps.apple.com/cn/app/id1314212521)

这个链接我测试了，在PPHub内部是可以被识别为一个仓库，然后跳转至原生界面的，请问你使用的PPHub版本是？ @Lauv-who

**Comment by Lauv-who** [comment]
> > 希望可以直接在app内向下方跳转，不要另开个网页转到跳转的地方，可能我说的不清楚，你看下这个项目：
> > https://github.com/kon9chunkit/GitHub-Chinese-Top-Charts
> > Sent from [PPHub](https://apps.apple.com/cn/app/id1314212521)
> 
> 这个链接我测试了，在PPHub内部是可以被识别为一个仓库，然后跳转至原生界面的，请问你使用的PPHub版本是？ @Lauv-who

2.4.9
