### ISSUE TITLE
v2.4.9 - 希望添加主题固定的设置，现在每次进入ap...

### ISSUE THREAD

**Issue by faimin** [PPHubApp/PPHub-Feedback#656]
希望添加主题固定的设置，现在每次进入app都是浅色主题

运行环境: iPhone 6s Plus - iOS13.7 - v2.4.9(186)

**Comment by jkpang** [comment]
现在的逻辑是选中主题后，在本地会记住，下次进来还是上次选中的主题，不会重置的。你这边是怎么复现的？ @faimin

**Comment by faimin** [comment]
> 现在的逻辑是选中主题后，在本地会记住，下次进来还是上次选中的主题，不会重置的。你这边是怎么复现的？ @faimin

进入`APP`后手动切到深色模式，然后手动kill掉或者退后台自动被系统干掉，再次进入都是浅色模式。
我的`iOS`设置是`日落前保持浅色外观`，也就是会根据时间自动切换深浅模式，不知道和这个有没有关系

**Comment by jkpang** [comment]
最新版没有这个问题，可能我默默的修复了吧😂
