### ISSUE TITLE
关于 activity「即NEWS」 tab页的建议

### ISSUE THREAD

**Issue by superleeyom** [PPHubApp/PPHub-Feedback#659]
最近下载了PPHub，因为我个人比较关注activity，在pc端的activity中，可以直观的看到关注人star的项目的简介，截图如下：
![image](https://user-images.githubusercontent.com/22115219/95697161-6082fe00-0c70-11eb-9f43-71e35538fac6.png)

而PPHub的NEWS也就是activity中，只有star项目的名称，需要点进去才能查询项目，能否考虑跟pc一样，也**展示 star的项目的简介**呢，如果简介字数太长，可以考虑`...`的省略方式，这样的好处就是，可以快速知道当前项目的信息
![image](https://user-images.githubusercontent.com/22115219/95697255-af309800-0c70-11eb-83b3-9dafd8dbd166.png)
盼回复，谢谢

**Comment by jkpang** [comment]
嗯嗯，因为News这个tab使用的是GitHub的REST API，news这个接口(https://api.github.com/users/{username}/received_events)没有给到仓库的详细信息，只给到名称；等以后研究了GraphQL接口看能不能获取 @superleeyom

**Comment by superleeyom** [comment]
@jkpang 多谢采纳！
