### ISSUE TITLE
v2.4.10 - 新版本老是连不上服务器 上一个版本可以

### ISSUE THREAD

**Issue by jicheng0622** [PPHubApp/PPHub-Feedback#661]
运行环境: iPhone 6s Plus - iOS14.0.1 - v2.4.10(189)

**Comment by jkpang** [comment]
新版本没有改动网络请求相关的代码，应该是你所处的网络环境问题，有关于这个问题的具体说明：[说明：“无法连接服务器”、“请求数据错误”等问题](https://github.com/PPHubApp/PPHub-Feedback/issues/611)     @jicheng0622
