### ISSUE TITLE
v2.4.10 - 小组件上的 commit 显示图和 Ap...

### ISSUE THREAD

**Issue by tisfeng** [PPHubApp/PPHub-Feedback#662]
小组件上的 commit 显示图和 App 内部显示不一样

小组件的部分commit 显示丢失（好像是私有库提交）

（请问什么时候支持 iOS 14 widget ？）

运行环境: iPhone XS - iOS14.2 - v2.4.10(189)

**Comment by jkpang** [comment]
- commit显示不全是没有显示私有库的提交，需要在网页中打开以下设置：私有库提交数量对外可见
![image](https://user-images.githubusercontent.com/17583451/96693813-45279980-13ba-11eb-8397-7ab882fbfa54.png)

- iOS 14 widget 目前还没有好的产品设计，commit小格子会显的很大很丑，所以现在只能继续用iOS 13时代的widget了  

@tisfeng

**Comment by tisfeng** [comment]
感谢，问题已解决。  

“commit小格子会显的很大很丑”，这点不太理解，目前的小组件尺寸，和 iOS 14 的 Medium 差不多，UI 甚至都不用怎么修改，用 SwiftUI 重写一下就行啊。。（主要是非 iOS 14 的 Widget 被降权，现在 PPHub  Widget 显示在负一屏最下面，查看起来好不方便）
