### ISSUE TITLE
v2.4.10 - news 和 stars 无法显示

### ISSUE THREAD

**Issue by Tillerzzz** [PPHubApp/PPHub-Feedback#665]
运行环境: iPhone11 - iOS14.0.1 - v2.4.10(189)

**Comment by jkpang** [comment]
1、News没有内容说明你的账号：
- 没有Follow任何用户或您Follow的用户没有相关动态；
- 没有Watch任何代码库或您Watch的代码库没有相关动态；
- 其他用户没有对您的公开代码库提出Issues或者Pull request；

2、Stars没有显示：可能是账号没有Star过仓库

3、如果是报出请求出错的问题，可以看看这个说明：[说明：“无法连接服务器”、“请求数据错误”等问题](https://github.com/PPHubApp/PPHub-Feedback/issues/611)     

@Tillerzzz
