### ISSUE TITLE
v2.4.10 - Network connecting i...

### ISSUE THREAD

**Issue by LightgardenCC** [PPHubApp/PPHub-Feedback#668]
Network connecting is a large bad problem, while I can fastly browser other websites

运行环境: iPad 5 - iOS13.6.1 - v2.4.10(189)

**Comment by jkpang** [comment]
是国内的网络问题：[说明：“无法连接服务器”、“请求数据错误”等问题 #611](https://github.com/PPHubApp/PPHub-Feedback/issues/611)     @LightgardenCC

**Comment by LightgardenCC** [comment]
OK，_It means I have to modify my Ipad's DNS._
