### ISSUE TITLE
v2.4.10 - 浅色模式下，小组件里的git提交图展示空...

### ISSUE THREAD

**Issue by cat-walk** [PPHubApp/PPHub-Feedback#672]
浅色模式下，小组件里的git提交图展示空白。深色模式下正常。

运行环境: iPhone 6s Plus - iOS14.1 - v2.4.10(189)

**Comment by jkpang** [comment]
官方网站数据原因，示例：https://github.com/users/jkpang/contributions ，正在修复中......   @cat-walk

**Comment by jkpang** [comment]
v2.4.12已可更新 @cat-walk
