### ISSUE TITLE
v2.4.10 - no map data.
GitHub ...

### ISSUE THREAD

**Issue by yihong0618** [PPHubApp/PPHub-Feedback#673]
no map data.
GitHub 的小格子不见了。

运行环境: iPhone XR - iOS14.1 - v2.4.10(189)

**Comment by jkpang** [comment]
官方网站数据原因，示例：https://github.com/users/jkpang/contributions ，正在修复中......  @yihong0618

**Comment by yihong0618** [comment]
好的，发现切换夜间模式是有的~

**Comment by jkpang** [comment]
v2.4.12已可更新 @yihong0618
