### ISSUE TITLE
v2.4.12 - 个人中心提交图案又显示不了了

### ISSUE THREAD

**Issue by youlookwhat** [PPHubApp/PPHub-Feedback#681]
运行环境: iPhone 12 - iOS14.2 - v2.4.12(196)

**Comment by lowking** [comment]
+1

**Comment by jkpang** [comment]
GitHub修改了数据字段导致的，目前已提交修复版本，静待审核通过 @youlookwhat @lowking

**Comment by jkpang** [comment]
新的修复版本已审核通过，已可更新。 @youlookwhat @lowking
