### ISSUE TITLE
v2.4.12 - 好像活动的小格子又变空白了。

### ISSUE THREAD

**Issue by yihong0618** [PPHubApp/PPHub-Feedback#682]
运行环境: iPhone XR - iOS14.2 - v2.4.12(196)

**Comment by jkpang** [comment]
GitHub修改了数据字段导致的，目前已提交修复版本，静待审核通过  @yihong0618

**Comment by yihong0618** [comment]
@jkpang 谢谢谢谢~
哈哈，反馈了好多次，感谢每次作者都耐心解决~

**Comment by jkpang** [comment]
客气了~ 
新的修复版本已审核通过，已可更新。 @yihong0618
