### ISSUE TITLE
v2.4.13 - 黑夜模式下，个人中心提交的点全部是亮的

### ISSUE THREAD

**Issue by youlookwhat** [PPHubApp/PPHub-Feedback#685]
运行环境: iPhone 12 - iOS14.2.1 - v2.4.13(199)

**Comment by jkpang** [comment]
嗯嗯，已经发现了这个问题，修复版本已提交审核，感谢反馈~ @youlookwhat

**Comment by jkpang** [comment]
v2.4.15已可更新 @youlookwhat
