### ISSUE TITLE
v2.4.15 - 编辑功能呢？？？？？？？？？？？？？？？...

### ISSUE THREAD

**Issue by jiakunguo** [PPHubApp/PPHub-Feedback#689]
编辑功能呢？？？？？？？？？？？？？？？？？？？？？？？？

运行环境: iPhone SE2 - iOS14.2 - v2.4.15(200)

**Comment by jkpang** [comment]
没有编辑功能，手机上写代码没有一点生产力，体验太差 @jiakunguo

**Comment by lzr52o** [comment]
> 编辑功能呢？？？？？？？？？？？？？？？？？？？？？？？？
> 
> 运行环境: iPhone SE2 - iOS14.2 - v2.4.15(200)

别找他了，这App就是自己给他自己开发的，别人的意见他听不进去的，他一直是他以为
买了好几年这钱算是白花了
