### ISSUE TITLE
v2.4.15 - readme 404notfound
网...

### ISSUE THREAD

**Issue by yummytaro** [PPHubApp/PPHub-Feedback#690]
readme 404notfound
网络配置正确 python文件可以打开

运行环境: iPad Pro 11 Inch - iOS12.4 - v2.4.15(200)

**Comment by jkpang** [comment]
> readme 404notfound
> 网络配置正确 python文件可以打开
> 
> 运行环境: iPad Pro 11 Inch - iOS12.4 - v2.4.15(200)

是私有库吗？应该是是Cookie失效了，可以退出后重新登录一下
