### ISSUE TITLE
v2.4.15 - 希望news可以显示自己open的iss...

### ISSUE THREAD

**Issue by lowking** [PPHubApp/PPHub-Feedback#694]
希望news可以显示自己open的issue别人回复的内容

运行环境: iPhone XS - iOS14.2 - v2.4.15(200)

**Comment by jkpang** [comment]
News模块目前是用的Github restful接口，News Api目前会缺失你所说的issue内容，我看以后GraphQL是否会有相关接口 @lowking

**Comment by lowking** [comment]
> News模块目前是用的Github restful接口，News Api目前会缺失你所说的issue内容，我看以后GraphQL是否会有相关接口 @lowking

好的，刚上github才看到这个issue的通知，希望尽早支持news里面显示
