### ISSUE TITLE
v2.4.15 - ios14的小部件呢。。看到截图有才买的

### ISSUE THREAD

**Issue by wumaorg** [PPHubApp/PPHub-Feedback#695]
运行环境: iPhone XS Max - iOS14.3 - v2.4.15(200)

**Comment by lzr52o** [comment]
> 运行环境: iPhone XS Max - iOS14.3 - v2.4.15(200)

他那是老插件，没有新的
![Uploading 3856CA09-D322-475F-9B75-1DB5F6F8CEC4.jpeg…]()

**Comment by lzr52o** [comment]
> 运行环境: iPhone XS Max - iOS14.3 - v2.4.15(200)

那是老插件
![image](https://user-images.githubusercontent.com/33163140/103175208-34f0d680-48a3-11eb-8287-e79451ef9a14.jpeg)
![image](https://user-images.githubusercontent.com/33163140/103175212-3a4e2100-48a3-11eb-98db-de24d594ed87.jpeg)
