### ISSUE TITLE
v2.4.15 - 代码阅读界面，旋转屏幕后（横版）弹出菜单...

### ISSUE THREAD

**Issue by heliarmk** [PPHubApp/PPHub-Feedback#697]
代码阅读界面，旋转屏幕后（横版）弹出菜单，没有显示的把菜单收起来的按钮。目前只能再点击旋转屏幕回到竖版才能收起菜单

运行环境: iPhone XS Max - iOS14.3 - v2.4.15(200)

**Comment by jkpang** [comment]
v2.4.16已可更新 @heliarmk
