### ISSUE TITLE
v2.4.15 - 请问现在屏幕小组件还支持吗？如何设置？

### ISSUE THREAD

**Issue by brant-ruan** [PPHubApp/PPHub-Feedback#701]
Environment: iPhone11 - iOS14.2 - v2.4.15(200)

**Comment by jkpang** [comment]
目前还不支持iOS 14的小组件，只有iOS 13样式的组件 @brant-ruan

**Comment by jkpang** [comment]
v2.7.0已支持桌面小组件 @brant-ruan
