### ISSUE TITLE
v2.4.15 - 每次从别的app切换到pphub，pph...

### ISSUE THREAD

**Issue by retina007** [PPHubApp/PPHub-Feedback#704]
每次从别的app切换到pphub，pphub中的页面都要刷新下，本来看到中间部分，刷新下就又要从头看了！！望修复bug

运行环境: iPad Pro 11 Inch - iOS12.1 - v2.4.15(200)

**Comment by jkpang** [comment]
现在应该不会了，更新下最新版本看看 @retina007
