### ISSUE TITLE
v2.4.15 - 提交图全变空白了

### ISSUE THREAD

**Issue by GuyCui** [PPHubApp/PPHub-Feedback#711]
运行环境: iPhone11 - iOS14.3 - v2.4.15(200)

**Comment by jkpang** [comment]
嗯嗯，GitHub又调整数据字段了，正在修复中，会尽快更新上线 @GuyCui

**Comment by jkpang** [comment]
v2.4.16已可更新 @GuyCui

**Comment by GuyCui** [comment]
OK非常感谢

发自我的iPhone
