### ISSUE TITLE
v2.4.15 - 好像又不能显示提交记录点了

### ISSUE THREAD

**Issue by youlookwhat** [PPHubApp/PPHub-Feedback#712]
运行环境: iPhone 12 - iOS14.3 - v2.4.15(200)

**Comment by jkpang** [comment]
嗯嗯，GitHub又调整数据字段了，正在修复中，会尽快更新上线 @youlookwhat

**Comment by jkpang** [comment]
v2.4.16已可更新 @youlookwhat
