### ISSUE TITLE
v2.4.15 - 提交记录小绿块不显示了

### ISSUE THREAD

**Issue by MarshallMathersIII** [PPHubApp/PPHub-Feedback#714]
运行环境: iPhone XR - iOS14.3 - v2.4.15(200)

**Comment by jkpang** [comment]
嗯嗯，GitHub又调整数据字段了，正在修复中，会尽快更新上线 @MarshallMathersIII

**Comment by jkpang** [comment]
Because GitHub has adjusted the data fields again, it is being fixed and will be updated online as soon as possible   @MarshallMathersIII

**Comment by jkpang** [comment]
v2.4.16已可更新 @MarshallMathersIII
