### ISSUE TITLE
v2.4.16 - 请问怎么给一个repository提is...

### ISSUE THREAD

**Issue by xuben99** [PPHubApp/PPHub-Feedback#715]
请问怎么给一个repository提issuer

运行环境: iPad 8 - iOS14.3 - v2.4.16(205)

**Comment by jkpang** [comment]
![image](https://user-images.githubusercontent.com/17583451/109003807-d8fbd000-76e2-11eb-95bb-53a005a3190e.png)
进入仓库的issue界面，点击右上角的“+”按钮，可以提交issue。如果此仓库未开启issue权限，此按钮是没有的 @xuben99
