### ISSUE TITLE
v1.2.2(19) - 无法直接在app内提Issue

### ISSUE THREAD

**Issue by TimorYang** [PPHubApp/PPHub-Feedback#74]
讨论某个仓库的问题是，无法直接comment 因为是直接跳转网页，需要再登陆一次，体验不好。

运行环境: iPhone 7 - iOS11.2.2 - PPHub v1.2.2(19)

**Comment by jkpang** [comment]
最新版v1.8.1已支持提Issue功能，快去更新吧 @TimorYang
