### ISSUE TITLE
v2.4.20 - 如果能有桌面小组件，github仓库搜索...

### ISSUE THREAD

**Issue by mefengl** [PPHubApp/PPHub-Feedback#742]
如果能有桌面小组件，github仓库搜索 就好了。

Environment: iPhone SE2 - iOS14.5 - v2.4.20(210)

**Comment by mefengl** [comment]
[类似issues](https://github.com/PPHubApp/PPHub-Feedback/issues/701#issue-782109899)

**Comment by jkpang** [comment]
v2.7.0已支持桌面小组件  @mefengl

**Comment by jkpang** [comment]
v2.7.0已支持桌面小组件  @mefengl
