### ISSUE TITLE
v2.5.0 - 下载代码一直连接不上，news页没有内容

### ISSUE THREAD

**Issue by Cuizhenzhen** [PPHubApp/PPHub-Feedback#762]
运行环境: iPhone 12 - iOS14.6 - v2.5.0(215)

**Comment by jkpang** [comment]
- PPHub 没有下载代码的功能哦（连接不上和国内网络有关）；
- News 也没内容是账户的数据问题，看看这个issue : [news 和 stars 无法显示](https://github.com/PPHubApp/PPHub-Feedback/issues/665)
