### ISSUE TITLE
v2.5.2 - 小组件里找不到pphub git热力图

### ISSUE THREAD

**Issue by runtimme** [PPHubApp/PPHub-Feedback#780]
运行环境: iPhone 13 Pro - iOS15.0 - v2.5.2(221)

**Comment by jkpang** [comment]
v2.7.0已支持小组件（实在抱歉哈，鸽了这么久，因为个人工作和生小宝宝的原因，导致没有太多精力放在 PPHub 上，但我不会放弃 PPHub 的更新的）
@runtimme @cattail5
