### ISSUE TITLE
v2.5.2 - 暗黑模式 readme中的文字非常的浅，...

### ISSUE THREAD

**Issue by kangpeilun** [PPHubApp/PPHub-Feedback#785]
暗黑模式 readme中的文字非常的浅，很难看清楚，不过我很喜欢暗黑模式的风格。希望尽快修复一下

运行环境: iPhone XR - iOS15.0 - v2.5.2(221)

**Comment by jkpang** [comment]
readme 的显示效果已重新优化，更新下最新的 v2.6.0 试试 @kangpeilun
