### ISSUE TITLE
v2.5.3 - Font colour stay bla...

### ISSUE THREAD

**Issue by MatrixLau** [PPHubApp/PPHub-Feedback#793]
Font colour stay black while I’m surfing README in dark mode

Environment: iPhone XR - iOS14.3 - v2.5.3(225)

**Comment by jkpang** [comment]
> Font colour stay black while I’m surfing README in dark mode

I've updated v2.5.4 today, see if there are still such problems

**Comment by MatrixLau** [comment]
Problem solved.👍👍👍
