### ISSUE TITLE
v1.3.1(25) - new feature

### ISSUE THREAD

**Issue by yuzhiquan** [PPHubApp/PPHub-Feedback#80]
1 夜间模式
2 可以下载repo到本地查看

运行环境: iPad Mini 2 - iOS11.0.3 - PPHub v1.3.1(25)

**Comment by jkpang** [comment]
1、PPHub v2.0.0已可用，已添加黑暗模式；
2、下载repo至本地可以使用Working Copy，在仓库详情页-右下角菜单按钮-左滑至第二页-Working Copy，即可享受专业的代码查看、编辑等功能。
@yuzhiquan
