### ISSUE TITLE
v1.3.1(25) - 一个功能的需求

### ISSUE THREAD

**Issue by Quorafind** [PPHubApp/PPHub-Feedback#82]
如果可以的话，希望能够出现一个收藏夹的按钮。在手机端能够实现快速查找star过的项目中的某个项目。因为watching需要收到太多邮件。而且我也发现了手机端查看不了your stars。对于一个平时喜欢把github当社区逛的人来说，需要收藏功能

运行环境: iPhone 7 - iOS10.3.3 - PPHub v1.3.1(25)

**Comment by jkpang** [comment]
恩恩, 感谢你的建议. 在后续的版本中我会将your stars独立出一个模块, 方便查找. 不过现在PPHub也是可以查看your stars的, 只是还不支持搜索查找: 看下图. (ps: 这段时间个人事情比较多,计划可能要延后一段时间, 感谢支持 )
![image](https://user-images.githubusercontent.com/17583451/37697179-5557662e-2d16-11e8-9dee-5e756a4cd9af.png)
![image](https://user-images.githubusercontent.com/17583451/37697238-a0ce11c0-2d16-11e8-8bf5-20994b56cb38.png)
 @Quorafind

**Comment by fiigii** [comment]
有个Bug，Stars界面显示的全是最近star的一个repo
![image](https://user-images.githubusercontent.com/1263030/46379974-727b4080-c655-11e8-8f39-7c4d8ef05bc3.png)
![image](https://user-images.githubusercontent.com/1263030/46379988-8161f300-c655-11e8-96ee-38407d62254e.png)

**Comment by jkpang** [comment]
好的，已知悉，国庆回来查看这个问题 @fiigii

**Comment by fiigii** [comment]
谢谢，这个问题是间歇性出现的，很难复现……
