### ISSUE TITLE
v2.6.0 - 经常无法加载项目

### ISSUE THREAD

**Issue by WuG978** [PPHubApp/PPHub-Feedback#820]
Environment: iPhone 11 - iOS15.2.1 - v2.6.0(230)

**Comment by jkpang** [comment]
我这边没有复现，请问是哪个页面提示都无法加载？方便贴个仓库的链接嘛？ @WuG978

**Comment by WuG978** [comment]
https://github.com/wbthomason/packer.nvim


https://github.com/nvim-lua/lsp_extensions.nvim

这里我列举上述两个项目，显示load fail，如附件截图所示。
------------------ 原始邮件 ------------------
From: jkpang ***@***.***&gt;
发送时间: 01/25/2022, 21:37
To: PPHubApp/PPHub-Feedback ***@***.***&gt;
抄送: Gino ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [PPHubApp/PPHub-Feedback] v2.6.0 - 经常无法加载项目 (Issue #820)





------------------ 原始邮件 ------------------
From: jkpang ***@***.***&gt;
发送时间: 01/25/2022, 21:37
To: PPHubApp/PPHub-Feedback ***@***.***&gt;
抄送: Gino ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [PPHubApp/PPHub-Feedback] v2.6.0 - 经常无法加载项目 (Issue #820)





 
我这边没有复现，请问是哪个页面提示都无法加载？方便贴个仓库的链接嘛？ @WuG978
 
&mdash;

**Comment by jkpang** [comment]
你是通过 浏览器 或者复制仓库链接 跳转到PPHub查看仓库详情才出现这样的问题吗？
我刚刚排查了下，通过搜索进入这两个仓库，是正常的，
但是 通过 浏览器 或者复制仓库链接 跳转到PPHub查看仓库详情 就会提示 “load fail”
因为这两个仓库名称带有` . `符号，导致仓库名称没有识别完整，所以会进不去，我会尽快修复这个问题 

@WuG978

**Comment by WuG978** [comment]
> 你是通过 浏览器 或者复制仓库链接 跳转到PPHub查看仓库详情才出现这样的问题吗？ 我刚刚排查了下，通过搜索进入这两个仓库，是正常的， 但是 通过 浏览器 或者复制仓库链接 跳转到PPHub查看仓库详情 就会提示 “load fail” 因为这两个仓库名称带有`.`符号，导致仓库名称没有识别完整，所以会进不去，我会尽快修复这个问题
> 
> @WuG978

感谢。

**Comment by jkpang** [comment]
v2.6.5已修复这个问题，已可更新 @WuG978
