### ISSUE TITLE
markdown文件内链接相对路径的资源无法通过点击链接直达或者无法渲染（比如图片无法渲染出来）

### ISSUE THREAD

**Issue by iuvhub** [PPHubApp/PPHub-Feedback#821]
![image](https://user-images.githubusercontent.com/89133723/151522765-ff607ccb-ab9a-4d75-b545-6699f2a74047.png)

**Comment by iuvhub** [comment]
iPhone x 15.2.1

**Comment by jkpang** [comment]
- `点击相对路径文件无法查看 `已修复，v2.6.7 已提交苹果审核；
- `图片渲染不出来`应该是国内的网络问题，挂梯子就行。
@iuvhub

**Comment by jkpang** [comment]
v2.6.7已可更新 @iuvhub
