### ISSUE TITLE
issues只能看不能直接回复，还需要登录

### ISSUE THREAD

**Issue by hiifong** [PPHubApp/PPHub-Feedback#824]
![A0235E049BAA157DD4133407B15D3A6D](https://user-images.githubusercontent.com/89133723/153704455-7567eadb-8be2-470b-922d-bef1db076ffd.png)

**Comment by jkpang** [comment]
应该是cookie失效了，重新授权登录下就好 @iuvhub

**Comment by iuvhub** [comment]
> 应该是cookie失效了，重新授权登录下就好 @iuvhub
谢谢
