### ISSUE TITLE
v2.6.7 - 查看今日动态，如何选择全部

### ISSUE THREAD

**Issue by Huauauaa** [PPHubApp/PPHub-Feedback#826]
Environment: iPhone 13 - iOS15.2.1 - v2.6.7(240)

**Comment by jkpang** [comment]
Trending 的时间范围选项，只有 `今日、本周、本月` 的选项，没有全部哦 @Huauauaa

**Comment by Huauauaa** [comment]
什么时候加上呢, 感觉还挺有用的 @jkpang

**Comment by jkpang** [comment]
> 什么时候加上呢, 感觉还挺有用的 @jkpang

Trending 官方网站就只有这三个选项，没有办法加哦  @Huauauaa 

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/17583451/154180048-44a604b4-11a1-43a3-a6ae-d7e635c1cb94.png">
