### ISSUE TITLE
v2.6.7 - 热门榜单无法正确筛选C#开发语言的仓库

### ISSUE THREAD

**Issue by Zoranner** [PPHubApp/PPHub-Feedback#830]
运行环境: iPhone 12 Pro - iOS15.3.1 - v2.6.7(240)

**Comment by jkpang** [comment]
我这边测试了可以哦，可能是网络的问题？搭个梯子看看？ @Zoranner 
<img width="240" alt="image" src="https://user-images.githubusercontent.com/17583451/167052852-dc168bce-841d-4f6b-ac27-7285490b13a5.png">

**Comment by Zoranner** [comment]
> 我这边测试了可以哦，可能是网络的问题？搭个梯子看看？ @Zoranner <img alt="image" width="240" src="https://user-images.githubusercontent.com/17583451/167052852-dc168bce-841d-4f6b-ac27-7285490b13a5.png">

我表述有些问题，是无法正确筛选，截图中的筛选结果并不是C#语言的，而是默认筛选了语言列表第一个语言的结果。

**Comment by jkpang** [comment]
明白了，我今天下班了排查下 @Zoranner

**Comment by jkpang** [comment]
v2.7.2已可更新 @Zoranner
