### ISSUE TITLE
v1.3.2(26) - feature request

### ISSUE THREAD

**Issue by droid-Q** [PPHubApp/PPHub-Feedback#89]
可以以付费扩展包的形式推出主题包，我比较喜欢dark  theme。

运行环境: iPhone X - iOS11.3 - PPHub v1.3.2(26)

**Comment by jkpang** [comment]
在后续的版本我会考虑加入夜间模式（不收费）， 现在还不确定（ps：推出付费主题包估计要被骂死😂😂😂）， 谢谢建议哈 @droid-Q

**Comment by droid-Q** [comment]
@jkpang 骂死不至于，对于可以多种主题选择的主题包进行收费我觉得是合情合理的，又不是强制，不过如果只是简单的夜间模式就另当别论了。

**Comment by jkpang** [comment]
Hi，
PPHub v2.0.0已可用
- 新增：Dark Mode（黑暗模式）；
- 新增：完美支持iPad多任务分屏模式；
- 优化：调整界面UI控件的排版、样式。

付费主题包可能暂时不会考虑啦，谢谢建议 @droid-Q
