### ISSUE TITLE
2.7.7 ios 16.1 ipad 16.1 都无法通过 github 登陆

### ISSUE THREAD

**Issue by sinlov** [PPHubApp/PPHub-Feedback#897]
- 排除网络问题（同样网络 Working Copy 这个app也是通过 api.github.com 能使用）
- github 账号密码登陆可用，登陆正常
- 登陆账号密码通过后，显示 github 授权 确认时，闪烁一下
- 然后卡白屏

![IMG_4CB5F274AC5E-1](https://user-images.githubusercontent.com/3433415/200126992-73364140-1c31-4dfc-b61b-936f7968c017.jpeg)

ipad 为这个显示

![IMG_BAA8168A8B0D-1](https://user-images.githubusercontent.com/3433415/200127097-8bc16a36-0745-4b43-a475-2569b8af2b42.jpeg)

## other

- `Working Copy` 授权显示为

![IMG_15D478757D7D-1](https://user-images.githubusercontent.com/3433415/200127375-dd691038-3cd3-465a-9ebc-da6868f1772e.jpeg)

**Comment by jkpang** [comment]
我这边卸载了 App，重新登陆授权试了下，没有重现这个问题诶，你卸载重装试试？ @sinlov 
我的设备是 iPhone 12，移动 4g 网络，iOS 16.1

**Comment by opa833** [comment]
我也遇上了同样的问题 14pm 16.1  另一个备用机却正常

**Comment by ljpcool** [comment]
14pro ios16.1 也出现一样的空白页

**Comment by jkpang** [comment]
啊，看下系统设置里是否授予了PPHub 网络权限？

**Comment by elnfnoosm** [comment]
同上。iPhone14 pro 
ios16.1.1，app最新版。登陆授权就白屏。现在没法用

**Comment by elnfnoosm** [comment]
今天刚下的

**Comment by Nergrove** [comment]
同上，iOS16，删除重装以后就登不上了，梯子具备，排除网络问题，授权后就白屏。

**Comment by jkpang** [comment]
太奇怪了，我这边尝试了重新登陆，卸载重装，都没问题，也是 iOS 16.1 的系统，猜测可能是 iOS 16.1 Webkit 的 Bug，我周末尝试修复下，看能不能找个有问题的机器；
你们可以先去 GitHub 申请 access token: https://github.com/settings/tokens ，然后在 PPHub 登录页面右上角点击 access token 按钮 输入登录
@sinlov @pikaqiu-go @elnfnoosm @Nergrove @opa833

**Comment by ljpcool** [comment]
> 太奇怪了，我这边尝试了重新登陆，卸载重装，都没问题，也是 iOS 16.1 的系统，猜测可能是 iOS 16.1 Webkit 的 Bug，我周末尝试修复下，看能不能找个有问题的机器；
> 你们可以先去 GitHub 申请 access token: https://github.com/settings/tokens ，然后在 PPHub 登录页面右上角点击 access token 按钮 输入登录
> @sinlov @pikaqiu-go @elnfnoosm @Nergrove @opa833

access token 貌似也有问题的，已经试过了，同样都是白屏

**Comment by jkpang** [comment]
我大概明白了，你们应该都是 首次授权 PPHub 访问 GitHub，首次授权在 iOS 16 上就会有问题。而我早就授权了，所以不会访问首次登录授权页面，也就没有出现问题。
目前在我找到解决方案之前，你们首次授权可以通过iPhone Safari 访问以下授权链接来进行，然后再打开 PPHub 登录：
仅访问公共库：https://github.com/login/oauth/authorize?allow_signup=false&client_id=5d79469d95f67fe366c9&scope=user,public_repo,notifications,read:discussion,read:org

访问公共库 + 私有库：https://github.com/login/oauth/authorize?allow_signup=false&client_id=5d79469d95f67fe366c9&scope=user,repo,notifications,read:discussion,read:org

@sinlov @pikaqiu-go @elnfnoosm @Nergrove @opa833

**Comment by ljpcool** [comment]
> 我大概明白了，你们应该都是 首次授权 PPHub 访问 GitHub，首次授权也在 iOS 16 上就会有问题。而我早就授权了，所以不会访问首次登录授权页面，也就没有出现问题。 目前在我找到解决方案之前，你们首次授权可以通过iPhone Safari 访问以下授权链接来进行，然后再打开 PPHub 登录： 仅访问公共库：https://github.com/login/oauth/authorize?allow_signup=false&client_id=5d79469d95f67fe366c9&scope=user,public_repo,notifications,read:discussion,read:org
> 
> 访问公共库 + 私有库：https://github.com/login/oauth/authorize?allow_signup=false&client_id=5d79469d95f67fe366c9&scope=user,repo,notifications,read:discussion,read:org
> 
> @sinlov @pikaqiu-go @elnfnoosm @Nergrove @opa833

是的，都是首次授权，中午试一下你提供的方法~

**Comment by ljpcool** [comment]
> 我大概明白了，你们应该都是 首次授权 PPHub 访问 GitHub，首次授权在 iOS 16 上就会有问题。而我早就授权了，所以不会访问首次登录授权页面，也就没有出现问题。 目前在我找到解决方案之前，你们首次授权可以通过iPhone Safari 访问以下授权链接来进行，然后再打开 PPHub 登录： 仅访问公共库：https://github.com/login/oauth/authorize?allow_signup=false&client_id=5d79469d95f67fe366c9&scope=user,public_repo,notifications,read:discussion,read:org
> 
> 访问公共库 + 私有库：https://github.com/login/oauth/authorize?allow_signup=false&client_id=5d79469d95f67fe366c9&scope=user,repo,notifications,read:discussion,read:org
> 
> @sinlov @pikaqiu-go @elnfnoosm @Nergrove @opa833

使用该方法，已解决~

**Comment by elnfnoosm** [comment]
已解决。确实如你所说，首次授权白屏。
使用网页授权后，已成功进入app



> 我大概明白了，你们应该都是 首次授权 PPHub 访问 GitHub，首次授权在 iOS 16 上就会有问题。而我早就授权了，所以不会访问首次登录授权页面，也就没有出现问题。
> 
> 目前在我找到解决方案之前，你们首次授权可以通过iPhone Safari 访问以下授权链接来进行，然后再打开 PPHub 登录：
> 
> 仅访问公共库：https://github.com/login/oauth/authorize?allow_signup=false&client_id=5d79469d95f67fe366c9&scope=user,public_repo,notifications,read:discussion,read:org
> 
> 
> 
> 访问公共库 + 私有库：https://github.com/login/oauth/authorize?allow_signup=false&client_id=5d79469d95f67fe366c9&scope=user,repo,notifications,read:discussion,read:org
> 
> 
> 
> @sinlov @pikaqiu-go @elnfnoosm @Nergrove @opa833
> 
>

**Comment by jkpang** [comment]
昨晚凌晨攻坚 ，已找到解决此系统 bug 的方法，v2.7.9 已可更新，抱歉经过这么久才修复，一直没找到根本原因😂
