### ISSUE TITLE
v2.7.8 - 登录授权页白屏

### ISSUE THREAD

**Issue by IraXu** [PPHubApp/PPHub-Feedback#904]
设备：iPhone 13
系统：iOS 16.1.1
缺陷：登录授权页白屏，无法进行授权并进入首页

**Comment by IraXu** [comment]
拿了一台低IOS版本设备授权并登录旧版本PPHUB后，再用16的设备登录上了（显示已授权）

**Comment by jkpang** [comment]
收到，正在排查原因，猜测是 iOS 16.1 webkit 的问题，具体讨论可看这个 issues: #897

**Comment by jkpang** [comment]
已针对此系统 bug 进行修复，可更新最新版本 v2.7.9
