### ISSUE TITLE
v2.7.10 - 应用无法打开

### ISSUE THREAD

**Issue by ChengLuffy** [PPHubApp/PPHub-Feedback#923]
运行环境: iPhone Xs - iOS16.4 - v2.7.10(打不开所以不知道)

在 LanuchScreen 显示前就已经闪退

以下是某一次闪退日志

[PPHub-2023-04-03-144348.ips.zip](https://github.com/PPHubApp/PPHub-Feedback/files/11135523/PPHub-2023-04-03-144348.ips.zip)

**Comment by jkpang** [comment]
感谢反馈，修复版本已在路上了，明天应该可以更新，目前可以通过卸载重装解决这个问题 @ChengLuffy

**Comment by ChengLuffy** [comment]
已正常
